XmmsClient: clients/lib/xmmsclient/c2c.c File Reference
c2c.c File Reference
#include "xmmsclient/xmmsclient.h"
#include "xmmsclientpriv/xmmsclient.h"
#include "xmmsclientpriv/xmmsclient_ipc.h"
#include "xmmsc/xmmsc_idnumbers.h"
Functions
xmmsc_result_t * xmmsc_c2c_send (xmmsc_connection_t *c, int dest, xmms_c2c_reply_policy_t reply_policy, xmmsv_t *payload)
Send a client-to-client message.
xmmsc_result_t * xmmsc_c2c_reply (xmmsc_connection_t *c, int msgid, xmms_c2c_reply_policy_t reply_policy, xmmsv_t *payload)
Reply to a client-to-client message.
int32_t xmmsc_c2c_get_own_id (xmmsc_connection_t *c)
Request your own client id.
xmmsc_result_t * xmmsc_c2c_get_connected_clients (xmmsc_connection_t *c)
Request a list of connected client ids.
xmmsc_result_t * xmmsc_c2c_ready (xmmsc_connection_t *c)
Notify the client's api is ready for query.
xmmsc_result_t * xmmsc_c2c_get_ready_clients (xmmsc_connection_t *c)
Request a list of clients ready for c2c communication.
xmmsc_result_t * xmmsc_broadcast_c2c_message (xmmsc_connection_t *c)
Request the client-to-client message broadcast.
xmmsc_result_t * xmmsc_broadcast_c2c_ready (xmmsc_connection_t *c)
Request the client service ready broadcast.
xmmsc_result_t * xmmsc_broadcast_c2c_client_connected (xmmsc_connection_t *c)
Request the client connected broadcast.
xmmsc_result_t * xmmsc_broadcast_c2c_client_disconnected (xmmsc_connection_t *c)
Request the client disconnected broadcast.
Function Documentation
xmmsc_result_t* xmmsc_broadcast_c2c_client_connected (xmmsc_connection_t * c)
Request the client connected broadcast.
This broadcast gets triggered when a new client connects, and contains the new client's id.
Parameters
c The connection to the server.
Definition at line 200 of file c2c.c.
xmmsc_result_t* xmmsc_broadcast_c2c_client_disconnected (xmmsc_connection_t * c)
Request the client disconnected broadcast.
This broadcast gets triggered when a client disconnects, and contains the disconnected client's id.
Parameters
c The connection to the server.
Definition at line 218 of file c2c.c.
xmmsc_result_t* xmmsc_broadcast_c2c_message (xmmsc_connection_t * c)
Request the client-to-client message broadcast.
This broadcast gets triggered when messages from other clients are received.
Parameters
c The connection to the server.
Definition at line 160 of file c2c.c.
Referenced by xmmsc_sc_init().
xmmsc_result_t* xmmsc_broadcast_c2c_ready (xmmsc_connection_t * c)
Request the client service ready broadcast.
This broadcast gets triggered when a client notify the server its api is ready.
Parameters
c The connection to the server.
Definition at line 182 of file c2c.c.
xmmsc_result_t* xmmsc_c2c_get_connected_clients (xmmsc_connection_t * c)
Request a list of connected client ids.
Parameters
c The connection to the server.
Definition at line 121 of file c2c.c.
int32_t xmmsc_c2c_get_own_id (xmmsc_connection_t * c)
Request your own client id.
Parameters
c The connection to the server.
Definition at line 109 of file c2c.c.
xmmsc_result_t* xmmsc_c2c_get_ready_clients (xmmsc_connection_t * c)
Request a list of clients ready for c2c communication.
Parameters
c The connection to the server.
Definition at line 146 of file c2c.c.
xmmsc_result_t* xmmsc_c2c_ready (xmmsc_connection_t * c)
Notify the client's api is ready for query.
Definition at line 133 of file c2c.c.
xmmsc_result_t* xmmsc_c2c_reply (xmmsc_connection_t * c, int msgid, xmms_c2c_reply_policy_t reply_policy, xmmsv_t * payload)
Reply to a client-to-client message.
Parameters
c The connection to the server.
msgid The id of the message you are replying to.
reply_policy Whether to expect no reply, a single reply or multiple replies for this message.
payload The contents of the reply.
Definition at line 74 of file c2c.c.
Referenced by xmmsc_sc_broadcast_emit().
xmmsc_result_t* xmmsc_c2c_send (xmmsc_connection_t * c, int dest, xmms_c2c_reply_policy_t reply_policy, xmmsv_t * payload)
Send a client-to-client message.
Parameters
c The connection to the server.
reply_policy Whether to expect no reply, a single reply or multiple replies for this message.
payload The contents of the message.
Definition at line 30 of file c2c.c.
Referenced by xmmsc_sc_broadcast_subscribe(), and xmmsc_sc_call().