XmmsClient: clients/lib/xmmsclient/service/common.c File Reference
common.c File Reference
#include "common.h"
Functions
xmmsc_sc_interface_entity_t * xmmsc_sc_locate_interface_entity (xmmsc_connection_t *c, xmmsv_t *path)
Resolve a path to a registered interface entity.
void xmmsc_sc_create_root_namespace (xmmsc_connection_t *c)
Function Documentation
void xmmsc_sc_create_root_namespace (xmmsc_connection_t * c)
Referenced by xmmsc_sc_init().
xmmsc_sc_interface_entity_t* xmmsc_sc_locate_interface_entity (xmmsc_connection_t * c, xmmsv_t * path)
Resolve a path to a registered interface entity.
An empty path resolves to the root namespace.
Referenced by xmmsc_sc_broadcast_emit(), and xmmsc_sc_namespace_lookup().