XmmsClient: PlaylistControl
PlaylistControl
XMMSClient
This controls the playlist.
Functions
xmmsc_result_t * xmmsc_playlist_current_pos (xmmsc_connection_t *c, const char *playlist)
Retrive the current position in the playlist.
xmmsc_result_t * xmmsc_playlist_current_active (xmmsc_connection_t *c)
Retrive the name of the active playlist.
xmmsc_result_t * xmmsc_playlist_list (xmmsc_connection_t *c)
List the existing playlists.
xmmsc_result_t * xmmsc_playlist_create (xmmsc_connection_t *c, const char *playlist)
Create a new empty playlist.
xmmsc_result_t * xmmsc_playlist_shuffle (xmmsc_connection_t *c, const char *playlist)
Shuffles the current playlist.
xmmsc_result_t * xmmsc_playlist_sort (xmmsc_connection_t *c, const char *playlist, xmmsv_t *properties)
Sorts the playlist according to the list of properties (xmmsv_t containing a list of strings).
xmmsc_result_t * xmmsc_playlist_clear (xmmsc_connection_t *c, const char *playlist)
Clears the current playlist.
xmmsc_result_t * xmmsc_playlist_replace (xmmsc_connection_t *c, const char *playlist, xmmsv_t *coll, xmms_playlist_position_action_t action)
Replaces the current playlist.
xmmsc_result_t * xmmsc_playlist_remove (xmmsc_connection_t *c, const char *playlist)
Remove the given playlist.
xmmsc_result_t * xmmsc_playlist_list_entries (xmmsc_connection_t *c, const char *playlist)
List current playlist.
xmmsc_result_t * xmmsc_playlist_insert_id (xmmsc_connection_t *c, const char *playlist, int pos, int id)
Insert a medialib id at given position in playlist.
xmmsc_result_t * xmmsc_playlist_insert_url (xmmsc_connection_t *c, const char *playlist, int pos, const char *url)
Insert entry at given position in playlist.
xmmsc_result_t * xmmsc_playlist_rinsert (xmmsc_connection_t *c, const char *playlist, int pos, const char *url)
Insert a directory recursivly at a given position in the playlist.
xmmsc_result_t * xmmsc_playlist_rinsert_encoded (xmmsc_connection_t *c, const char *playlist, int pos, const char *url)
Insert a directory recursivly at a given position in the playlist.
xmmsc_result_t * xmmsc_playlist_insert_args (xmmsc_connection_t *c, const char *playlist, int pos, const char *url, int numargs, const char **args)
Insert entry at given position in playlist with args.
xmmsc_result_t * xmmsc_playlist_insert_full (xmmsc_connection_t *c, const char *playlist, int pos, const char *url, xmmsv_t *args)
Insert entry at given position in playlist with args.
xmmsc_result_t * xmmsc_playlist_insert_encoded (xmmsc_connection_t *c, const char *playlist, int pos, const char *url)
Insert entry at given position in playlist.
xmmsc_result_t * xmmsc_playlist_insert_collection (xmmsc_connection_t *c, const char *playlist, int pos, xmmsv_t *coll, xmmsv_t *order)
Queries the medialib for media and inserts the matching ones to the current playlist at the given position.
xmmsc_result_t * xmmsc_playlist_add_id (xmmsc_connection_t *c, const char *playlist, int id)
Add a medialib id to the playlist.
xmmsc_result_t * xmmsc_playlist_add_url (xmmsc_connection_t *c, const char *playlist, const char *url)
Add the url to the playlist.
xmmsc_result_t * xmmsc_playlist_radd (xmmsc_connection_t *c, const char *playlist, const char *url)
Adds a directory recursivly to the playlist.
xmmsc_result_t * xmmsc_playlist_radd_encoded (xmmsc_connection_t *c, const char *playlist, const char *url)
Adds a directory recursivly to the playlist.
xmmsc_result_t * xmmsc_playlist_add_args (xmmsc_connection_t *c, const char *playlist, const char *url, int nargs, const char **args)
Add the url to the playlist with arguments.
xmmsc_result_t * xmmsc_playlist_add_full (xmmsc_connection_t *c, const char *playlist, const char *url, xmmsv_t *args)
Add the url to the playlist with arguments.
xmmsc_result_t * xmmsc_playlist_add_encoded (xmmsc_connection_t *c, const char *playlist, const char *url)
Add the url to the playlist.
xmmsc_result_t * xmmsc_playlist_add_idlist (xmmsc_connection_t *c, const char *playlist, xmmsv_t *coll)
Adds media in idlist to a playlist.
xmmsc_result_t * xmmsc_playlist_add_collection (xmmsc_connection_t *c, const char *playlist, xmmsv_t *coll, xmmsv_t *order)
Queries the medialib for media and adds the matching ones to the current playlist.
xmmsc_result_t * xmmsc_playlist_move_entry (xmmsc_connection_t *c, const char *playlist, int cur_pos, int new_pos)
Move a playlist entry to a new position (absolute move)
xmmsc_result_t * xmmsc_playlist_remove_entry (xmmsc_connection_t *c, const char *playlist, int pos)
Remove an entry from the playlist.
xmmsc_result_t * xmmsc_broadcast_playlist_changed (xmmsc_connection_t *c)
Request the playlist changed broadcast from the server.
xmmsc_result_t * xmmsc_broadcast_playlist_current_pos (xmmsc_connection_t *c)
Request the playlist current pos broadcast.
xmmsc_result_t * xmmsc_playlist_set_next (xmmsc_connection_t *c, int pos)
Set next entry in the playlist.
xmmsc_result_t * xmmsc_playlist_set_next_rel (xmmsc_connection_t *c, int pos)
Same as xmmsc_playlist_set_next but relative to the current postion.
xmmsc_result_t * xmmsc_playlist_load (xmmsc_connection_t *c, const char *name)
Load a playlist as the current active playlist.
xmmsc_result_t * xmmsc_broadcast_playlist_loaded (xmmsc_connection_t *c)
Request the playlist_loaded broadcast.
Detailed Description
This controls the playlist.
Function Documentation
xmmsc_result_t* xmmsc_broadcast_playlist_changed (xmmsc_connection_t * c)
Request the playlist changed broadcast from the server.
Everytime someone manipulate the playlist this will be emitted.
xmmsc_result_t* xmmsc_broadcast_playlist_current_pos (xmmsc_connection_t * c)
Request the playlist current pos broadcast.
When the position in the playlist is changed this will be called.
xmmsc_result_t* xmmsc_broadcast_playlist_loaded (xmmsc_connection_t * c)
Request the playlist_loaded broadcast.
This will be called if a playlist is loaded server-side. The argument will be a string with the playlist name.
xmmsc_result_t* xmmsc_playlist_add_args (xmmsc_connection_t * c, const char * playlist, const char * url, int nargs, const char ** args)
Add the url to the playlist with arguments.
Parameters
c The connection structure.
playlist The playlist in which to add the media.
url path.
nargs The number of arguments
args array of numargs strings used as arguments
xmmsc_result_t* xmmsc_playlist_add_collection (xmmsc_connection_t * c, const char * playlist, xmmsv_t * coll, xmmsv_t * order)
Queries the medialib for media and adds the matching ones to the current playlist.
Parameters
c The connection structure.
playlist The playlist in which to add the media.
coll The collection to find media in the medialib.
order The list of properties by which to order the matching media, passed as an xmmsv_t list of strings.
xmmsc_result_t* xmmsc_playlist_add_encoded (xmmsc_connection_t * c, const char * playlist, const char * url)
Add the url to the playlist.
The url should be absolute to the server-side AND encoded.
Parameters
c The connection structure.
playlist The playlist in which to add the media.
url path.
Referenced by xmmsc_playlist_add_args(), and xmmsc_playlist_add_full().
xmmsc_result_t* xmmsc_playlist_add_full (xmmsc_connection_t * c, const char * playlist, const char * url, xmmsv_t * args)
Add the url to the playlist with arguments.
Parameters
c The connection structure.
playlist The playlist in which to add the media.
url path.
nargs The number of arguments
args array of numargs strings used as arguments
Referenced by xmmsc_playlist_add_url().
xmmsc_result_t* xmmsc_playlist_add_id (xmmsc_connection_t * c, const char * playlist, int id)
Add a medialib id to the playlist.
Parameters
c The connection structure.
playlist The playlist in which to add the media.
id A medialib id.
xmmsc_result_t* xmmsc_playlist_add_idlist (xmmsc_connection_t * c, const char * playlist, xmmsv_t * coll)
Adds media in idlist to a playlist.
Parameters
c The connection structure.
playlist The playlist in which to add the media.
coll The collection to find media in the medialib.
xmmsc_result_t* xmmsc_playlist_add_url (xmmsc_connection_t * c, const char * playlist, const char * url)
Add the url to the playlist.
The url should be absolute to the server-side. Note that you will have to include the protocol for the url to. ie: file://mp3/my_mp3s/first.mp3.
Parameters
c The connection structure.
playlist The playlist in which to add the media.
url path.
xmmsc_result_t* xmmsc_playlist_clear (xmmsc_connection_t * c, const char * playlist)
Clears the current playlist.
xmmsc_result_t* xmmsc_playlist_create (xmmsc_connection_t * c, const char * playlist)
Create a new empty playlist.
xmmsc_result_t* xmmsc_playlist_current_active (xmmsc_connection_t * c)
Retrive the name of the active playlist.
xmmsc_result_t* xmmsc_playlist_current_pos (xmmsc_connection_t * c, const char * playlist)
Retrive the current position in the playlist.
xmmsc_result_t* xmmsc_playlist_insert_args (xmmsc_connection_t * c, const char * playlist, int pos, const char * url, int numargs, const char ** args)
Insert entry at given position in playlist with args.
Parameters
c The connection structure.
playlist The playlist in which to insert the media.
pos A position in the playlist
url The URL to insert
numargs The number of arguments
args array of numargs strings used as arguments
xmmsc_result_t* xmmsc_playlist_insert_collection (xmmsc_connection_t * c, const char * playlist, int pos, xmmsv_t * coll, xmmsv_t * order)
Queries the medialib for media and inserts the matching ones to the current playlist at the given position.
Parameters
c The connection structure.
playlist The playlist in which to insert the media.
pos A position in the playlist
coll The collection to find media in the medialib.
order The list of properties by which to order the matching media, passed as an xmmsv_t list of strings.
xmmsc_result_t* xmmsc_playlist_insert_encoded (xmmsc_connection_t * c, const char * playlist, int pos, const char * url)
Insert entry at given position in playlist.
Same as xmmsc_playlist_insert_url but takes an encoded url instead.
Parameters
c The connection structure.
playlist The playlist in which to insert the media.
pos A position in the playlist
url The URL to insert
Referenced by xmmsc_playlist_insert_args(), and xmmsc_playlist_insert_full().
xmmsc_result_t* xmmsc_playlist_insert_full (xmmsc_connection_t * c, const char * playlist, int pos, const char * url, xmmsv_t * args)
Insert entry at given position in playlist with args.
Parameters
c The connection structure.
playlist The playlist in which to insert the media.
pos A position in the playlist
url The URL to insert
numargs The number of arguments
args array of numargs strings used as arguments
Referenced by xmmsc_playlist_insert_url().
xmmsc_result_t* xmmsc_playlist_insert_id (xmmsc_connection_t * c, const char * playlist, int pos, int id)
Insert a medialib id at given position in playlist.
Parameters
c The connection structure.
playlist The playlist in which to insert the media.
pos A position in the playlist
id A medialib id.
xmmsc_result_t* xmmsc_playlist_insert_url (xmmsc_connection_t * c, const char * playlist, int pos, const char * url)
Insert entry at given position in playlist.
Parameters
c The connection structure.
playlist The playlist in which to insert the media.
pos A position in the playlist
url The URL to insert
xmmsc_result_t* xmmsc_playlist_list (xmmsc_connection_t * c)
List the existing playlists.
xmmsc_result_t* xmmsc_playlist_list_entries (xmmsc_connection_t * c, const char * playlist)
List current playlist.
xmmsc_result_t* xmmsc_playlist_load (xmmsc_connection_t * c, const char * name)
Load a playlist as the current active playlist.
xmmsc_result_t* xmmsc_playlist_move_entry (xmmsc_connection_t * c, const char * playlist, int cur_pos, int new_pos)
Move a playlist entry to a new position (absolute move)
xmmsc_result_t* xmmsc_playlist_radd (xmmsc_connection_t * c, const char * playlist, const char * url)
Adds a directory recursivly to the playlist.
The url should be absolute to the server-side. Note that you will have to include the protocol for the url to. ie: file://mp3/my_mp3s/first.mp3.
Parameters
c The connection structure.
playlist The playlist in which to add the media.
url path.
xmmsc_result_t* xmmsc_playlist_radd_encoded (xmmsc_connection_t * c, const char * playlist, const char * url)
Adds a directory recursivly to the playlist.
The url should be absolute to the server-side and url encoded. Note that you will have to include the protocol for the url to. ie: file://mp3/my_mp3s/first.mp3. You probably want to use xmmsc_playlist_radd unless you want to add a string that comes as a result from the daemon, such as from xmmsc_xform_media_browse
Parameters
c The connection structure.
playlist The playlist in which to add the media.
url Encoded path.
Referenced by xmmsc_playlist_radd().
xmmsc_result_t* xmmsc_playlist_remove (xmmsc_connection_t * c, const char * playlist)
Remove the given playlist.
xmmsc_result_t* xmmsc_playlist_remove_entry (xmmsc_connection_t * c, const char * playlist, int pos)
Remove an entry from the playlist.
Parameters
c The connection structure.
playlist The playlist in which to add the media.
pos The position that should be removed from the playlist.
See Also
xmmsc_playlist_list
xmmsc_result_t* xmmsc_playlist_replace (xmmsc_connection_t * c, const char * playlist, xmmsv_t * coll, xmms_playlist_position_action_t action)
Replaces the current playlist.
xmmsc_result_t* xmmsc_playlist_rinsert (xmmsc_connection_t * c, const char * playlist, int pos, const char * url)
Insert a directory recursivly at a given position in the playlist.
The url should be absolute to the server-side. Note that you will have to include the protocol for the url to. ie: file://mp3/my_mp3s/first.mp3.
Parameters
c The connection structure.
playlist The playlist in which to add the media.
pos A position in the playlist
url path.
xmmsc_result_t* xmmsc_playlist_rinsert_encoded (xmmsc_connection_t * c, const char * playlist, int pos, const char * url)
Insert a directory recursivly at a given position in the playlist.
The url should be absolute to the server-side and url encoded. Note that you will have to include the protocol for the url to. ie: file://mp3/my_mp3s/first.mp3. You probably want to use xmmsc_playlist_radd unless you want to add a string that comes as a result from the daemon, such as from xmmsc_xform_media_browse
Parameters
c The connection structure.
playlist The playlist in which to add the media.
pos A position in the playlist
url Encoded path.
Referenced by xmmsc_playlist_rinsert().
xmmsc_result_t* xmmsc_playlist_set_next (xmmsc_connection_t * c, int pos)
Set next entry in the playlist.
Alter the position pointer.
xmmsc_result_t* xmmsc_playlist_set_next_rel (xmmsc_connection_t * c, int pos)
Same as xmmsc_playlist_set_next but relative to the current postion.
-1 will back one and 1 will move to the next.
xmmsc_result_t* xmmsc_playlist_shuffle (xmmsc_connection_t * c, const char * playlist)
Shuffles the current playlist.
xmmsc_result_t* xmmsc_playlist_sort (xmmsc_connection_t * c, const char * playlist, xmmsv_t * properties)
Sorts the playlist according to the list of properties (xmmsv_t containing a list of strings).