XmmsClient: The type xmmsv_t
The type xmmsv_t
Modules
Collections
All modules related to collection handling.
Bitbuffer
Easier building of lists and dictionaries
Deprecated
Dictionaries
Lists
Utilities
Macros
#define XMMSV_TYPE_INT32 XMMSV_TYPE_INT64
#define xmmsv_get_int xmmsv_get_int32
Typedefs
typedef struct xmmsv_St xmmsv_t
Enumerations
enum xmmsv_type_t {
XMMSV_TYPE_NONE, XMMSV_TYPE_ERROR, XMMSV_TYPE_INT64, XMMSV_TYPE_STRING,
XMMSV_TYPE_COLL, XMMSV_TYPE_BIN, XMMSV_TYPE_LIST, XMMSV_TYPE_DICT,
XMMSV_TYPE_BITBUFFER, XMMSV_TYPE_FLOAT, XMMSV_TYPE_END
}
Functions
xmmsv_t * xmmsv_new_none (void) XMMS_PUBLIC
Allocates a new empty xmmsv_t.
xmmsv_t * xmmsv_new_error (const char *errstr) XMMS_PUBLIC
Allocates a new error xmmsv_t.
xmmsv_t * xmmsv_new_int (int64_t i) XMMS_PUBLIC
Allocates a new integer xmmsv_t.
xmmsv_t * xmmsv_new_float (float i) XMMS_PUBLIC
Allocates a new float xmmsv_t.
xmmsv_t * xmmsv_new_string (const char *s) XMMS_PUBLIC
Allocates a new string xmmsv_t.
xmmsv_t * xmmsv_new_bin (const unsigned char *data, unsigned int len) XMMS_PUBLIC
Allocates a new binary data xmmsv_t.
xmmsv_t * xmmsv_copy (xmmsv_t *val) XMMS_PUBLIC
Return a new value object which is a deep copy of the input value.
xmmsv_t * xmmsv_coll_copy (xmmsv_t *orig_coll) XMMS_PUBLIC XMMS_DEPRECATED
xmmsv_t * xmmsv_ref (xmmsv_t *val) XMMS_PUBLIC
References the xmmsv_t.
void xmmsv_unref (xmmsv_t *val) XMMS_PUBLIC
Decreases the references for the xmmsv_t When the number of references reaches 0 it will be freed.
xmmsv_type_t xmmsv_get_type (const xmmsv_t *val) XMMS_PUBLIC
Get the type of the value.
int xmmsv_is_type (const xmmsv_t *val, xmmsv_type_t t) XMMS_PUBLIC
Check if value is of specified type.
int xmmsv_get_error (const xmmsv_t *val, const char **r) XMMS_PUBLIC
Retrieves an error string describing the server error from the value.
int xmmsv_get_int32 (const xmmsv_t *val, int32_t *r) XMMS_PUBLIC
Retrieves a signed integer from the value.
int xmmsv_get_int64 (const xmmsv_t *val, int64_t *r) XMMS_PUBLIC
Retrieves a signed integer from the value.
int xmmsv_get_float (const xmmsv_t *val, float *r) XMMS_PUBLIC
Retrieves a float from the value.
int xmmsv_get_string (const xmmsv_t *val, const char **r) XMMS_PUBLIC
Retrieves a string from the value.
int xmmsv_get_coll (const xmmsv_t *val, xmmsv_t **coll) XMMS_PUBLIC XMMS_DEPRECATED
Retrieves a collection from the value.
int xmmsv_get_bin (const xmmsv_t *val, const unsigned char **r, unsigned int *rlen) XMMS_PUBLIC
Retrieves binary data from the value.
int xmmsv_is_error (const xmmsv_t *val) XMMS_PUBLIC
Check if the value stores an error.
Detailed Description
Macro Definition Documentation
#define xmmsv_get_int xmmsv_get_int32
Definition at line 87 of file xmmsv_general.h.
Referenced by setup_shm_handle(), setup_udp_handle(), xmmsc_sc_broadcast_emit(), xmmsc_visualization_init_handle(), xmmsv_copy(), and xmmsv_dict_format().
#define XMMSV_TYPE_INT32 XMMSV_TYPE_INT64
Definition at line 52 of file xmmsv_general.h.
Typedef Documentation
typedef struct xmmsv_St xmmsv_t
Definition at line 54 of file xmmsv_general.h.
Enumeration Type Documentation
enum xmmsv_type_t
Enumerator
XMMSV_TYPE_NONE
XMMSV_TYPE_ERROR
XMMSV_TYPE_INT64
XMMSV_TYPE_STRING
XMMSV_TYPE_COLL
XMMSV_TYPE_BIN
XMMSV_TYPE_LIST
XMMSV_TYPE_DICT
XMMSV_TYPE_BITBUFFER
XMMSV_TYPE_FLOAT
XMMSV_TYPE_END
Definition at line 38 of file xmmsv_general.h.
Function Documentation
xmmsv_t* xmmsv_coll_copy (xmmsv_t * orig_coll)
Definition at line 158 of file xmmsv_copy.c.
xmmsv_t* xmmsv_copy (xmmsv_t * val)
Return a new value object which is a deep copy of the input value.
Parameters
val xmmsv_t to copy.
Returns
1 the address to the new copy of the value.
Definition at line 34 of file xmmsv_copy.c.
int xmmsv_get_bin (const xmmsv_t * val, const unsigned char ** r, unsigned int * rlen)
Retrieves binary data from the value.
Parameters
val a xmmsv_t containing a string.
r the return data. This data is owned by the value and will be freed when the value is freed.
rlen the return length of data.
Returns
1 upon success otherwise 0
Definition at line 440 of file xmmsv_general.c.
Referenced by xmmsv_deserialize().
int xmmsv_get_coll (const xmmsv_t * val, xmmsv_t ** c)
Retrieves a collection from the value.
Parameters
val a xmmsv_t containing a collection.
c the return collection. This collection is owned by the value and will be unref'd when the value is freed.
Returns
1 upon success otherwise 0
Definition at line 419 of file xmmsv_general.c.
int xmmsv_get_error (const xmmsv_t * val, const char ** r)
Retrieves an error string describing the server error from the value.
Parameters
val a xmmsv_t containing a integer.
r the return error.
Returns
1 upon success otherwise 0
Definition at line 316 of file xmmsv_general.c.
Referenced by xmmsc_connect(), and xmmsv_copy().
int xmmsv_get_float (const xmmsv_t * val, float * r)
Retrieves a float from the value.
Parameters
val a xmmsv_t containing a float value.
r the return float.
Returns
1 upon success otherwise 0
Definition at line 379 of file xmmsv_general.c.
Referenced by xmmsv_copy(), and xmmsv_dict_format().
int xmmsv_get_int32 (const xmmsv_t * val, int32_t * r)
Retrieves a signed integer from the value.
Parameters
val a xmmsv_t containing an integer.
r the return integer.
Returns
1 upon success otherwise 0
Definition at line 335 of file xmmsv_general.c.
int xmmsv_get_int64 (const xmmsv_t * val, int64_t * r)
Retrieves a signed integer from the value.
Parameters
val a xmmsv_t containing an integer.
r the return integer.
Returns
1 upon success otherwise 0
Definition at line 357 of file xmmsv_general.c.
Referenced by xmmsc_connect().
int xmmsv_get_string (const xmmsv_t * val, const char ** r)
Retrieves a string from the value.
Parameters
val a xmmsv_t containing a string.
r the return string. This string is owned by the value and will be freed when the value is freed.
Returns
1 upon success otherwise 0
Definition at line 399 of file xmmsv_general.c.
Referenced by xmmsv_copy(), xmmsv_decode_url(), xmmsv_dict_format(), and xmmsv_encode_url_full().
xmmsv_type_t xmmsv_get_type (const xmmsv_t * val)
Get the type of the value.
Parameters
val a xmmsv_t to get the type from.
Returns
The data type in the value.
Definition at line 270 of file xmmsv_general.c.
Referenced by xmmsc_sc_call(), xmmsc_visualization_properties_set(), xmmsv_bitbuffer_serialize_value(), xmmsv_build_metadata(), xmmsv_copy(), xmmsv_dict_entry_get_type(), xmmsv_dict_format(), xmmsv_is_type(), and xmmsv_sc_argument_new().
int xmmsv_is_error (const xmmsv_t * val)
Check if the value stores an error.
Parameters
val a xmmsv_t
Returns
1 if error was encountered, 0 otherwise.
Definition at line 302 of file xmmsv_general.c.
Referenced by xmmsc_connect().
int xmmsv_is_type (const xmmsv_t * val, xmmsv_type_t t)
Check if value is of specified type.
Parameters
val xmmsv_t to check.
t xmmsv_type_t to check for.
Returns
1 if value is of specified type, 0 otherwise.
Definition at line 286 of file xmmsv_general.c.
Referenced by xmmsc_sc_namespace_add_method(), xmmsc_sc_namespace_lookup(), xmmsc_sc_namespace_remove(), xmmsv_coll_add_order_operators(), xmmsv_coll_attribute_get_int32(), xmmsv_coll_attribute_get_int64(), xmmsv_coll_attribute_get_string(), xmmsv_coll_attribute_get_value(), xmmsv_coll_attribute_set_int(), xmmsv_coll_attribute_set_string(), xmmsv_coll_attribute_set_value(), xmmsv_coll_attributes_set(), xmmsv_dict_clear(), xmmsv_dict_foreach(), xmmsv_dict_get(), xmmsv_dict_get_size(), xmmsv_dict_remove(), xmmsv_dict_set(), xmmsv_is_error(), xmmsv_list_append(), xmmsv_list_clear(), xmmsv_list_foreach(), xmmsv_list_get(), xmmsv_list_get_size(), xmmsv_list_get_type(), xmmsv_list_has_type(), xmmsv_list_index_of(), xmmsv_list_insert(), xmmsv_list_move(), xmmsv_list_remove(), xmmsv_list_set(), and xmmsv_list_sort().
xmmsv_t* xmmsv_new_bin (const unsigned char * data, unsigned int len)
Allocates a new binary data xmmsv_t.
Parameters
data The data to store in the xmmsv_t.
len The size of the data.
Returns
The new xmmsv_t. Must be unreferenced with xmmsv_unref.
Definition at line 211 of file xmmsv_general.c.
Referenced by xmmsc_bindata_add(), xmmsv_copy(), xmmsv_decode_url(), and xmmsv_serialize().
xmmsv_t* xmmsv_new_error (const char * errstr)
Allocates a new error xmmsv_t.
Parameters
s The error message to store in the xmmsv_t. The string is copied in the value.
Returns
The new xmmsv_t. Must be unreferenced with xmmsv_unref.
Definition at line 133 of file xmmsv_general.c.
Referenced by xmmsc_result_seterror(), xmmsc_result_wait(), xmmsc_sc_interface_entity_method_call(), and xmmsv_copy().
xmmsv_t* xmmsv_new_float (float i)
Allocates a new float xmmsv_t.
Parameters
i The value to store in the xmmsv_t.
Returns
The new xmmsv_t. Must be unreferenced with xmmsv_unref.
Definition at line 169 of file xmmsv_general.c.
Referenced by xmmsv_copy().
xmmsv_t* xmmsv_new_int (int64_t i)
Allocates a new integer xmmsv_t.
Parameters
i The value to store in the xmmsv_t.
Returns
The new xmmsv_t. Must be unreferenced with xmmsv_unref.
Definition at line 151 of file xmmsv_general.c.
Referenced by xmmsc_sc_interface_entity_broadcast_add_id(), and xmmsv_copy().
xmmsv_t* xmmsv_new_none (void)
Allocates a new empty xmmsv_t.
Returns
The new xmmsv_t. Must be unreferenced with xmmsv_unref.
Definition at line 119 of file xmmsv_general.c.
Referenced by xmmsc_sc_interface_entity_method_call(), and xmmsv_copy().
xmmsv_t* xmmsv_new_string (const char * s)
Allocates a new string xmmsv_t.
Parameters
s The value to store in the xmmsv_t. The string is copied in the value.
Returns
The new xmmsv_t. Must be unreferenced with xmmsv_unref.
Definition at line 188 of file xmmsv_general.c.
Referenced by xmmsc_sc_create_root_namespace(), xmmsv_copy(), and xmmsv_make_stringlist().
xmmsv_t* xmmsv_ref (xmmsv_t * val)
References the xmmsv_t.
Parameters
val the value to reference.
Returns
val
Definition at line 237 of file xmmsv_general.c.
Referenced by _xmmsv_new(), xmmsc_c2c_reply(), xmmsc_c2c_send(), xmmsc_coll_query(), xmmsc_coll_query_infos(), xmmsc_coll_save(), xmmsc_playlist_add_idlist(), xmmsc_playlist_replace(), xmmsc_sc_broadcast_subscribe(), xmmsc_sc_call(), xmmsc_sc_interface_entity_broadcast_introspect(), xmmsc_sc_interface_entity_method_introspect(), xmmsc_sc_interface_entity_namespace_introspect(), xmmsc_visualization_properties_set(), xmmsv_c2c_message_format(), xmmsv_coll_add_limit_operator(), xmmsv_coll_add_order_operator(), xmmsv_coll_add_order_operators(), xmmsv_coll_attributes_set(), xmmsv_coll_idlist_set(), xmmsv_coll_operands_set(), xmmsv_coll_ref(), xmmsv_dict_iter_set(), xmmsv_dict_set(), and xmmsv_list_set().
void xmmsv_unref (xmmsv_t * val)
Decreases the references for the xmmsv_t When the number of references reaches 0 it will be freed.
And thus all data you extracted from it will be deallocated.
Definition at line 252 of file xmmsv_general.c.
Referenced by _xmmsv_coll_free(), _xmmsv_dict_free(), _xmmsv_list_free(), xmmsc_coll_query_ids(), xmmsc_playlist_create(), xmmsc_playlist_shuffle(), xmmsc_playlist_sort(), xmmsc_result_run(), xmmsc_result_seterror(), xmmsc_sc_broadcast_subscribe(), xmmsc_sc_call(), xmmsc_sc_create_root_namespace(), xmmsc_sc_interface_entity_broadcast_add_id(), xmmsc_sc_interface_entity_destroy(), xmmsc_sc_interface_entity_namespace_introspect(), xmmsc_sc_introspect_constant(), xmmsc_sc_introspect_docstring(), xmmsc_sc_namespace_destroy(), xmmsc_sc_namespace_get(), xmmsc_send_cmd(), xmmsc_send_cmd_cookie(), xmmsc_send_msg_no_arg(), xmmsc_write_signal_msg(), xmmsv_build_cluster_dict(), xmmsv_build_cluster_list(), xmmsv_build_dict_va(), xmmsv_build_list_va(), xmmsv_build_metadata(), xmmsv_build_organize(), xmmsv_coll_add_order_operator(), xmmsv_coll_add_order_operators(), xmmsv_coll_attributes_set(), xmmsv_coll_default_parse_build(), xmmsv_coll_idlist_set(), xmmsv_coll_operands_set(), xmmsv_coll_unref(), xmmsv_deserialize(), xmmsv_dict_clear(), xmmsv_dict_iter_set(), xmmsv_list_flatten(), xmmsv_list_set(), xmmsv_make_stringlist(), and xmmsv_serialize().