XmmsClient: ResultValueRetrieval
ResultValueRetrieval
Result
Explains how you can retrive values from a xmmsc_result_t.
Functions
xmmsv_t * xmmsc_result_get_value (xmmsc_result_t *res)
Get the value from a result.
Detailed Description
Explains how you can retrive values from a xmmsc_result_t.
Function Documentation
xmmsv_t* xmmsc_result_get_value (xmmsc_result_t * res)
Get the value from a result.
The reference is still owned by the result.
Parameters
res a xmmsc_result_t containing the value.
Returns
A borrowed reference to the value received by the result.
Definition at line 465 of file result.c.
Referenced by setup_shm_handle(), setup_udp_handle(), xmmsc_connect(), and xmmsc_visualization_init_handle().