XmmsClient: Lists
Lists
The type xmmsv_t
Modules
Iteration
Macros
#define xmmsv_list_get_int xmmsv_list_get_int32
#define xmmsv_list_iter_entry_int xmmsv_list_iter_entry_int32
Typedefs
typedef int(* xmmsv_list_compare_func_t)(xmmsv_t **, xmmsv_t **)
Functions
xmmsv_t * xmmsv_new_list (void) XMMS_PUBLIC
Allocates a new list xmmsv_t.
int xmmsv_list_get (xmmsv_t *listv, int pos, xmmsv_t **val) XMMS_PUBLIC
Get the element at the given position in the list xmmsv_t.
int xmmsv_list_set (xmmsv_t *listv, int pos, xmmsv_t *val) XMMS_PUBLIC
Set the element at the given position in the list xmmsv_t.
int xmmsv_list_append (xmmsv_t *listv, xmmsv_t *val) XMMS_PUBLIC
Append an element to the end of the list xmmsv_t.
int xmmsv_list_insert (xmmsv_t *listv, int pos, xmmsv_t *val) XMMS_PUBLIC
Insert an element at the given position in the list xmmsv_t.
int xmmsv_list_remove (xmmsv_t *listv, int pos) XMMS_PUBLIC
Remove the element at the given position from the list xmmsv_t.
int xmmsv_list_move (xmmsv_t *listv, int old_pos, int new_pos) XMMS_PUBLIC
Move the element from position #old to position #new.
int xmmsv_list_clear (xmmsv_t *listv) XMMS_PUBLIC
Empty the list from all its elements.
int xmmsv_list_sort (xmmsv_t *listv, xmmsv_list_compare_func_t comparator) XMMS_PUBLIC
Sort the list using the supplied comparator.
int xmmsv_list_get_size (xmmsv_t *listv) XMMS_PUBLIC
Return the size of the list.
int xmmsv_list_restrict_type (xmmsv_t *listv, xmmsv_type_t type) XMMS_PUBLIC
int xmmsv_list_has_type (xmmsv_t *listv, xmmsv_type_t type) XMMS_PUBLIC
Checks if all elements in the list has the given type.
int xmmsv_list_get_type (xmmsv_t *listv, xmmsv_type_t *type) XMMS_PUBLIC
Gets the current type restriction of a list.
int xmmsv_list_index_of (xmmsv_t *listv, xmmsv_t *val) XMMS_PUBLIC
Get the index of an element in the list.
int xmmsv_list_get_string (xmmsv_t *v, int pos, const char **val) XMMS_PUBLIC
int xmmsv_list_get_int32 (xmmsv_t *v, int pos, int32_t *val) XMMS_PUBLIC
int xmmsv_list_get_int64 (xmmsv_t *v, int pos, int64_t *val) XMMS_PUBLIC
int xmmsv_list_get_float (xmmsv_t *v, int pos, float *val) XMMS_PUBLIC
int xmmsv_list_get_coll (xmmsv_t *v, int pos, xmmsv_t **val) XMMS_PUBLIC XMMS_DEPRECATED
int xmmsv_list_set_string (xmmsv_t *v, int pos, const char *val) XMMS_PUBLIC
int xmmsv_list_set_int (xmmsv_t *v, int pos, int64_t val) XMMS_PUBLIC
int xmmsv_list_set_float (xmmsv_t *v, int pos, float val) XMMS_PUBLIC
int xmmsv_list_set_coll (xmmsv_t *v, int pos, xmmsv_t *val) XMMS_PUBLIC XMMS_DEPRECATED
int xmmsv_list_insert_string (xmmsv_t *v, int pos, const char *val) XMMS_PUBLIC
int xmmsv_list_insert_int (xmmsv_t *v, int pos, int64_t val) XMMS_PUBLIC
int xmmsv_list_insert_float (xmmsv_t *v, int pos, float val) XMMS_PUBLIC
int xmmsv_list_insert_coll (xmmsv_t *v, int pos, xmmsv_t *val) XMMS_PUBLIC XMMS_DEPRECATED
int xmmsv_list_append_string (xmmsv_t *v, const char *val) XMMS_PUBLIC
int xmmsv_list_append_int (xmmsv_t *v, int64_t val) XMMS_PUBLIC
int xmmsv_list_append_float (xmmsv_t *v, float val) XMMS_PUBLIC
int xmmsv_list_append_coll (xmmsv_t *v, xmmsv_t *val) XMMS_PUBLIC XMMS_DEPRECATED
xmmsv_t * xmmsv_list_flatten (xmmsv_t *list, int depth) XMMS_PUBLIC
Flattens a list of lists.
Detailed Description
Macro Definition Documentation
#define xmmsv_list_get_int xmmsv_list_get_int32
Definition at line 117 of file xmmsv_list.h.
Referenced by xmmsv_coll_idlist_get_index_int32(), and xmmsv_coll_idlist_get_index_int64().
#define xmmsv_list_iter_entry_int xmmsv_list_iter_entry_int32
Definition at line 118 of file xmmsv_list.h.
Typedef Documentation
typedef int(* xmmsv_list_compare_func_t)(xmmsv_t **, xmmsv_t **)
Definition at line 33 of file xmmsv_list.h.
Function Documentation
int xmmsv_list_append (xmmsv_t * listv, xmmsv_t * val)
Append an element to the end of the list xmmsv_t.
The list will hold a reference to the element until it's removed.
Parameters
listv A xmmsv_t containing a list.
val The element to append.
Returns
1 upon success otherwise 0
Definition at line 449 of file xmmsv_list.c.
Referenced by xmmsc_sc_interface_entity_broadcast_add_id(), xmmsc_sc_interface_entity_namespace_introspect(), xmmsv_build_list_va(), xmmsv_build_metadata(), xmmsv_coll_add_operand(), xmmsv_list_append_coll(), and xmmsv_make_stringlist().
int xmmsv_list_append_coll (xmmsv_t * v, xmmsv_t * val)
Definition at line 1040 of file xmmsv_list.c.
int xmmsv_list_append_float (xmmsv_t * v, float val)
int xmmsv_list_append_int (xmmsv_t * v, int64_t val)
Referenced by xmmsv_coll_idlist_append(), and xmmsv_coll_set_idlist().
int xmmsv_list_append_string (xmmsv_t * v, const char * val)
Referenced by xmmsc_sc_introspect_docstring().
int xmmsv_list_clear (xmmsv_t * listv)
Empty the list from all its elements.
Parameters
listv A xmmsv_t containing a list.
Returns
1 upon success otherwise 0
Definition at line 465 of file xmmsv_list.c.
Referenced by xmmsv_coll_idlist_clear(), and xmmsv_coll_set_idlist().
xmmsv_t* xmmsv_list_flatten (xmmsv_t * list, int depth)
Flattens a list of lists.
Parameters
list The list to flatten
depth The level of lists to flatten.
Returns
A new flattened list, or NULL on error.
Definition at line 934 of file xmmsv_list.c.
int xmmsv_list_get (xmmsv_t * listv, int pos, xmmsv_t ** val)
Get the element at the given position in the list xmmsv_t.
This function does not increase the refcount of the element, the reference is still owned by the list.
Parameters
listv A xmmsv_t containing a list.
pos The position in the list. If negative, start counting from the end (-1 is the last element, etc).
val Pointer set to a borrowed reference to the element at the given position in the list.
Returns
1 upon success otherwise 0
Definition at line 327 of file xmmsv_list.c.
Referenced by xmmsv_list_get_coll().
int xmmsv_list_get_coll (xmmsv_t * v, int pos, xmmsv_t ** val)
Definition at line 965 of file xmmsv_list.c.
int xmmsv_list_get_float (xmmsv_t * v, int pos, float * val)
int xmmsv_list_get_int32 (xmmsv_t * v, int pos, int32_t * val)
int xmmsv_list_get_int64 (xmmsv_t * v, int pos, int64_t * val)
int xmmsv_list_get_size (xmmsv_t * listv)
Return the size of the list.
Parameters
listv The xmmsv_t containing the list.
Returns
The size of the list, or -1 if listv is invalid.
Definition at line 529 of file xmmsv_list.c.
Referenced by xmmsc_sc_broadcast_emit(), xmmsc_sc_broadcast_subscribe(), xmmsc_sc_call(), xmmsc_sc_locate_interface_entity(), and xmmsv_coll_idlist_get_size().
int xmmsv_list_get_string (xmmsv_t * v, int pos, const char ** val)
int xmmsv_list_get_type (xmmsv_t * listv, xmmsv_type_t * type)
Gets the current type restriction of a list.
Parameters
listv The list to Check
Returns
the xmmsv_type_t of the restricted type, or XMMSV_TYPE_NONE if no restriction.
Definition at line 558 of file xmmsv_list.c.
int xmmsv_list_has_type (xmmsv_t * listv, xmmsv_type_t type)
Checks if all elements in the list has the given type.
Parameters
listv The list to check
type The type to check for
Returns
non-zero if all elements in the list has the type, 0 otherwise
Definition at line 578 of file xmmsv_list.c.
Referenced by xmmsv_list_restrict_type().
int xmmsv_list_index_of (xmmsv_t * listv, xmmsv_t * val)
Get the index of an element in the list.
This function compares the pointers and not the actual values contained in the elements.
Parameters
listv The xmmsv_t containing the list
val The element to find
Returns
The index of the element if found, -1 otherwise
Definition at line 612 of file xmmsv_list.c.
int xmmsv_list_insert (xmmsv_t * listv, int pos, xmmsv_t * val)
Insert an element at the given position in the list xmmsv_t.
The list will hold a reference to the element until it's removed.
Parameters
listv A xmmsv_t containing a list.
pos The position in the list. If negative, start counting from the end (-1 is the last element, etc).
val The element to insert.
Returns
1 upon success otherwise 0
Definition at line 391 of file xmmsv_list.c.
Referenced by xmmsv_list_insert_coll().
int xmmsv_list_insert_coll (xmmsv_t * v, int pos, xmmsv_t * val)
Definition at line 1015 of file xmmsv_list.c.
int xmmsv_list_insert_float (xmmsv_t * v, int pos, float val)
int xmmsv_list_insert_int (xmmsv_t * v, int pos, int64_t val)
Referenced by xmmsv_coll_idlist_insert().
int xmmsv_list_insert_string (xmmsv_t * v, int pos, const char * val)
int xmmsv_list_move (xmmsv_t * listv, int old_pos, int new_pos)
Move the element from position #old to position #new.
xmmsv_list_iter_t's remain pointing at their element (which might or might not be at a different position).
Parameters
listv A xmmsv_t containing a list
old The original position in the list. If negative, start counting from the end (-1 is the last element, etc.)
new The new position in the list. If negative start counting from the end (-1 is the last element, etc.) For the sake of counting the element to be moved is still at its old position.
Returns
1 upon success otherwise 0
Definition at line 432 of file xmmsv_list.c.
Referenced by xmmsv_coll_idlist_move().
int xmmsv_list_remove (xmmsv_t * listv, int pos)
Remove the element at the given position from the list xmmsv_t.
Parameters
listv A xmmsv_t containing a list.
pos The position in the list. If negative, start counting from the end (-1 is the last element, etc).
Returns
1 upon success otherwise 0
Definition at line 409 of file xmmsv_list.c.
Referenced by xmmsv_coll_idlist_remove().
int xmmsv_list_restrict_type (xmmsv_t * listv, xmmsv_type_t type)
Definition at line 539 of file xmmsv_list.c.
Referenced by xmmsc_playlist_sort(), xmmsc_sc_broadcast_emit(), xmmsc_sc_broadcast_subscribe(), xmmsc_sc_call(), xmmsc_sc_introspect_constant(), xmmsc_sc_introspect_docstring(), xmmsc_sc_namespace_lookup(), xmmsc_sc_namespace_remove(), xmmsv_coll_idlist_set(), and xmmsv_coll_operands_set().
int xmmsv_list_set (xmmsv_t * listv, int pos, xmmsv_t * val)
Set the element at the given position in the list xmmsv_t.
Parameters
listv A xmmsv_t containing a list.
pos The position in the list. If negative, start counting from the end (-1 is the last element, etc).
val The element to put at the given position in the list.
Returns
1 upon success otherwise 0
Definition at line 358 of file xmmsv_list.c.
Referenced by xmmsv_list_iter_set(), and xmmsv_list_set_coll().
int xmmsv_list_set_coll (xmmsv_t * v, int pos, xmmsv_t * val)
Definition at line 990 of file xmmsv_list.c.
int xmmsv_list_set_float (xmmsv_t * v, int pos, float val)
int xmmsv_list_set_int (xmmsv_t * v, int pos, int64_t val)
Referenced by xmmsv_coll_idlist_set_index().
int xmmsv_list_set_string (xmmsv_t * v, int pos, const char * val)
int xmmsv_list_sort (xmmsv_t * listv, xmmsv_list_compare_func_t comparator)
Sort the list using the supplied comparator.
Parameters
listv A xmmsv_t containing a list.
Returns
1 upon success otherwise 0
Definition at line 482 of file xmmsv_list.c.
xmmsv_t* xmmsv_new_list (void)
Allocates a new list xmmsv_t.
Returns
The new xmmsv_t. Must be unreferenced with xmmsv_unref.
Definition at line 302 of file xmmsv_list.c.
Referenced by xmmsc_coll_query_infos(), xmmsc_sc_call(), xmmsc_sc_interface_entity_namespace_introspect(), xmmsc_sc_introspect_docstring(), xmmsc_send_msg_no_arg(), xmmsv_build_list_va(), xmmsv_build_metadata(), xmmsv_list_flatten(), and xmmsv_make_stringlist().