XmmsClient: Iteration
Iteration
Lists
Typedefs
typedef void(* xmmsv_list_foreach_func)(xmmsv_t *value, void *user_data)
typedef struct xmmsv_list_iter_St xmmsv_list_iter_t
Functions
int xmmsv_list_foreach (xmmsv_t *listv, xmmsv_list_foreach_func func, void *user_data) XMMS_PUBLIC
Apply a function to each element in the list, in sequential order.
int xmmsv_get_list_iter (const xmmsv_t *val, xmmsv_list_iter_t **it) XMMS_PUBLIC
Retrieves a list iterator from a list xmmsv_t.
void xmmsv_list_iter_explicit_destroy (xmmsv_list_iter_t *it) XMMS_PUBLIC
Explicitly free list iterator.
int xmmsv_list_iter_entry (xmmsv_list_iter_t *it, xmmsv_t **val) XMMS_PUBLIC
Get the element currently pointed at by the iterator.
int xmmsv_list_iter_valid (xmmsv_list_iter_t *it) XMMS_PUBLIC
Check whether the iterator is valid and points to a valid element.
void xmmsv_list_iter_first (xmmsv_list_iter_t *it) XMMS_PUBLIC
Rewind the iterator to the start of the list.
void xmmsv_list_iter_last (xmmsv_list_iter_t *it) XMMS_PUBLIC
Move the iterator to end of the list.
void xmmsv_list_iter_next (xmmsv_list_iter_t *it) XMMS_PUBLIC
Advance the iterator to the next element in the list.
void xmmsv_list_iter_prev (xmmsv_list_iter_t *it) XMMS_PUBLIC
Move the iterator to the previous element in the list.
int xmmsv_list_iter_seek (xmmsv_list_iter_t *it, int pos) XMMS_PUBLIC
Move the iterator to the n-th element in the list.
int xmmsv_list_iter_tell (const xmmsv_list_iter_t *it) XMMS_PUBLIC
Tell the position of the iterator.
xmmsv_t * xmmsv_list_iter_get_parent (const xmmsv_list_iter_t *it) XMMS_PUBLIC
Return the parent xmmsv_t of an iterator.
int xmmsv_list_iter_set (xmmsv_list_iter_t *it, xmmsv_t *val) XMMS_PUBLIC
Replace an element in the list at the position pointed at by the iterator.
int xmmsv_list_iter_insert (xmmsv_list_iter_t *it, xmmsv_t *val) XMMS_PUBLIC
Insert an element in the list at the position pointed at by the iterator.
int xmmsv_list_iter_remove (xmmsv_list_iter_t *it) XMMS_PUBLIC
Remove the element in the list at the position pointed at by the iterator.
int xmmsv_list_iter_entry_string (xmmsv_list_iter_t *it, const char **val) XMMS_PUBLIC
int xmmsv_list_iter_entry_int32 (xmmsv_list_iter_t *it, int32_t *val) XMMS_PUBLIC
int xmmsv_list_iter_entry_int64 (xmmsv_list_iter_t *it, int64_t *val) XMMS_PUBLIC
int xmmsv_list_iter_entry_float (xmmsv_list_iter_t *it, float *val) XMMS_PUBLIC
int xmmsv_list_iter_entry_coll (xmmsv_list_iter_t *it, xmmsv_t **val) XMMS_PUBLIC XMMS_DEPRECATED
int xmmsv_list_iter_insert_string (xmmsv_list_iter_t *it, const char *val) XMMS_PUBLIC
int xmmsv_list_iter_insert_int (xmmsv_list_iter_t *it, int64_t val) XMMS_PUBLIC
int xmmsv_list_iter_insert_float (xmmsv_list_iter_t *it, float val) XMMS_PUBLIC
int xmmsv_list_iter_insert_coll (xmmsv_list_iter_t *it, xmmsv_t *val) XMMS_PUBLIC XMMS_DEPRECATED
Detailed Description
Typedef Documentation
typedef void(* xmmsv_list_foreach_func)(xmmsv_t *value, void *user_data)
Definition at line 79 of file xmmsv_list.h.
typedef struct xmmsv_list_iter_St xmmsv_list_iter_t
Definition at line 82 of file xmmsv_list.h.
Function Documentation
int xmmsv_get_list_iter (const xmmsv_t * val, xmmsv_list_iter_t ** it)
Retrieves a list iterator from a list xmmsv_t.
Parameters
val a xmmsv_t containing a list.
it An xmmsv_list_iter_t that can be used to access the list data. The iterator will be freed when the value is freed.
Returns
1 upon success otherwise 0
Definition at line 667 of file xmmsv_list.c.
Referenced by xmmsc_sc_broadcast_emit(), xmmsc_sc_namespace_resolve_path(), xmmsv_coll_add_operand(), xmmsv_coll_add_order_operators(), xmmsv_coll_remove_operand(), xmmsv_list_foreach(), xmmsv_list_has_type(), and xmmsv_list_index_of().
int xmmsv_list_foreach (xmmsv_t * listv, xmmsv_list_foreach_func func, void * user_data)
Apply a function to each element in the list, in sequential order.
Parameters
listv A xmmsv_t containing a list.
function The function to apply to each element.
user_data User data passed to the foreach function.
Returns
1 upon success otherwise 0
Definition at line 502 of file xmmsv_list.c.
int xmmsv_list_iter_entry (xmmsv_list_iter_t * it, xmmsv_t ** val)
Get the element currently pointed at by the iterator.
This function does not increase the refcount of the element, the reference is still owned by the list. If iterator does not point on a valid element xmmsv_list_iter_entry returns 0 and leaves val untouched.
Parameters
it A xmmsv_list_iter_t.
val Pointer set to a borrowed reference to the element pointed at by the iterator.
Returns
1 upon success otherwise 0
Definition at line 723 of file xmmsv_list.c.
Referenced by xmmsc_sc_broadcast_emit(), xmmsc_sc_namespace_resolve_path(), xmmsv_coll_add_order_operators(), xmmsv_list_foreach(), xmmsv_list_has_type(), xmmsv_list_index_of(), and xmmsv_list_iter_entry_coll().
int xmmsv_list_iter_entry_coll (xmmsv_list_iter_t * it, xmmsv_t ** val)
Definition at line 1063 of file xmmsv_list.c.
int xmmsv_list_iter_entry_float (xmmsv_list_iter_t * it, float * val)
int xmmsv_list_iter_entry_int32 (xmmsv_list_iter_t * it, int32_t * val)
int xmmsv_list_iter_entry_int64 (xmmsv_list_iter_t * it, int64_t * val)
int xmmsv_list_iter_entry_string (xmmsv_list_iter_t * it, const char ** val)
void xmmsv_list_iter_explicit_destroy (xmmsv_list_iter_t * it)
Explicitly free list iterator.
Immediately frees any resources used by this iterator. The iterator is freed automatically when the list is freed, but this function is useful when the list can be long lived.
Parameters
it iterator to free
Definition at line 706 of file xmmsv_list.c.
Referenced by xmmsv_coll_add_operand(), xmmsv_coll_remove_operand(), and xmmsv_list_index_of().
void xmmsv_list_iter_first (xmmsv_list_iter_t * it)
Rewind the iterator to the start of the list.
Parameters
it A xmmsv_list_iter_t.
Definition at line 751 of file xmmsv_list.c.
xmmsv_t* xmmsv_list_iter_get_parent (const xmmsv_list_iter_t * it)
Return the parent xmmsv_t of an iterator.
Parameters
it A xmmsv_list_iter_t.
Returns
The parent xmmsv_t of the iterator, or NULL if invalid.
Definition at line 848 of file xmmsv_list.c.
int xmmsv_list_iter_insert (xmmsv_list_iter_t * it, xmmsv_t * val)
Insert an element in the list at the position pointed at by the iterator.
Parameters
it A xmmsv_list_iter_t.
val The element to insert.
Returns
1 upon success otherwise 0
Definition at line 881 of file xmmsv_list.c.
Referenced by xmmsv_list_iter_insert_coll().
int xmmsv_list_iter_insert_coll (xmmsv_list_iter_t * it, xmmsv_t * val)
Definition at line 1088 of file xmmsv_list.c.
int xmmsv_list_iter_insert_float (xmmsv_list_iter_t * it, float val)
int xmmsv_list_iter_insert_int (xmmsv_list_iter_t * it, int64_t val)
int xmmsv_list_iter_insert_string (xmmsv_list_iter_t * it, const char * val)
void xmmsv_list_iter_last (xmmsv_list_iter_t * it)
Move the iterator to end of the list.
Parameters
listv A xmmsv_list_iter_t.
Definition at line 764 of file xmmsv_list.c.
Referenced by xmmsv_coll_add_order_operators().
void xmmsv_list_iter_next (xmmsv_list_iter_t * it)
Advance the iterator to the next element in the list.
Parameters
it A xmmsv_list_iter_t.
Definition at line 781 of file xmmsv_list.c.
Referenced by xmmsc_sc_broadcast_emit(), xmmsc_sc_namespace_resolve_path(), xmmsv_list_foreach(), xmmsv_list_has_type(), and xmmsv_list_index_of().
void xmmsv_list_iter_prev (xmmsv_list_iter_t * it)
Move the iterator to the previous element in the list.
Parameters
listv A xmmsv_list_iter_t.
Definition at line 796 of file xmmsv_list.c.
Referenced by xmmsv_coll_add_order_operators().
int xmmsv_list_iter_remove (xmmsv_list_iter_t * it)
Remove the element in the list at the position pointed at by the iterator.
Parameters
it A xmmsv_list_iter_t.
Returns
1 upon success otherwise 0
Definition at line 897 of file xmmsv_list.c.
Referenced by xmmsv_coll_remove_operand().
int xmmsv_list_iter_seek (xmmsv_list_iter_t * it, int pos)
Move the iterator to the n-th element in the list.
Parameters
it A xmmsv_list_iter_t.
pos The position in the list. If negative, start counting from the end (-1 is the last element, etc).
Returns
1 upon success otherwise 0
Definition at line 815 of file xmmsv_list.c.
int xmmsv_list_iter_set (xmmsv_list_iter_t * it, xmmsv_t * val)
Replace an element in the list at the position pointed at by the iterator.
Parameters
it A xmmsv_list_iter_t.
val The element to insert.
Returns
1 upon success otherwise 0
Definition at line 864 of file xmmsv_list.c.
int xmmsv_list_iter_tell (const xmmsv_list_iter_t * it)
Tell the position of the iterator.
Parameters
it A xmmsv_list_iter_t.
Returns
The position of the iterator, or -1 if invalid.
Definition at line 834 of file xmmsv_list.c.
int xmmsv_list_iter_valid (xmmsv_list_iter_t * it)
Check whether the iterator is valid and points to a valid element.
Parameters
it A xmmsv_list_iter_t.
Returns
1 if the iterator is valid, 0 otherwise
Definition at line 740 of file xmmsv_list.c.
Referenced by xmmsc_sc_broadcast_emit(), xmmsc_sc_namespace_resolve_path(), and xmmsv_list_iter_entry().