XmmsClient: clients/lib/xmmsclient/ipc.c File Reference
ipc.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <xmmsclient/xmmsclient.h>
#include <xmmsc/xmmsc_ipc_transport.h>
#include <xmmsc/xmmsc_ipc_msg.h>
#include <xmmsclientpriv/xmmsclient.h>
#include <xmmsclientpriv/xmmsclient_ipc.h>
#include <xmmsclientpriv/xmmsclient_util.h>
#include <xmmsclientpriv/xmmsclient_queue.h>
#include <xmmsc/xmmsc_idnumbers.h>
#include <xmmsc/xmmsc_util.h>
#include <xmmsc/xmmsc_stdint.h>
#include <xmmsc/xmmsc_sockets.h>
Functions
int xmmsc_ipc_io_in_callback (xmmsc_ipc_t *ipc)
int xmmsc_ipc_io_out (xmmsc_ipc_t *ipc)
int xmmsc_ipc_io_out_callback (xmmsc_ipc_t *ipc)
xmms_socket_t xmmsc_ipc_fd_get (xmmsc_ipc_t *ipc)
const char * xmmsc_ipc_error_get (xmmsc_ipc_t *ipc)
void xmmsc_ipc_disconnect (xmmsc_ipc_t *ipc)
bool xmmsc_ipc_disconnected (xmmsc_ipc_t *ipc)
xmmsc_ipc_t * xmmsc_ipc_init (void)
void xmmsc_ipc_disconnect_set (xmmsc_ipc_t *ipc, void(*disconnect_callback)(void *), void *userdata, xmmsc_user_data_free_func_t free_func)
void xmmsc_ipc_need_out_callback_set (xmmsc_ipc_t *ipc, void(*callback)(int, void *), void *userdata, xmmsc_user_data_free_func_t free_func)
void xmmsc_ipc_lock_set (xmmsc_ipc_t *ipc, void *lock, void(*lockfunc)(void *), void(*unlockfunc)(void *))
void xmmsc_ipc_result_register (xmmsc_ipc_t *ipc, xmmsc_result_t *res)
xmmsc_result_t * xmmsc_ipc_result_lookup (xmmsc_ipc_t *ipc, uint32_t cookie)
void xmmsc_ipc_result_unregister (xmmsc_ipc_t *ipc, xmmsc_result_t *res)
void xmmsc_ipc_error_set (xmmsc_ipc_t *ipc, char *error)
void xmmsc_ipc_wait_for_event (xmmsc_ipc_t *ipc, unsigned int timeout)
bool xmmsc_ipc_msg_write (xmmsc_ipc_t *ipc, xmms_ipc_msg_t *msg, uint32_t cookie)
void xmmsc_ipc_destroy (xmmsc_ipc_t *ipc)
bool xmmsc_ipc_connect (xmmsc_ipc_t *ipc, char *path)
Function Documentation
bool xmmsc_ipc_connect (xmmsc_ipc_t * ipc, char * path)
Definition at line 368 of file ipc.c.
Referenced by xmmsc_connect().
void xmmsc_ipc_destroy (xmmsc_ipc_t * ipc)
Definition at line 325 of file ipc.c.
Referenced by xmmsc_connect().
void xmmsc_ipc_disconnect (xmmsc_ipc_t * ipc)
Definition at line 147 of file ipc.c.
Referenced by xmmsc_io_disconnect(), xmmsc_ipc_io_in_callback(), and xmmsc_ipc_io_out_callback().
void xmmsc_ipc_disconnect_set (xmmsc_ipc_t * ipc, void(*)(void *) disconnect_callback, void * userdata, xmmsc_user_data_free_func_t free_func)
Definition at line 180 of file ipc.c.
Referenced by xmmsc_disconnect_callback_set_full().
bool xmmsc_ipc_disconnected (xmmsc_ipc_t * ipc)
Definition at line 161 of file ipc.c.
Referenced by xmmsc_io_in_handle().
const char* xmmsc_ipc_error_get (xmmsc_ipc_t * ipc)
Definition at line 140 of file ipc.c.
Referenced by xmmsc_result_wait().
void xmmsc_ipc_error_set (xmmsc_ipc_t * ipc, char * error)
Definition at line 264 of file ipc.c.
Referenced by xmmsc_ipc_disconnect().
xmms_socket_t xmmsc_ipc_fd_get (xmmsc_ipc_t * ipc)
Definition at line 132 of file ipc.c.
Referenced by xmmsc_io_fd_get().
xmmsc_ipc_t* xmmsc_ipc_init (void)
Definition at line 168 of file ipc.c.
Referenced by xmmsc_connect().
int xmmsc_ipc_io_in_callback (xmmsc_ipc_t * ipc)
Definition at line 62 of file ipc.c.
Referenced by xmmsc_io_in_handle(), and xmmsc_ipc_wait_for_event().
int xmmsc_ipc_io_out (xmmsc_ipc_t * ipc)
Definition at line 95 of file ipc.c.
Referenced by xmmsc_io_out_handle(), xmmsc_io_want_out(), xmmsc_ipc_io_out_callback(), and xmmsc_ipc_wait_for_event().
int xmmsc_ipc_io_out_callback (xmmsc_ipc_t * ipc)
Definition at line 103 of file ipc.c.
Referenced by xmmsc_io_out_handle(), and xmmsc_ipc_wait_for_event().
void xmmsc_ipc_lock_set (xmmsc_ipc_t * ipc, void * lock, void(*)(void *) lockfunc, void(*)(void *) unlockfunc)
Definition at line 198 of file ipc.c.
Referenced by xmmsc_lock_set().
bool xmmsc_ipc_msg_write (xmmsc_ipc_t * ipc, xmms_ipc_msg_t * msg, uint32_t cookie)
Definition at line 309 of file ipc.c.
void xmmsc_ipc_need_out_callback_set (xmmsc_ipc_t * ipc, void(*)(int, void *) callback, void * userdata, xmmsc_user_data_free_func_t free_func)
Definition at line 189 of file ipc.c.
Referenced by xmmsc_io_need_out_callback_set_full().
xmmsc_result_t* xmmsc_ipc_result_lookup (xmmsc_ipc_t * ipc, uint32_t cookie)
Definition at line 217 of file ipc.c.
void xmmsc_ipc_result_register (xmmsc_ipc_t * ipc, xmmsc_result_t * res)
Definition at line 206 of file ipc.c.
Referenced by xmmsc_result_new().
void xmmsc_ipc_result_unregister (xmmsc_ipc_t * ipc, xmmsc_result_t * res)
Definition at line 241 of file ipc.c.
void xmmsc_ipc_wait_for_event (xmmsc_ipc_t * ipc, unsigned int timeout)
Definition at line 271 of file ipc.c.
Referenced by xmmsc_result_wait().