XmmsClient: clients/lib/xmmsclient/medialib.c File Reference
medialib.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <xmmsclient/xmmsclient.h>
#include <xmmsclientpriv/xmmsclient.h>
#include <xmmsclientpriv/xmmsclient_ipc.h>
#include <xmmsc/xmmsc_idnumbers.h>
#include <xmmsc/xmmsc_stringport.h>
Macros
#define GOODCHAR(a)
Functions
xmmsc_result_t * xmmsc_medialib_get_id (xmmsc_connection_t *conn, const char *url)
Search for a entry (URL) in the medialib db and return its ID number.
xmmsc_result_t * xmmsc_medialib_get_id_encoded (xmmsc_connection_t *conn, const char *url)
Search for a entry (URL) in the medialib db and return its ID number.
xmmsc_result_t * xmmsc_medialib_move_entry (xmmsc_connection_t *conn, int entry, const char *url)
Change the url property of an entry in the media library.
xmmsc_result_t * xmmsc_medialib_remove_entry (xmmsc_connection_t *conn, int entry)
Remove a entry from the medialib.
xmmsc_result_t * xmmsc_medialib_add_entry (xmmsc_connection_t *conn, const char *url)
Add a URL to the medialib.
xmmsc_result_t * xmmsc_medialib_add_entry_args (xmmsc_connection_t *conn, const char *url, int numargs, const char **args)
Add a URL with arguments to the medialib.
xmmsc_result_t * xmmsc_medialib_add_entry_full (xmmsc_connection_t *conn, const char *url, xmmsv_t *args)
Add a URL with arguments to the medialib.
xmmsc_result_t * xmmsc_medialib_add_entry_encoded (xmmsc_connection_t *conn, const char *url)
Add a URL to the medialib.
xmmsc_result_t * xmmsc_medialib_import_path (xmmsc_connection_t *conn, const char *path)
Import a all files recursivly from the directory passed as argument.
xmmsc_result_t * xmmsc_medialib_import_path_encoded (xmmsc_connection_t *conn, const char *path)
Import a all files recursivly from the directory passed as argument which must already be url encoded.
xmmsc_result_t * xmmsc_medialib_path_import (xmmsc_connection_t *conn, const char *path)
Import a all files recursivly from the directory passed as argument.
xmmsc_result_t * xmmsc_medialib_path_import_encoded (xmmsc_connection_t *conn, const char *path)
Import a all files recursivly from the directory passed as argument which must already be url encoded.
xmmsc_result_t * xmmsc_medialib_rehash (xmmsc_connection_t *conn, int id)
Rehash the medialib, this will check data in the medialib still is the same as the data in files.
xmmsc_result_t * xmmsc_medialib_get_info (xmmsc_connection_t *c, int id)
Retrieve information about a entry from the medialib.
xmmsc_result_t * xmmsc_broadcast_medialib_entry_added (xmmsc_connection_t *c)
Request the medialib_entry_added broadcast.
xmmsc_result_t * xmmsc_broadcast_medialib_entry_changed (xmmsc_connection_t *c)
Request the medialib_entry_updated broadcast.
xmmsc_result_t * xmmsc_broadcast_medialib_entry_updated (xmmsc_connection_t *c)
Request the medialib_entry_updated broadcast.
xmmsc_result_t * xmmsc_broadcast_medialib_entry_removed (xmmsc_connection_t *c)
Request the medialib_entry_removed broadcast.
xmmsc_result_t * xmmsc_medialib_entry_property_set_int (xmmsc_connection_t *c, int id, const char *key, int32_t value)
Associate a int value with a medialib entry.
xmmsc_result_t * xmmsc_medialib_entry_property_set_int_with_source (xmmsc_connection_t *c, int id, const char *source, const char *key, int32_t value)
Set a custom int field in the medialib associated with a entry, the same as xmmsc_medialib_entry_property_set_int but with specifing your own source.
xmmsc_result_t * xmmsc_medialib_entry_property_set_str (xmmsc_connection_t *c, int id, const char *key, const char *value)
Associate a value with a medialib entry.
xmmsc_result_t * xmmsc_medialib_entry_property_set_str_with_source (xmmsc_connection_t *c, int id, const char *source, const char *key, const char *value)
Set a custom field in the medialib associated with a entry, the same as xmmsc_medialib_entry_property_set_str but with specifing your own source.
xmmsc_result_t * xmmsc_medialib_entry_property_remove (xmmsc_connection_t *c, int id, const char *key)
Remove a custom field in the medialib associated with an entry.
xmmsc_result_t * xmmsc_medialib_entry_property_remove_with_source (xmmsc_connection_t *c, int id, const char *source, const char *key)
Remove a custom field in the medialib associated with an entry.
int _xmmsc_medialib_verify_url (const char *url)
char * _xmmsc_medialib_encode_url_old (const char *url, int narg, const char **args)
char * xmmsc_medialib_encode_url_full (const char *url, xmmsv_t *args)
Encodes an url with arguments stored in dict args.
char * xmmsc_medialib_encode_url (const char *url)
Encodes an url.
Macro Definition Documentation
#define GOODCHAR (a)
Value:
((((a) >= 'a') && ((a) <= 'z')) || \
                     (((a) >= 'A') && ((a) <= 'Z')) || \
                     (((a) >= '0') && ((a) <= '9')) || \
                     ((a) == ':') || \
                     ((a) == '/') || \
                     ((a) == '-') || \
                     ((a) == '.') || \
                     ((a) == '_'))
Definition at line 495 of file medialib.c.
Referenced by _xmmsc_medialib_encode_url_old(), and _xmmsc_medialib_verify_url().
Function Documentation
char* _xmmsc_medialib_encode_url_old (const char * url, int narg, const char ** args)
Definition at line 518 of file medialib.c.
Referenced by xmmsc_medialib_add_entry_args(), xmmsc_playlist_add_args(), and xmmsc_playlist_insert_args().
int _xmmsc_medialib_verify_url (const char * url)
Definition at line 506 of file medialib.c.
Referenced by xmmsc_medialib_add_entry_encoded(), xmmsc_medialib_import_path_encoded(), xmmsc_playlist_add_encoded(), xmmsc_playlist_insert_encoded(), xmmsc_playlist_radd_encoded(), xmmsc_playlist_rinsert_encoded(), and xmmsc_xform_media_browse_encoded().
char* xmmsc_medialib_encode_url (const char * url)
Encodes an url.
The encoded url is allocated using malloc and has to be freed by the user.
Parameters
url The url to encode.
Returns
The encoded url
Definition at line 585 of file medialib.c.
char* xmmsc_medialib_encode_url_full (const char * url, xmmsv_t * args)
Encodes an url with arguments stored in dict args.
The encoded url is allocated using malloc and has to be freed by the user.
Parameters
url The url to encode.
args The dict with arguments, or NULL.
Returns
The encoded url
Definition at line 571 of file medialib.c.