XmmsClient: clients/lib/xmmsclient/visualization/udp.c File Reference
udp.c File Reference
#include <xmmsclientpriv/visualization/common.h>
Functions
xmmsc_result_t * setup_udp_prepare (xmmsc_connection_t *c, int32_t vv)
bool setup_udp_handle (xmmsc_result_t *res)
void cleanup_udp (xmmsc_vis_udp_t *t)
int read_do_udp (xmmsc_vis_udp_t *t, xmmsc_visualization_t *v, short *buffer, int drawtime, unsigned int blocking)
Function Documentation
void cleanup_udp (xmmsc_vis_udp_t * t)
Definition at line 163 of file udp.c.
Referenced by xmmsc_visualization_shutdown().
int read_do_udp (xmmsc_vis_udp_t * t, xmmsc_visualization_t * v, short * buffer, int drawtime, unsigned int blocking)
Definition at line 185 of file udp.c.
bool setup_udp_handle (xmmsc_result_t * res)
Definition at line 136 of file udp.c.
Referenced by xmmsc_visualization_start_handle().
xmmsc_result_t* setup_udp_prepare (xmmsc_connection_t * c, int32_t vv)
Definition at line 116 of file udp.c.
Referenced by xmmsc_visualization_start().