XmmsClient: lib/xmmstypes/xlist.c File Reference
xlist.c File Reference
#include <assert.h>
#include <xmmscpriv/xmms_list.h>
#include <stdlib.h>
Macros
#define _x_list_alloc x_list_alloc
#define _x_list_free_1 x_list_free_1
Functions
x_list_t * x_list_alloc (void)
void x_list_free (x_list_t *list)
void x_list_free_1 (x_list_t *list)
x_list_t * x_list_append (x_list_t *list, void *data)
x_list_t * x_list_prepend (x_list_t *list, void *data)
x_list_t * x_list_insert (x_list_t *list, void *data, int position)
x_list_t * x_list_insert_before (x_list_t *list, x_list_t *sibling, void *data)
x_list_t * x_list_concat (x_list_t *list1, x_list_t *list2)
x_list_t * x_list_remove (x_list_t *list, const void *data)
x_list_t * x_list_remove_all (x_list_t *list, const void *data)
x_list_t * x_list_remove_link (x_list_t *list, x_list_t *link)
x_list_t * x_list_delete_link (x_list_t *list, x_list_t *link)
x_list_t * x_list_copy (x_list_t *list)
x_list_t * x_list_reverse (x_list_t *list)
x_list_t * x_list_nth (x_list_t *list, unsigned int n)
x_list_t * x_list_nth_prev (x_list_t *list, unsigned int n)
void * x_list_nth_data (x_list_t *list, unsigned int n)
x_list_t * x_list_find (x_list_t *list, const void *data)
x_list_t * x_list_find_custom (x_list_t *list, const void *data, XCompareFunc func)
int x_list_position (x_list_t *list, x_list_t *link)
int x_list_index (x_list_t *list, const void *data)
x_list_t * x_list_last (x_list_t *list)
x_list_t * x_list_first (x_list_t *list)
unsigned int x_list_length (x_list_t *list)
void x_list_foreach (x_list_t *list, XFunc func, void *user_data)
x_list_t * x_list_insert_sorted (x_list_t *list, void *data, XCompareFunc func)
Macro Definition Documentation
#define _x_list_alloc x_list_alloc
Definition at line 33 of file xlist.c.
Referenced by x_list_append(), x_list_copy(), x_list_insert(), x_list_insert_sorted(), and x_list_prepend().
#define _x_list_free_1 x_list_free_1
Definition at line 56 of file xlist.c.
Referenced by x_list_delete_link(), x_list_remove(), and x_list_remove_all().
Function Documentation
x_list_t* x_list_alloc (void)
Definition at line 35 of file xlist.c.
Referenced by x_list_insert_before().
x_list_t* x_list_append (x_list_t * list, void * data)
Definition at line 64 of file xlist.c.
Referenced by x_list_insert(), x_queue_push_tail(), and xmmsc_sc_namespace_add_child().
x_list_t* x_list_concat (x_list_t * list1, x_list_t * list2)
Definition at line 179 of file xlist.c.
x_list_t* x_list_copy (x_list_t * list)
Definition at line 284 of file xlist.c.
x_list_t* x_list_delete_link (x_list_t * list, x_list_t * link)
Definition at line 275 of file xlist.c.
Referenced by xmmsc_ipc_result_unregister(), and xmmsc_sc_namespace_remove().
x_list_t* x_list_find (x_list_t * list, const void * data)
Definition at line 351 of file xlist.c.
Referenced by xmmsc_sc_namespace_remove().
x_list_t* x_list_find_custom (x_list_t * list, const void * data, XCompareFunc func)
Definition at line 363 of file xlist.c.
x_list_t* x_list_first (x_list_t * list)
Definition at line 421 of file xlist.c.
void x_list_foreach (x_list_t * list, XFunc func, void * user_data)
Definition at line 446 of file xlist.c.
void x_list_free (x_list_t * list)
Definition at line 45 of file xlist.c.
Referenced by x_queue_free(), xmmsc_ipc_destroy(), and xmmsc_sc_namespace_destroy().
void x_list_free_1 (x_list_t * list)
Definition at line 58 of file xlist.c.
Referenced by x_queue_pop_head(), and x_queue_pop_tail().
int x_list_index (x_list_t * list, const void * data)
Definition at line 394 of file xlist.c.
x_list_t* x_list_insert (x_list_t * list, void * data, int position)
Definition at line 105 of file xlist.c.
x_list_t* x_list_insert_before (x_list_t * list, x_list_t * sibling, void * data)
Definition at line 138 of file xlist.c.
x_list_t* x_list_insert_sorted (x_list_t * list, void * data, XCompareFunc func)
Definition at line 457 of file xlist.c.
x_list_t* x_list_last (x_list_t * list)
Definition at line 410 of file xlist.c.
Referenced by x_list_append(), and x_list_concat().
unsigned int x_list_length (x_list_t * list)
Definition at line 432 of file xlist.c.
x_list_t* x_list_nth (x_list_t * list, unsigned int n)
Definition at line 324 of file xlist.c.
Referenced by x_list_insert().
void* x_list_nth_data (x_list_t * list, unsigned int n)
Definition at line 342 of file xlist.c.
x_list_t* x_list_nth_prev (x_list_t * list, unsigned int n)
Definition at line 333 of file xlist.c.
int x_list_position (x_list_t * list, x_list_t * link)
Definition at line 378 of file xlist.c.
x_list_t* x_list_prepend (x_list_t * list, void * data)
Definition at line 85 of file xlist.c.
Referenced by x_list_insert(), x_queue_push_head(), and xmmsc_ipc_result_register().
x_list_t* x_list_remove (x_list_t * list, const void * data)
Definition at line 197 of file xlist.c.
x_list_t* x_list_remove_all (x_list_t * list, const void * data)
Definition at line 223 of file xlist.c.
x_list_t* x_list_remove_link (x_list_t * list, x_list_t * link)
Definition at line 269 of file xlist.c.
x_list_t* x_list_reverse (x_list_t * list)
Definition at line 308 of file xlist.c.