XmmsClient: include/xmmsc/xmmsc_ipc_msg.h File Reference
xmmsc_ipc_msg.h File Reference
#include <xmmsc/xmmsc_compiler.h>
#include <xmmsc/xmmsc_stdint.h>
#include <xmmsc/xmmsc_stdbool.h>
#include <xmmsc/xmmsc_util.h>
#include <xmmsc/xmmsc_ipc_transport.h>
#include <xmmsc/xmmsv_coll.h>
#include <xmmsc/xmmsv.h>
Macros
#define XMMS_IPC_MSG_DEFAULT_SIZE 128 /*32768*/
#define XMMS_IPC_MSG_HEAD_LEN 16 /* all but data */
Typedefs
typedef struct xmms_ipc_msg_St xmms_ipc_msg_t
Functions
uint32_t xmms_ipc_msg_get_object (const xmms_ipc_msg_t *msg)
uint32_t xmms_ipc_msg_get_cmd (const xmms_ipc_msg_t *msg)
uint32_t xmms_ipc_msg_get_cookie (const xmms_ipc_msg_t *msg)
void xmms_ipc_msg_set_cookie (xmms_ipc_msg_t *msg, uint32_t cookie)
xmms_ipc_msg_t * xmms_ipc_msg_new (uint32_t object, uint32_t cmd)
xmms_ipc_msg_t * xmms_ipc_msg_alloc (void)
void xmms_ipc_msg_destroy (xmms_ipc_msg_t *msg)
bool xmms_ipc_msg_write_transport (xmms_ipc_msg_t *msg, xmms_ipc_transport_t *transport, bool *disconnected)
bool xmms_ipc_msg_read_transport (xmms_ipc_msg_t *msg, xmms_ipc_transport_t *transport, bool *disconnected)
uint32_t xmms_ipc_msg_put_value (xmms_ipc_msg_t *msg, xmmsv_t *v)
bool xmms_ipc_msg_get_value (xmms_ipc_msg_t *msg, xmmsv_t **val)
Macro Definition Documentation
#define XMMS_IPC_MSG_DEFAULT_SIZE 128 /*32768*/
Definition at line 28 of file xmmsc_ipc_msg.h.
#define XMMS_IPC_MSG_HEAD_LEN 16 /* all but data */
Definition at line 29 of file xmmsc_ipc_msg.h.
Typedef Documentation
typedef struct xmms_ipc_msg_St xmms_ipc_msg_t
Definition at line 31 of file xmmsc_ipc_msg.h.
Function Documentation
xmms_ipc_msg_t* xmms_ipc_msg_alloc (void)
Referenced by xmmsc_ipc_io_in_callback().
void xmms_ipc_msg_destroy (xmms_ipc_msg_t * msg)
Referenced by xmmsc_ipc_destroy(), xmmsc_ipc_disconnect(), xmmsc_ipc_io_out_callback(), and xmmsc_result_run().
uint32_t xmms_ipc_msg_get_cmd (const xmms_ipc_msg_t * msg)
Referenced by xmmsc_send_msg().
uint32_t xmms_ipc_msg_get_cookie (const xmms_ipc_msg_t * msg)
uint32_t xmms_ipc_msg_get_object (const xmms_ipc_msg_t * msg)
Referenced by xmmsc_send_msg().
bool xmms_ipc_msg_get_value (xmms_ipc_msg_t * msg, xmmsv_t ** val)
xmms_ipc_msg_t* xmms_ipc_msg_new (uint32_t object, uint32_t cmd)
Referenced by xmmsc_send_cmd(), xmmsc_send_cmd_cookie(), xmmsc_send_msg_no_arg(), and xmmsc_write_signal_msg().
uint32_t xmms_ipc_msg_put_value (xmms_ipc_msg_t * msg, xmmsv_t * v)
Referenced by xmmsc_send_cmd(), xmmsc_send_cmd_cookie(), xmmsc_send_msg_no_arg(), and xmmsc_write_signal_msg().
bool xmms_ipc_msg_read_transport (xmms_ipc_msg_t * msg, xmms_ipc_transport_t * transport, bool * disconnected)
Referenced by xmmsc_ipc_io_in_callback().
void xmms_ipc_msg_set_cookie (xmms_ipc_msg_t * msg, uint32_t cookie)
Referenced by xmmsc_ipc_msg_write().
bool xmms_ipc_msg_write_transport (xmms_ipc_msg_t * msg, xmms_ipc_transport_t * transport, bool * disconnected)
Referenced by xmmsc_ipc_io_out_callback().