XmmsClient: include/xmmsc/xmmsc_ipc_transport.h File Reference
xmmsc_ipc_transport.h File Reference
#include <xmmsc/xmmsc_stdint.h>
#include <xmmsc/xmmsc_sockets.h>
Data Structures
struct xmms_ipc_transport_St
Typedefs
typedef struct
xmms_ipc_transport_St xmms_ipc_transport_t
typedef int(* xmms_ipc_read_func)(xmms_ipc_transport_t *, char *, int)
typedef int(* xmms_ipc_write_func)(xmms_ipc_transport_t *, char *, int)
typedef xmms_ipc_transport_t *(* xmms_ipc_accept_func)(xmms_ipc_transport_t *)
typedef void(* xmms_ipc_destroy_func)(xmms_ipc_transport_t *)
Functions
void xmms_ipc_transport_destroy (xmms_ipc_transport_t *ipct)
int xmms_ipc_transport_read (xmms_ipc_transport_t *ipct, char *buffer, int len)
int xmms_ipc_transport_write (xmms_ipc_transport_t *ipct, char *buffer, int len)
xmms_socket_t xmms_ipc_transport_fd_get (xmms_ipc_transport_t *ipct)
xmms_ipc_transport_t * xmms_ipc_server_accept (xmms_ipc_transport_t *ipct)
xmms_ipc_transport_t * xmms_ipc_client_init (const char *path)
xmms_ipc_transport_t * xmms_ipc_server_init (const char *path)
char * xmms_ipc_hostname (const char *path)
Typedef Documentation
typedef xmms_ipc_transport_t*(* xmms_ipc_accept_func)(xmms_ipc_transport_t *)
Definition at line 28 of file xmmsc_ipc_transport.h.
typedef void(* xmms_ipc_destroy_func)(xmms_ipc_transport_t *)
Definition at line 29 of file xmmsc_ipc_transport.h.
typedef int(* xmms_ipc_read_func)(xmms_ipc_transport_t *, char *, int)
Definition at line 26 of file xmmsc_ipc_transport.h.
typedef struct xmms_ipc_transport_St xmms_ipc_transport_t
Definition at line 24 of file xmmsc_ipc_transport.h.
typedef int(* xmms_ipc_write_func)(xmms_ipc_transport_t *, char *, int)
Definition at line 27 of file xmmsc_ipc_transport.h.
Function Documentation
xmms_ipc_transport_t* xmms_ipc_client_init (const char * path)
Referenced by xmmsc_ipc_connect().
char* xmms_ipc_hostname (const char * path)
xmms_ipc_transport_t* xmms_ipc_server_accept (xmms_ipc_transport_t * ipct)
xmms_ipc_transport_t* xmms_ipc_server_init (const char * path)
void xmms_ipc_transport_destroy (xmms_ipc_transport_t * ipct)
Referenced by xmmsc_ipc_destroy().
xmms_socket_t xmms_ipc_transport_fd_get (xmms_ipc_transport_t * ipct)
Referenced by xmmsc_ipc_fd_get(), and xmmsc_ipc_wait_for_event().
int xmms_ipc_transport_read (xmms_ipc_transport_t * ipct, char * buffer, int len)
int xmms_ipc_transport_write (xmms_ipc_transport_t * ipct, char * buffer, int len)