XmmsClient: include/xmmsc/xmmsc_util.h File Reference
xmmsc_util.h File Reference
#include <xmmsc/xmmsc_stdbool.h>
#include <xmmsc/xmmsc_compiler.h>
Macros
#define XMMS_STRINGIFY_NOEXPAND(x) #x
#define XMMS_STRINGIFY(x) XMMS_STRINGIFY_NOEXPAND(x)
#define XMMS_PATH_MAX 255
#define XMMS_DEFAULT_TCP_PORT 9667
Functions
const char * xmms_userconfdir_get (char *buf, int len) XMMS_PUBLIC
const char * xmms_usercachedir_get (char *buf, int len) XMMS_PUBLIC
const char * xmms_default_ipcpath_get (char *buf, int len) XMMS_PUBLIC
const char * xmms_fallback_ipcpath_get (char *buf, int len)
bool xmms_sleep_ms (int n)
Macro Definition Documentation
#define XMMS_DEFAULT_TCP_PORT 9667
Definition at line 13 of file xmmsc_util.h.
#define XMMS_PATH_MAX 255
Definition at line 10 of file xmmsc_util.h.
#define XMMS_STRINGIFY (x) XMMS_STRINGIFY_NOEXPAND(x)
Definition at line 8 of file xmmsc_util.h.
#define XMMS_STRINGIFY_NOEXPAND (x) #x
Definition at line 7 of file xmmsc_util.h.
Function Documentation
const char* xmms_default_ipcpath_get (char * buf, int len)
Referenced by xmmsc_connect().
const char* xmms_fallback_ipcpath_get (char * buf, int len)
bool xmms_sleep_ms (int n)
Referenced by check_drawtime().
const char* xmms_usercachedir_get (char * buf, int len)
const char* xmms_userconfdir_get (char * buf, int len)
Referenced by xmmsc_userconfdir_get().