XmmsClient: clients/lib/xmmsclient/xmmsclient.c File Reference
xmmsclient.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <sys/types.h>
#include <string.h>
#include <ctype.h>
#include <limits.h>
#include <xmmscpriv/xmms_list.h>
#include <xmmsclient/xmmsclient.h>
#include <xmmsclientpriv/xmmsclient.h>
#include <xmmsc/xmmsc_idnumbers.h>
#include <xmmsc/xmmsc_stdint.h>
#include <xmmsc/xmmsc_stringport.h>
#include <xmmsc/xmmsc_util.h>
Macros
#define XMMS_MAX_URI_LEN 1024
Functions
xmmsc_connection_t * xmmsc_init (const char *clientname)
Initializes a xmmsc_connection_t.
int xmmsc_connect (xmmsc_connection_t *c, const char *ipcpath)
Connects to the XMMS server.
void xmmsc_disconnect_callback_set (xmmsc_connection_t *c, xmmsc_disconnect_func_t callback, void *userdata)
Set the disconnect callback.
void xmmsc_disconnect_callback_set_full (xmmsc_connection_t *c, xmmsc_disconnect_func_t callback, void *userdata, xmmsc_user_data_free_func_t free_func)
char * xmmsc_get_last_error (xmmsc_connection_t *c)
Returns a string that descibes the last error.
void xmmsc_unref (xmmsc_connection_t *c)
Dereference the xmmsc_connection_t and free the memory when reference count reaches zero.
xmmsc_connection_t * xmmsc_ref (xmmsc_connection_t *c)
References the xmmsc_connection_t.
void xmmsc_lock_set (xmmsc_connection_t *c, void *lock, void(*lockfunc)(void *), void(*unlockfunc)(void *))
Set locking functions for a connection.
xmmsc_result_t * xmmsc_quit (xmmsc_connection_t *c)
Tell the server to quit.
xmmsc_result_t * xmmsc_broadcast_quit (xmmsc_connection_t *c)
Request the quit broadcast.
const char * xmmsc_userconfdir_get (char *buf, int len)
Get the absolute path to the user config dir.
xmmsc_result_t * xmmsc_send_broadcast_msg (xmmsc_connection_t *c, int signalid)
uint32_t xmmsc_write_signal_msg (xmmsc_connection_t *c, int signalid)
xmmsc_result_t * xmmsc_send_signal_msg (xmmsc_connection_t *c, int signalid)
xmmsc_result_t * xmmsc_send_msg_no_arg (xmmsc_connection_t *c, int object, int method)
xmmsc_result_t * xmmsc_send_msg (xmmsc_connection_t *c, xmms_ipc_msg_t *msg)
xmmsc_result_t * xmmsc_send_cmd (xmmsc_connection_t *c, int obj, int cmd,...)
uint32_t xmmsc_send_cmd_cookie (xmmsc_connection_t *c, int obj, int cmd,...)
int xmmsc_io_want_out (xmmsc_connection_t *c)
Check for pending output.
int xmmsc_io_out_handle (xmmsc_connection_t *c)
Write pending data.
int xmmsc_io_in_handle (xmmsc_connection_t *c)
Read available data.
int xmmsc_io_fd_get (xmmsc_connection_t *c)
Retrieve filedescriptor for connection.
void xmmsc_io_need_out_callback_set (xmmsc_connection_t *c, void(*callback)(int, void *), void *userdata)
Set callback for enabling/disabling writing.
void xmmsc_io_need_out_callback_set_full (xmmsc_connection_t *c, void(*callback)(int, void *), void *userdata, xmmsc_user_data_free_func_t free_func)
void xmmsc_io_disconnect (xmmsc_connection_t *c)
Flag connection as disconnected.
Macro Definition Documentation
#define XMMS_MAX_URI_LEN 1024
Definition at line 37 of file xmmsclient.c.
Function Documentation
xmmsc_result_t* xmmsc_send_broadcast_msg (xmmsc_connection_t * c, int signalid)
Definition at line 359 of file xmmsclient.c.
Referenced by xmmsc_broadcast_c2c_client_connected(), xmmsc_broadcast_c2c_client_disconnected(), xmmsc_broadcast_c2c_message(), xmmsc_broadcast_c2c_ready(), xmmsc_broadcast_collection_changed(), xmmsc_broadcast_config_value_changed(), xmmsc_broadcast_mediainfo_reader_status(), xmmsc_broadcast_medialib_entry_added(), xmmsc_broadcast_medialib_entry_changed(), xmmsc_broadcast_medialib_entry_removed(), xmmsc_broadcast_medialib_entry_updated(), xmmsc_broadcast_playback_current_id(), xmmsc_broadcast_playback_status(), xmmsc_broadcast_playback_volume_changed(), xmmsc_broadcast_playlist_changed(), xmmsc_broadcast_playlist_current_pos(), xmmsc_broadcast_playlist_loaded(), and xmmsc_broadcast_quit().
xmmsc_result_t* xmmsc_send_cmd (xmmsc_connection_t * c, int obj, int cmd, ...)
Definition at line 439 of file xmmsclient.c.
Referenced by setup_shm_prepare(), setup_udp_prepare(), xmmsc_bindata_add(), xmmsc_bindata_list(), xmmsc_bindata_remove(), xmmsc_bindata_retrieve(), xmmsc_coll_find(), xmmsc_coll_get(), xmmsc_coll_idlist_from_playlist_file(), xmmsc_coll_list(), xmmsc_coll_query(), xmmsc_coll_query_infos(), xmmsc_coll_remove(), xmmsc_coll_rename(), xmmsc_coll_save(), xmmsc_coll_sync(), xmmsc_config_get_value(), xmmsc_config_register_value(), xmmsc_config_set_value(), xmmsc_main_list_plugins(), xmmsc_medialib_entry_property_remove_with_source(), xmmsc_medialib_entry_property_set_int_with_source(), xmmsc_medialib_entry_property_set_str_with_source(), xmmsc_medialib_get_info(), xmmsc_medialib_move_entry(), xmmsc_medialib_rehash(), xmmsc_medialib_remove_entry(), xmmsc_playback_seek_ms(), xmmsc_playback_seek_samples(), xmmsc_playback_volume_set(), xmmsc_playlist_add_collection(), xmmsc_playlist_add_encoded(), xmmsc_playlist_add_id(), xmmsc_playlist_add_idlist(), xmmsc_playlist_clear(), xmmsc_playlist_current_pos(), xmmsc_playlist_insert_collection(), xmmsc_playlist_insert_encoded(), xmmsc_playlist_insert_id(), xmmsc_playlist_list_entries(), xmmsc_playlist_load(), xmmsc_playlist_move_entry(), xmmsc_playlist_radd_encoded(), xmmsc_playlist_remove_entry(), xmmsc_playlist_replace(), xmmsc_playlist_rinsert_encoded(), xmmsc_playlist_set_next(), xmmsc_playlist_set_next_rel(), xmmsc_playlist_shuffle(), xmmsc_playlist_sort(), xmmsc_send_broadcast_msg(), xmmsc_send_signal_msg(), xmmsc_visualization_properties_set(), xmmsc_visualization_property_set(), xmmsc_visualization_shutdown(), xmmsc_visualization_start_handle(), and xmmsc_xform_media_browse_encoded().
uint32_t xmmsc_send_cmd_cookie (xmmsc_connection_t * c, int obj, int cmd, ...)
Definition at line 460 of file xmmsclient.c.
Referenced by xmmsc_c2c_reply(), and xmmsc_c2c_send().
xmmsc_result_t* xmmsc_send_msg (xmmsc_connection_t * c, xmms_ipc_msg_t * msg)
Definition at line 419 of file xmmsclient.c.
Referenced by xmmsc_send_cmd().
xmmsc_result_t* xmmsc_send_msg_no_arg (xmmsc_connection_t * c, int object, int method)
Definition at line 401 of file xmmsclient.c.
Referenced by xmmsc_c2c_get_connected_clients(), xmmsc_c2c_get_ready_clients(), xmmsc_c2c_ready(), xmmsc_config_list_values(), xmmsc_main_stats(), xmmsc_playback_current_id(), xmmsc_playback_pause(), xmmsc_playback_playtime(), xmmsc_playback_start(), xmmsc_playback_status(), xmmsc_playback_stop(), xmmsc_playback_tickle(), xmmsc_playback_volume_get(), xmmsc_playlist_current_active(), xmmsc_quit(), xmmsc_visualization_init(), and xmmsc_visualization_version().
xmmsc_result_t* xmmsc_send_signal_msg (xmmsc_connection_t * c, int signalid)
Definition at line 388 of file xmmsclient.c.
Referenced by xmmsc_signal_mediainfo_reader_unindexed(), and xmmsc_signal_playback_playtime().
uint32_t xmmsc_write_signal_msg (xmmsc_connection_t * c, int signalid)
Definition at line 368 of file xmmsclient.c.