XmmsClient: clients/lib/xmmsclient/xqueue.c File Reference
xqueue.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <xmmscpriv/xmms_list.h>
#include <xmmsclientpriv/xmmsclient_util.h>
#include <xmmsclientpriv/xmmsclient_queue.h>
#include <xmmsc/xmmsc_util.h>
#include <xmmsc/xmmsc_stdbool.h>
Functions
x_queue_t * x_queue_new (void)
void x_queue_free (x_queue_t *queue)
void x_queue_push_head (x_queue_t *queue, void *data)
void x_queue_push_tail (x_queue_t *queue, void *data)
void * x_queue_pop_head (x_queue_t *queue)
void * x_queue_pop_tail (x_queue_t *queue)
void * x_queue_peek_head (x_queue_t *queue)
void * x_queue_peek_tail (x_queue_t *queue)
bool x_queue_is_empty (x_queue_t *queue)
Function Documentation
void x_queue_free (x_queue_t * queue)
Referenced by xmmsc_ipc_destroy().
bool x_queue_is_empty (x_queue_t * queue)
Referenced by xmmsc_ipc_io_out(), and xmmsc_ipc_io_out_callback().
x_queue_t* x_queue_new (void)
Referenced by xmmsc_ipc_init().
void* x_queue_peek_head (x_queue_t * queue)
Referenced by xmmsc_ipc_io_out_callback().
void* x_queue_peek_tail (x_queue_t * queue)
void* x_queue_pop_head (x_queue_t * queue)
Referenced by xmmsc_ipc_io_out_callback().
void* x_queue_pop_tail (x_queue_t * queue)
void x_queue_push_head (x_queue_t * queue, void * data)
void x_queue_push_tail (x_queue_t * queue, void * data)
Referenced by xmmsc_ipc_msg_write().