XMMS2: Fetch Specifications
Fetch Specifications
S4
Specifies what to fetch in a query.
Functions
s4_fetchspec_t * s4_fetchspec_create (void)
Creates a new fetch specification.
void s4_fetchspec_add (s4_fetchspec_t *spec, const char *key, s4_sourcepref_t *sourcepref, int flags)
Adds something to fetch to the fetch specification.
void s4_fetchspec_update_key (s4_t *s4, s4_fetchspec_t *spec)
void s4_fetchspec_free (s4_fetchspec_t *spec)
Frees a fetchspec.
s4_fetchspec_t * s4_fetchspec_ref (s4_fetchspec_t *spec)
void s4_fetchspec_unref (s4_fetchspec_t *spec)
int s4_fetchspec_size (s4_fetchspec_t *spec)
Gets the size of the fetchspec.
const char * s4_fetchspec_get_key (s4_fetchspec_t *spec, int index)
Gets the key at a give index.
s4_sourcepref_t * s4_fetchspec_get_sourcepref (s4_fetchspec_t *spec, int index)
Gets the sourcepref at a give index.
int s4_fetchspec_get_flags (s4_fetchspec_t *spec, int index)
Detailed Description
Specifies what to fetch in a query.
Function Documentation
void s4_fetchspec_add (s4_fetchspec_t * spec, const char * key, s4_sourcepref_t * sourcepref, int flags)
Adds something to fetch to the fetch specification.
If key is NULL, it will fetch everything in an entry
Parameters
spec The specification to add to
key The key to fetch
sourcepref The sourcepref to use when deciding which key-value pair to fetch
flags Flags to decide what to fetch
Definition at line 64 of file fetchspec.c.
Referenced by CASE(), xmms_fetch_info_add_key(), xmms_fetch_info_new(), and xmms_medialib_session_property_set().
s4_fetchspec_t* s4_fetchspec_create (void)
Creates a new fetch specification.
Returns
A new fetchspec
Definition at line 45 of file fetchspec.c.
Referenced by CASE(), xmms_fetch_info_new(), and xmms_medialib_session_property_set().
void s4_fetchspec_free (s4_fetchspec_t * spec)
Frees a fetchspec.
Parameters
spec The fetchspec to free
Definition at line 102 of file fetchspec.c.
Referenced by CASE(), s4_fetchspec_unref(), xmms_fetch_info_free(), and xmms_medialib_session_property_set().
int s4_fetchspec_get_flags (s4_fetchspec_t * spec, int index)
Definition at line 184 of file fetchspec.c.
const char* s4_fetchspec_get_key (s4_fetchspec_t * spec, int index)
Gets the key at a give index.
Parameters
spec The fetchspec to find the key in
index The index of the key
Returns
The key, or NULL if index is out of bounds
Definition at line 162 of file fetchspec.c.
Referenced by print_fetch().
s4_sourcepref_t* s4_fetchspec_get_sourcepref (s4_fetchspec_t * spec, int index)
Gets the sourcepref at a give index.
Parameters
spec The fetchspec to find the sourcepref in
index The index of the sourcepref
Returns
The key, or NULL if index is out of bounds
Definition at line 176 of file fetchspec.c.
s4_fetchspec_t* s4_fetchspec_ref (s4_fetchspec_t * spec)
Definition at line 123 of file fetchspec.c.
int s4_fetchspec_size (s4_fetchspec_t * spec)
Gets the size of the fetchspec.
Parameters
spec The fetchspec to find the size of
Returns
The size of spec
Definition at line 151 of file fetchspec.c.
Referenced by _s4_query(), print_fetch(), and xmms_fetch_info_add_key().
void s4_fetchspec_unref (s4_fetchspec_t * spec)
Definition at line 135 of file fetchspec.c.
void s4_fetchspec_update_key (s4_t * s4, s4_fetchspec_t * spec)
Definition at line 83 of file fetchspec.c.
Referenced by _s4_query().