XMMS2: Config
Config
XMMSServer
Controls configuration for the server.
Macros
#define XMMS_CONFIG_VERSION 2
Config file version.
Functions
const gchar * xmms_config_property_lookup_get_string (xmms_config_t *conf, const gchar *key, xmms_error_t *err)
Config functions.
xmms_config_property_t * xmms_config_lookup (const gchar *path)
Look up a config key from the global config.
const gchar * xmms_config_property_get_name (const xmms_config_property_t *prop)
Get the name of a config property.
void xmms_config_property_set_data (xmms_config_property_t *prop, const gchar *data)
Set the data of the config property to a new value.
const gchar * xmms_config_property_get_string (const xmms_config_property_t *prop)
Return the value of a config property as a string.
gint xmms_config_property_get_int (const xmms_config_property_t *prop)
Return the value of a config property as an int.
gfloat xmms_config_property_get_float (const xmms_config_property_t *prop)
Return the value of a config property as a float.
void xmms_config_property_callback_set (xmms_config_property_t *prop, xmms_object_handler_t cb, gpointer userdata)
Set a callback function for a config property.
void xmms_config_property_callback_remove (xmms_config_property_t *prop, xmms_object_handler_t cb, gpointer userdata)
Remove a callback from a config property.
xmms_config_property_t * xmms_config_property_register (const gchar *path, const gchar *default_value, xmms_object_handler_t cb, gpointer userdata)
Register a new config property.
Detailed Description
Controls configuration for the server.
The configuration is saved to, and loaded from an XML file. It's split into plugin, client and core parts. This documents the configuration for parts inside the server. For plugin config see each server object's documentation.
Macro Definition Documentation
#define XMMS_CONFIG_VERSION 2
Config file version.
Definition at line 125 of file config.c.
Referenced by xmms_config_save().
Function Documentation
xmms_config_property_t* xmms_config_lookup (const gchar * path)
Look up a config key from the global config.
Parameters
path A configuration path. Could be core.myconfig or effect.foo.myconfig
Returns
An xmms_config_property_t
Definition at line 171 of file config.c.
Referenced by xmms_config_property_lookup_get_string(), and xmms_plugin_config_lookup().
void xmms_config_property_callback_remove (xmms_config_property_t * prop, xmms_object_handler_t cb, gpointer userdata)
Remove a callback from a config property.
Parameters
prop The config property
cb The callback to remove
Definition at line 299 of file config.c.
void xmms_config_property_callback_set (xmms_config_property_t * prop, xmms_object_handler_t cb, gpointer userdata)
Set a callback function for a config property.
This will be called each time the property's value changes.
Parameters
prop The config property
cb The callback to set
userdata Data to pass on to the callback
Definition at line 279 of file config.c.
Referenced by xmms_config_property_register().
gfloat xmms_config_property_get_float (const xmms_config_property_t * prop)
Return the value of a config property as a float.
Parameters
prop The config property
Returns
value as float
Definition at line 262 of file config.c.
gint xmms_config_property_get_int (const xmms_config_property_t * prop)
Return the value of a config property as an int.
Parameters
prop The config property
Returns
value as int
Definition at line 247 of file config.c.
Referenced by xmms_output_new(), xmms_playlist_init(), and xmms_xform_plugin_supports().
const gchar* xmms_config_property_get_name (const xmms_config_property_t * prop)
Get the name of a config property.
Parameters
prop The config property
Returns
Name of config property
Definition at line 189 of file config.c.
const gchar* xmms_config_property_get_string (const xmms_config_property_t * prop)
Return the value of a config property as a string.
Parameters
prop The config property
Returns
value as string
Definition at line 235 of file config.c.
Referenced by main(), on_config_ipcsocket_change(), xmms_bindata_init(), xmms_config_property_lookup_get_string(), and xmms_medialib_init().
const gchar* xmms_config_property_lookup_get_string (xmms_config_t * conf, const gchar * key, xmms_error_t * err)
Config functions.
Lookup config key and return its associated value as a string. This is a convenient function to make it easier to get a configuration value rather than having to call xmms_config_property_get_string separately.
Parameters
conf Global config
key Configuration property to lookup
err if error occurs this will be filled in
Returns
A string with the value. If the value is an int it will return NULL
Definition at line 149 of file config.c.
xmms_config_property_t* xmms_config_property_register (const gchar * path, const gchar * default_value, xmms_object_handler_t cb, gpointer userdata)
Register a new config property.
This should be called from the init code as XMMS2 won't allow set/get on properties that haven't been registered.
Parameters
path The path in the config tree.
default_value If the value was not found in the configfile, what should we use?
cb A callback function that will be called if the value is changed by the client. Can be set to NULL.
userdata Data to pass to the callback function.
Returns
A newly allocated xmms_config_property_t for the registered property.
Definition at line 326 of file config.c.
Referenced by main(), xmms_bindata_init(), xmms_coll_sync_init(), xmms_medialib_init(), xmms_output_new(), xmms_playlist_init(), and xmms_plugin_config_property_register().
void xmms_config_property_set_data (xmms_config_property_t * prop, const gchar * data)
Set the data of the config property to a new value.
Parameters
prop The config property
data The value to set
Definition at line 202 of file config.c.
Referenced by main(), and xmms_config_property_register().