XMMS2: Iteration
Iteration
Dictionaries
Typedefs
typedef void(* xmmsv_dict_foreach_func)(const char *key, xmmsv_t *value, void *user_data)
typedef struct xmmsv_dict_iter_St xmmsv_dict_iter_t
Functions
int xmmsv_dict_foreach (xmmsv_t *dictv, xmmsv_dict_foreach_func func, void *user_data)
Apply a function to each key-element pair in the list.
int xmmsv_get_dict_iter (const xmmsv_t *val, xmmsv_dict_iter_t **it)
Retrieves a dict iterator from a dict xmmsv_t.
void xmmsv_dict_iter_explicit_destroy (xmmsv_dict_iter_t *it)
Explicitly free dict iterator.
int xmmsv_dict_iter_pair (xmmsv_dict_iter_t *it, const char **key, xmmsv_t **val)
Get the key-element pair currently pointed at by the iterator.
int xmmsv_dict_iter_valid (xmmsv_dict_iter_t *it)
Check whether the iterator is valid and points to a valid pair.
void xmmsv_dict_iter_first (xmmsv_dict_iter_t *it)
Rewind the iterator to the start of the dict.
void xmmsv_dict_iter_next (xmmsv_dict_iter_t *it)
Advance the iterator to the next pair in the dict.
int xmmsv_dict_iter_find (xmmsv_dict_iter_t *it, const char *key)
Move the iterator to the pair with the given key (if it exists) or move it to the position where the key would have to be put (if it doesn't exist yet).
int xmmsv_dict_iter_set (xmmsv_dict_iter_t *it, xmmsv_t *val)
Replace the element of the pair currently pointed to by the iterator.
int xmmsv_dict_iter_remove (xmmsv_dict_iter_t *it)
Remove the pair in the dict pointed at by the iterator.
int xmmsv_dict_iter_pair_string (xmmsv_dict_iter_t *it, const char **key, const char **r)
int xmmsv_dict_iter_pair_int32 (xmmsv_dict_iter_t *it, const char **key, int32_t *r)
int xmmsv_dict_iter_pair_int64 (xmmsv_dict_iter_t *it, const char **key, int64_t *r)
int xmmsv_dict_iter_pair_float (xmmsv_dict_iter_t *it, const char **key, float *r)
int xmmsv_dict_iter_pair_coll (xmmsv_dict_iter_t *it, const char **key, xmmsv_t **r)
int xmmsv_dict_iter_set_string (xmmsv_dict_iter_t *it, const char *elem)
int xmmsv_dict_iter_set_int (xmmsv_dict_iter_t *it, int64_t elem)
int xmmsv_dict_iter_set_float (xmmsv_dict_iter_t *it, float elem)
int xmmsv_dict_iter_set_coll (xmmsv_dict_iter_t *it, xmmsv_t *elem)
Detailed Description
Typedef Documentation
typedef void(* xmmsv_dict_foreach_func)(const char *key, xmmsv_t *value, void *user_data)
Definition at line 59 of file xmmsv_dict.h.
typedef struct xmmsv_dict_iter_St xmmsv_dict_iter_t
Definition at line 62 of file xmmsv_dict.h.
Function Documentation
int xmmsv_dict_foreach (xmmsv_t * dictv, xmmsv_dict_foreach_func func, void * user_data)
Apply a function to each key-element pair in the list.
No particular order is assumed.
Parameters
dictv A xmmsv_t containing a dict.
function The function to apply to each key-element pair.
user_data User data passed to the foreach function.
Returns
1 upon success otherwise 0
Definition at line 449 of file xmmsv_dict.c.
Referenced by xmms_collection_restore(), and xmmsv_encode_url_full().
void xmmsv_dict_iter_explicit_destroy (xmmsv_dict_iter_t * it)
Explicitly free dict iterator.
Immediately frees any resources used by this iterator. The iterator is freed automatically when the dict is freed, but this function is useful when the dict can be long lived.
Parameters
it iterator to free
Definition at line 553 of file xmmsv_dict.c.
int xmmsv_dict_iter_find (xmmsv_dict_iter_t * it, const char * key)
Move the iterator to the pair with the given key (if it exists) or move it to the position where the key would have to be put (if it doesn't exist yet).
Parameters
it A xmmsv_dict_iter_t.
key The key to seek for.
Returns
1 upon success otherwise 0
Definition at line 646 of file xmmsv_dict.c.
Referenced by xmmsv_dict_format().
void xmmsv_dict_iter_first (xmmsv_dict_iter_t * it)
Rewind the iterator to the start of the dict.
Parameters
it A xmmsv_dict_iter_t.
Returns
1 upon success otherwise 0
Definition at line 609 of file xmmsv_dict.c.
Referenced by xmmsv_dict_iter_find().
void xmmsv_dict_iter_next (xmmsv_dict_iter_t * it)
Advance the iterator to the next pair in the dict.
Parameters
it A xmmsv_dict_iter_t.
Returns
1 upon success otherwise 0
Definition at line 626 of file xmmsv_dict.c.
Referenced by xmmsv_dict_foreach(), xmmsv_dict_iter_find(), xmmsv_dict_iter_remove(), xmmsv_encode_url_full(), and xmmsv_propdict_to_dict().
int xmmsv_dict_iter_pair (xmmsv_dict_iter_t * it, const char ** key, xmmsv_t ** val)
Get the key-element pair currently pointed at by the iterator.
This function does not increase the refcount of the element, the reference is still owned by the dict.
Parameters
it A xmmsv_dict_iter_t.
key Pointer set to the key pointed at by the iterator.
val Pointer set to a borrowed reference to the element pointed at by the iterator.
Returns
1 upon success otherwise 0
Definition at line 570 of file xmmsv_dict.c.
Referenced by xmmsv_dict_foreach(), xmmsv_dict_format(), xmmsv_dict_iter_find(), xmmsv_dict_iter_pair_coll(), xmmsv_encode_url_full(), and xmmsv_propdict_to_dict().
int xmmsv_dict_iter_pair_coll (xmmsv_dict_iter_t * it, const char ** key, xmmsv_t ** r)
Definition at line 777 of file xmmsv_dict.c.
int xmmsv_dict_iter_pair_float (xmmsv_dict_iter_t * it, const char ** key, float * r)
Definition at line 774 of file xmmsv_dict.c.
int xmmsv_dict_iter_pair_int32 (xmmsv_dict_iter_t * it, const char ** key, int32_t * r)
Definition at line 772 of file xmmsv_dict.c.
int xmmsv_dict_iter_pair_int64 (xmmsv_dict_iter_t * it, const char ** key, int64_t * r)
Definition at line 773 of file xmmsv_dict.c.
int xmmsv_dict_iter_pair_string (xmmsv_dict_iter_t * it, const char ** key, const char ** r)
Definition at line 771 of file xmmsv_dict.c.
int xmmsv_dict_iter_remove (xmmsv_dict_iter_t * it)
Remove the pair in the dict pointed at by the iterator.
Parameters
it A xmmsv_dict_iter_t.
Returns
1 upon success otherwise 0
Definition at line 694 of file xmmsv_dict.c.
int xmmsv_dict_iter_set (xmmsv_dict_iter_t * it, xmmsv_t * val)
Replace the element of the pair currently pointed to by the iterator.
Parameters
it A xmmsv_dict_iter_t.
val The element to set in the pair.
Returns
1 upon success otherwise 0
Definition at line 674 of file xmmsv_dict.c.
Referenced by xmmsv_dict_iter_set_coll().
int xmmsv_dict_iter_set_coll (xmmsv_dict_iter_t * it, xmmsv_t * elem)
Definition at line 802 of file xmmsv_dict.c.
int xmmsv_dict_iter_set_float (xmmsv_dict_iter_t * it, float elem)
Definition at line 799 of file xmmsv_dict.c.
int xmmsv_dict_iter_set_int (xmmsv_dict_iter_t * it, int64_t elem)
Definition at line 798 of file xmmsv_dict.c.
int xmmsv_dict_iter_set_string (xmmsv_dict_iter_t * it, const char * elem)
Definition at line 797 of file xmmsv_dict.c.
int xmmsv_dict_iter_valid (xmmsv_dict_iter_t * it)
Check whether the iterator is valid and points to a valid pair.
Parameters
it A xmmsv_dict_iter_t.
Returns
1 if the iterator is valid, 0 otherwise
Definition at line 595 of file xmmsv_dict.c.
Referenced by xmmsv_dict_iter_find(), xmmsv_dict_iter_pair(), xmmsv_dict_iter_remove(), and xmmsv_dict_iter_set().
int xmmsv_get_dict_iter (const xmmsv_t * val, xmmsv_dict_iter_t ** it)
Retrieves a dict iterator from a dict xmmsv_t.
Parameters
val a xmmsv_t containing a dict.
it An xmmsv_dict_iter_t that can be used to access the dict data. The iterator will be freed when the value is freed.
Returns
1 upon success otherwise 0
Definition at line 522 of file xmmsv_dict.c.
Referenced by xmmsv_dict_foreach(), xmmsv_dict_format(), xmmsv_encode_url_full(), and xmmsv_propdict_to_dict().