XMMS2: src/lib/s4/src/tools/bench/s4_bench.c File Reference
s4_bench.c File Reference
#include "s4.h"
#include <stdio.h>
#include <stdlib.h>
#include <glib.h>
#include <glib/gstdio.h>
Macros
#define ENTRIES 10000
Functions
void log_init (GLogLevelFlags log_lev)
long timediff (GTimeVal *prev, GTimeVal *cur)
void take_time (const char *message, GTimeVal *prev, GTimeVal *cur)
int main (int argc, char *argv[])
Macro Definition Documentation
#define ENTRIES 10000
Definition at line 21 of file s4_bench.c.
Referenced by main().
Function Documentation
void log_init (GLogLevelFlags log_lev)
Definition at line 31 of file logging.c.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 46 of file s4_bench.c.
void take_time (const char * message, GTimeVal * prev, GTimeVal * cur)
Definition at line 35 of file s4_bench.c.
Referenced by main().
long timediff (GTimeVal * prev, GTimeVal * cur)
Definition at line 25 of file s4_bench.c.
Referenced by take_time().