XMMS2: src/lib/xmmsutils/utils_win32.c File Reference
utils_win32.c File Reference
Miscellaneous internal utility functions.
#include <stdlib.h>
#include <windows.h>
#include <time.h>
#include <xmmsc/xmmsc_util.h>
Functions
const char * xmms_userconfdir_get (char *buf, int len)
Get the absolute path to the user config dir.
const char * xmms_fallback_ipcpath_get (char *buf, int len)
Get the fallback connection path (if XMMS_PATH is not accessible)
bool xmms_sleep_ms (int n)
Sleep for n milliseconds.
Detailed Description
Miscellaneous internal utility functions.
Definition in file utils_win32.c.
Function Documentation
const char* xmms_fallback_ipcpath_get (char * buf, int len)
Get the fallback connection path (if XMMS_PATH is not accessible)
Parameters
buf A char buffer
len The length of buf (XMMS_PATH_MAX is a good choice)
Returns
A pointer to buf, or NULL if an error occured.
Definition at line 62 of file utils_win32.c.
Referenced by main(), and xmms_default_ipcpath_get().
bool xmms_sleep_ms (int n)
Sleep for n milliseconds.
Parameters
n The number of milliseconds to sleep.
Returns
true when we waited the full time, false otherwise.
Definition at line 76 of file utils_win32.c.
const char* xmms_userconfdir_get (char * buf, int len)
Get the absolute path to the user config dir.
Parameters
buf A char buffer
len The length of buf (XMMS_PATH_MAX is a good choice)
Returns
A pointer to buf, or NULL if an error occurred.
Definition at line 35 of file utils_win32.c.
Referenced by xmms_build_path().