XMMS2: src/lib/s4/src/tools/s4/cli.h File Reference
cli.h File Reference
#include <s4.h>
#include <glib.h>
Data Structures
struct range_t
struct list_data_t
struct list_t
Macros
#define MAX_LINE_COUNT 128
Functions
void init_lexer (char *lines[], int line_count)
int yylex (void)
const char * value_to_string (const s4_val_t *val)
int find_column (const char *key, const s4_resultset_t *set)
void print_list (list_t *list)
void print_result (const s4_resultset_t *res)
void print_cond (s4_condition_t *cond)
void print_fetch (s4_fetchspec_t *fetch)
void print_vars (void)
void print_help (void)
void config_init (void)
void config_cleanup (void)
void set_var (const char *key, char *val)
const char * get_var (const char *key)
void print_set_var (const char *key)
Variables
GHashTable * cond_table
GHashTable * res_table
GHashTable * list_table
GHashTable * fetch_table
GHashTable * pref_table
char ** lines
s4_t * s4
Macro Definition Documentation
#define MAX_LINE_COUNT 128
Definition at line 35 of file cli.h.
Function Documentation
void config_cleanup (void)
Definition at line 125 of file config.c.
void config_init (void)
Definition at line 100 of file config.c.
int find_column (const char * key, const s4_resultset_t * set)
Definition at line 140 of file print.c.
const char* get_var (const char * key)
Definition at line 182 of file config.c.
Referenced by print_fetch(), print_list(), and print_result().
void init_lexer (char * lines[], int line_count)
void print_cond (s4_condition_t * cond)
Definition at line 239 of file print.c.
Referenced by print_vars().
void print_fetch (s4_fetchspec_t * fetch)
Definition at line 292 of file print.c.
Referenced by print_vars().
void print_help (void)
Definition at line 347 of file print.c.
void print_list (list_t * list)
Definition at line 39 of file print.c.
Referenced by print_vars().
void print_result (const s4_resultset_t * res)
Definition at line 170 of file print.c.
Referenced by print_vars().
void print_set_var (const char * key)
Definition at line 198 of file config.c.
void print_vars (void)
Definition at line 313 of file print.c.
void set_var (const char * key, char * val)
Definition at line 150 of file config.c.
Referenced by config_init().
const char* value_to_string (const s4_val_t * val)
Definition at line 24 of file print.c.
Referenced by print_cond(), print_list(), and print_result().
int yylex (void)
Variable Documentation
GHashTable* cond_table
Referenced by print_vars().
GHashTable * fetch_table
Referenced by print_vars().
char** lines
GHashTable * list_table
Referenced by print_vars().
GHashTable * pref_table
GHashTable * res_table
Referenced by print_vars().
s4_t* s4
Definition at line 31 of file t_s4.c.
Referenced by _s4_add(), _s4_del(), _s4_query(), _transaction_dummy_alloc(), main(), s4_begin(), s4_commit(), s4_open(), and s4_val_new_internal_string().