XMMS2: src/xmms/visualization/common.h File Reference
common.h File Reference
#include <glib.h>
#include <xmmspriv/xmms_log.h>
#include <xmmspriv/xmms_visualization.h>
#include <xmmsc/xmmsc_visualization.h>
Data Structures
struct xmms_vis_client_t
The structures for a vis client.
struct xmms_visualization_St
The structures for the vis module.
Macros
#define x_fetch_client(id)
#define x_release_client() g_mutex_unlock (&vis->clientlock);
Functions
xmms_vis_client_t * get_client (int32_t id)
void delete_client (int32_t id)
void send_data (int channels, int size, int16_t *buf)
int32_t init_shm (xmms_visualization_t *vis, int32_t id, int32_t shmid, xmms_error_t *err)
void cleanup_shm (xmmsc_vis_unixshm_t *t)
gboolean write_start_shm (int32_t id, xmmsc_vis_unixshm_t *t, xmmsc_vischunk_t **dest)
void write_finish_shm (int32_t id, xmmsc_vis_unixshm_t *t, xmmsc_vischunk_t *dest)
gboolean write_shm (xmmsc_vis_unixshm_t *t, xmms_vis_client_t *c, int32_t id, struct timeval *time, int channels, int size, short *buf)
int32_t init_udp (xmms_visualization_t *vis, int32_t id, xmms_error_t *err)
void cleanup_udp (xmmsc_vis_udp_t *t, xmms_socket_t socket)
gboolean write_udp (xmmsc_vis_udp_t *t, xmms_vis_client_t *c, int32_t id, struct timeval *time, int channels, int size, short *buf, int socket)
void fft_init (void)
short fill_buffer (int16_t *dest, xmmsc_vis_properties_t *prop, int channels, int size, short *src)
Macro Definition Documentation
#define x_fetch_client (id)
Value:
g_mutex_lock (&vis->clientlock); \
    c = get_client (id); \
    if (!c) { \
        xmms_error_set (err, XMMS_ERROR_INVAL, "invalid server-side identifier provided"); \
        g_mutex_unlock (&vis->clientlock); \
        return -1; \
    }
Definition at line 63 of file common.h.
Referenced by init_shm(), and init_udp().
#define x_release_client () g_mutex_unlock (&vis->clientlock);
Definition at line 71 of file common.h.
Referenced by init_shm(), and init_udp().
Function Documentation
void cleanup_shm (xmmsc_vis_unixshm_t * t)
Definition at line 27 of file dummy.c.
Referenced by delete_client().
void cleanup_udp (xmmsc_vis_udp_t * t, xmms_socket_t socket)
Definition at line 174 of file udp.c.
Referenced by delete_client().
void fft_init (void)
Definition at line 18 of file format.c.
Referenced by send_data().
short fill_buffer (int16_t * dest, xmmsc_vis_properties_t * prop, int channels, int size, short * src)
Definition at line 148 of file format.c.
Referenced by write_shm(), and write_udp().
int32_t init_shm (xmms_visualization_t * vis, int32_t id, int32_t shmid, xmms_error_t * err)
Definition at line 20 of file dummy.c.
int32_t init_udp (xmms_visualization_t * vis, int32_t id, xmms_error_t * err)
Definition at line 107 of file udp.c.
void send_data (int channels, int size, int16_t * buf)
void write_finish_shm (int32_t id, xmmsc_vis_unixshm_t * t, xmmsc_vischunk_t * dest)
Definition at line 33 of file dummy.c.
Referenced by write_shm().
gboolean write_shm (xmmsc_vis_unixshm_t * t, xmms_vis_client_t * c, int32_t id, struct timeval * time, int channels, int size, short * buf)
Definition at line 36 of file dummy.c.
gboolean write_start_shm (int32_t id, xmmsc_vis_unixshm_t * t, xmmsc_vischunk_t ** dest)
Definition at line 30 of file dummy.c.
Referenced by write_shm().
gboolean write_udp (xmmsc_vis_udp_t * t, xmms_vis_client_t * c, int32_t id, struct timeval * time, int channels, int size, short * buf, int socket)
Definition at line 182 of file udp.c.