XMMS2: src/lib/s4/src/lib/const.c File Reference
const.c File Reference
#include "s4_priv.h"
#include <stdlib.h>
Functions
s4_const_data_t * _const_create_data ()
void _const_free_data (s4_const_data_t *data)
const char * _string_lookup (s4_t *s4, const char *str)
Gets a pointer to a constant string that's equal to str.
const s4_val_t * _string_lookup_val (s4_t *s4, const char *str)
Gets a pointer to a constant string value with a string equal to str.
char * s4_string_collate (const char *str)
Creates a string that orders correctly according to the locale.
char * s4_string_casefold (const char *str)
Creates a casefolded version of the string.
const char * _string_lookup_casefolded (s4_t *s4, const char *str)
Gets the casefolded string corresponding to str.
const char * _string_lookup_collated (s4_t *s4, const char *str)
Gets the collated string corresponding to str.
const s4_val_t * _int_lookup_val (s4_t *s4, int32_t i)
const s4_val_t * _const_lookup (s4_t *s4, const s4_val_t *val)
Function Documentation
s4_const_data_t* _const_create_data (void)
Definition at line 42 of file const.c.
void _const_free_data (s4_const_data_t * data)
Definition at line 63 of file const.c.
const s4_val_t* _const_lookup (s4_t * s4, const s4_val_t * val)
Definition at line 222 of file const.c.
Referenced by s4_add(), and s4_del().
const s4_val_t* _int_lookup_val (s4_t * s4, int32_t i)
Definition at line 205 of file const.c.
Referenced by _const_lookup().
const char* _string_lookup (s4_t * s4, const char * str)
Gets a pointer to a constant string that's equal to str.
_string_lookup will always return the same pointer for the same string
Parameters
s4 The database to look for the string in
str The string to find the constant string of
Returns
A pointer to a string equal to str
Definition at line 87 of file const.c.
Referenced by _string_lookup_casefolded(), _string_lookup_collated(), s4_add(), s4_cond_update_key(), s4_del(), and s4_fetchspec_update_key().
const char* _string_lookup_casefolded (s4_t * s4, const char * str)
Gets the casefolded string corresponding to str.
str must have been obtained by calling _string_lookup.
Parameters
s4 The database to look in
str The string to find the casefold string of
Returns
The casefolded string of str
Definition at line 157 of file const.c.
Referenced by s4_val_get_casefolded_str().
const char* _string_lookup_collated (s4_t * s4, const char * str)
Gets the collated string corresponding to str.
str must have been obtained by calling _string_lookup.
Parameters
s4 The database to look in
str The string to find the collated string of
Returns
The collated string of str
Definition at line 185 of file const.c.
Referenced by s4_val_get_collated_str().
const s4_val_t* _string_lookup_val (s4_t * s4, const char * str)
Gets a pointer to a constant string value with a string equal to str.
_string_lookup_val will always return the same value for the same string.
Parameters
s4 The database to look for the string in
str The string to find the constant string of
Returns
A pointer to a string value
Definition at line 109 of file const.c.
Referenced by _const_lookup(), and _string_lookup().
char* s4_string_casefold (const char * str)
Creates a casefolded version of the string.
Parameters
str The string to casefold
Returns
A casefolded version of str, free with g_free
Definition at line 144 of file const.c.
Referenced by _string_lookup_casefolded(), and s4_val_get_casefolded_str().
char* s4_string_collate (const char * str)
Creates a string that orders correctly according to the locale.
Parameters
str The string to collate
Returns
A collated version of str, must be freed with g_free
Definition at line 133 of file const.c.
Referenced by _string_lookup_collated(), and s4_val_get_collated_str().