XMMS2: src/xmms/visualization/format.c File Reference
format.c File Reference
#include <math.h>
#include "common.h"
Macros
#define FFT_LEN XMMSC_VISUALIZATION_WINDOW_SIZE
#define FFT_BITS 9
#define AMP_LOG_SCALE_THRESHOLD0 0.001f
#define AMP_LOG_SCALE_DIVISOR 6.908f /* divisor = -log threshold */
#define FREQ_LOG_SCALE_BASE 2.0f
Functions
void fft_init ()
short fill_buffer (int16_t *dest, xmmsc_vis_properties_t *prop, int channels, int size, short *src)
Macro Definition Documentation
#define AMP_LOG_SCALE_DIVISOR 6.908f /* divisor = -log threshold */
Definition at line 10 of file format.c.
#define AMP_LOG_SCALE_THRESHOLD0 0.001f
Definition at line 9 of file format.c.
#define FFT_BITS 9
Definition at line 6 of file format.c.
#define FFT_LEN XMMSC_VISUALIZATION_WINDOW_SIZE
Definition at line 4 of file format.c.
Referenced by fft_init().
#define FREQ_LOG_SCALE_BASE 2.0f
Definition at line 11 of file format.c.
Function Documentation
void fft_init (void)
Definition at line 18 of file format.c.
Referenced by send_data().
short fill_buffer (int16_t * dest, xmmsc_vis_properties_t * prop, int channels, int size, short * src)
Definition at line 148 of file format.c.
Referenced by write_shm(), and write_udp().