XMMS2: Bitbuffer
Bitbuffer
The type xmmsv_t
Functions
xmmsv_t * xmmsv_bitbuffer_new_ro (const unsigned char *v, int len)
xmmsv_t * xmmsv_bitbuffer_new (void)
xmmsv_t * xmmsv_new_bitbuffer_ro (const unsigned char *v, int len)
Allocates a new bitbuffer xmmsv_t.
xmmsv_t * xmmsv_new_bitbuffer (void)
Allocates a new empty bitbuffer xmmsv_t.
int xmmsv_bitbuffer_get_bits (xmmsv_t *v, int bits, int64_t *res)
int xmmsv_bitbuffer_get_data (xmmsv_t *v, unsigned char *b, int len)
int xmmsv_bitbuffer_put_bits (xmmsv_t *v, int bits, int64_t d)
int xmmsv_bitbuffer_put_bits_at (xmmsv_t *v, int bits, int64_t d, int offset)
int xmmsv_bitbuffer_put_data (xmmsv_t *v, const unsigned char *b, int len)
int xmmsv_bitbuffer_align (xmmsv_t *v)
int xmmsv_bitbuffer_goto (xmmsv_t *v, int pos)
int xmmsv_bitbuffer_pos (xmmsv_t *v)
int xmmsv_bitbuffer_rewind (xmmsv_t *v)
int xmmsv_bitbuffer_end (xmmsv_t *v)
int xmmsv_bitbuffer_len (xmmsv_t *v)
const unsigned char * xmmsv_bitbuffer_buffer (xmmsv_t *v)
int xmmsv_get_bitbuffer (const xmmsv_t *val, const unsigned char **r, unsigned int *rlen)
Retrieves the bit buffer from the value.
int xmmsv_bitbuffer_serialize_value (xmmsv_t *bb, xmmsv_t *v)
int xmmsv_bitbuffer_deserialize_value (xmmsv_t *bb, xmmsv_t **val)
Detailed Description
Function Documentation
int xmmsv_bitbuffer_align (xmmsv_t * v)
Definition at line 189 of file xmmsv_bitbuffer.c.
Referenced by xmms_ipc_msg_write_transport().
const unsigned char* xmmsv_bitbuffer_buffer (xmmsv_t * v)
Definition at line 230 of file xmmsv_bitbuffer.c.
Referenced by xmms_ipc_msg_write_transport(), and xmmsv_serialize().
int xmmsv_bitbuffer_deserialize_value (xmmsv_t * bb, xmmsv_t ** val)
Definition at line 650 of file value_serialize.c.
Referenced by xmms_ipc_msg_get_value(), and xmmsv_deserialize().
int xmmsv_bitbuffer_end (xmmsv_t * v)
Definition at line 218 of file xmmsv_bitbuffer.c.
Referenced by xmms_ipc_msg_set_cookie().
int xmmsv_bitbuffer_get_bits (xmmsv_t * v, int bits, int64_t * res)
Definition at line 76 of file xmmsv_bitbuffer.c.
Referenced by xmms_ipc_msg_get_cmd(), xmms_ipc_msg_get_cookie(), xmms_ipc_msg_get_object(), and xmmsv_bitbuffer_get_data().
int xmmsv_bitbuffer_get_data (xmmsv_t * v, unsigned char * b, int len)
Definition at line 106 of file xmmsv_bitbuffer.c.
int xmmsv_bitbuffer_goto (xmmsv_t * v, int pos)
Definition at line 196 of file xmmsv_bitbuffer.c.
Referenced by xmms_ipc_msg_get_cmd(), xmms_ipc_msg_get_cookie(), xmms_ipc_msg_get_object(), xmms_ipc_msg_read_transport(), xmms_ipc_msg_set_cookie(), xmmsv_bitbuffer_end(), xmmsv_bitbuffer_put_bits_at(), xmmsv_bitbuffer_rewind(), and xmmsv_copy().
int xmmsv_bitbuffer_len (xmmsv_t * v)
Definition at line 224 of file xmmsv_bitbuffer.c.
Referenced by xmms_ipc_msg_write_transport(), and xmmsv_serialize().
xmmsv_t* xmmsv_bitbuffer_new (void)
Deprecated:
Definition at line 53 of file xmmsv_bitbuffer.c.
xmmsv_t* xmmsv_bitbuffer_new_ro (const unsigned char * v, int len)
Deprecated:
Definition at line 27 of file xmmsv_bitbuffer.c.
int xmmsv_bitbuffer_pos (xmmsv_t * v)
Definition at line 206 of file xmmsv_bitbuffer.c.
Referenced by xmms_ipc_msg_get_cmd(), xmms_ipc_msg_get_cookie(), xmms_ipc_msg_get_object(), xmms_ipc_msg_put_value(), xmmsv_bitbuffer_put_bits_at(), and xmmsv_copy().
int xmmsv_bitbuffer_put_bits (xmmsv_t * v, int bits, int64_t d)
Definition at line 120 of file xmmsv_bitbuffer.c.
Referenced by xmms_ipc_msg_set_cookie(), xmmsv_bitbuffer_put_bits_at(), and xmmsv_bitbuffer_put_data().
int xmmsv_bitbuffer_put_bits_at (xmmsv_t * v, int bits, int64_t d, int offset)
Definition at line 163 of file xmmsv_bitbuffer.c.
int xmmsv_bitbuffer_put_data (xmmsv_t * v, const unsigned char * b, int len)
Definition at line 175 of file xmmsv_bitbuffer.c.
Referenced by xmms_ipc_msg_alloc(), xmms_ipc_msg_read_transport(), and xmmsv_copy().
int xmmsv_bitbuffer_rewind (xmmsv_t * v)
Definition at line 212 of file xmmsv_bitbuffer.c.
int xmmsv_bitbuffer_serialize_value (xmmsv_t * bb, xmmsv_t * v)
Definition at line 637 of file value_serialize.c.
Referenced by xmms_ipc_msg_put_value(), and xmmsv_serialize().
int xmmsv_get_bitbuffer (const xmmsv_t * val, const unsigned char ** r, unsigned int * rlen)
Retrieves the bit buffer from the value.
Parameters
val a xmmsv_t containing a string.
r the return data. This data is owned by the value and will be freed when the value is freed.
rlen the return length of data.
Returns
1 upon success otherwise 0
Definition at line 245 of file xmmsv_bitbuffer.c.
xmmsv_t* xmmsv_new_bitbuffer (void)
Allocates a new empty bitbuffer xmmsv_t.
Returns
The new xmmsv_t. Must be unreferenced with xmmsv_unref.
Definition at line 64 of file xmmsv_bitbuffer.c.
Referenced by xmms_ipc_msg_alloc(), xmmsv_bitbuffer_new(), xmmsv_copy(), and xmmsv_serialize().
xmmsv_t* xmmsv_new_bitbuffer_ro (const unsigned char * v, int len)
Allocates a new bitbuffer xmmsv_t.
Returns
The new xmmsv_t. Must be unreferenced with xmmsv_unref.
Definition at line 38 of file xmmsv_bitbuffer.c.
Referenced by xmmsv_bitbuffer_new_ro(), and xmmsv_deserialize().