XMMS2: Transactions
Transactions
S4
Functions dealing with transactions.
Functions
void _transaction_writing (s4_transaction_t *trans)
s4_lock_t * _transaction_get_waiting_for (s4_transaction_t *trans)
void _transaction_set_waiting_for (s4_transaction_t *trans, s4_lock_t *waiting_for)
GList * _transaction_get_locks (s4_transaction_t *trans)
void _transaction_add_lock (s4_transaction_t *trans, s4_lock_t *lock)
void _transaction_set_deadlocked (s4_transaction_t *trans)
s4_transaction_t * _transaction_dummy_alloc (s4_t *s4)
void _transaction_dummy_free (s4_transaction_t *trans)
int _transaction_get_flags (s4_transaction_t *trans)
s4_transaction_t * s4_begin (s4_t *s4, int flags)
Starts a new transaction.
int s4_commit (s4_transaction_t *trans)
Commits a transaction.
int s4_abort (s4_transaction_t *trans)
Aborts a transaction.
s4_t * _transaction_get_db (s4_transaction_t *trans)
int s4_add (s4_transaction_t *trans, const char *key_a, const s4_val_t *val_a, const char *key_b, const s4_val_t *val_b, const char *src)
Adds a relationship to the database.
int s4_del (s4_transaction_t *trans, const char *key_a, const s4_val_t *val_a, const char *key_b, const s4_val_t *val_b, const char *src)
Deletes a relationship from the database.
s4_resultset_t * s4_query (s4_transaction_t *trans, s4_fetchspec_t *spec, s4_condition_t *cond)
Queries an S4 database.
Detailed Description
Functions dealing with transactions.
Function Documentation
void _transaction_add_lock (s4_transaction_t * trans, s4_lock_t * lock)
Definition at line 66 of file transaction.c.
Referenced by _lock_exclusive(), and _lock_shared().
s4_transaction_t* _transaction_dummy_alloc (s4_t * s4)
Definition at line 77 of file transaction.c.
void _transaction_dummy_free (s4_transaction_t * trans)
Definition at line 85 of file transaction.c.
s4_t* _transaction_get_db (s4_transaction_t * trans)
Definition at line 174 of file transaction.c.
Referenced by _oplist_get_db(), _s4_add(), _s4_del(), _s4_query(), s4_add(), s4_commit(), and s4_del().
int _transaction_get_flags (s4_transaction_t * trans)
Definition at line 92 of file transaction.c.
Referenced by _lock_shared().
GList* _transaction_get_locks (s4_transaction_t * trans)
Definition at line 61 of file transaction.c.
Referenced by _lock_unlock_all().
s4_lock_t* _transaction_get_waiting_for (s4_transaction_t * trans)
Definition at line 51 of file transaction.c.
void _transaction_set_deadlocked (s4_transaction_t * trans)
Definition at line 71 of file transaction.c.
Referenced by _s4_add(), _s4_del(), and _s4_query().
void _transaction_set_waiting_for (s4_transaction_t * trans, s4_lock_t * waiting_for)
Definition at line 56 of file transaction.c.
Referenced by _lock_exclusive(), and _lock_shared().
void _transaction_writing (s4_transaction_t * trans)
Definition at line 46 of file transaction.c.
int s4_abort (s4_transaction_t * trans)
Aborts a transaction.
The database will behave like the transaction never happened.
Parameters
trans The transaction
Returns
0 on error, non-zero on success.
Definition at line 165 of file transaction.c.
Referenced by CASE(), and xmms_medialib_session_abort().
int s4_add (s4_transaction_t * trans, const char * key_a, const s4_val_t * val_a, const char * key_b, const s4_val_t * val_b, const char * src)
Adds a relationship to the database.
It takes both a database handle and a transaction handle, but only one if used. If the transaction handle is NULL it will create a local transaction, otherwise it will use the transaction passed, and thus s4 is not needed.
Parameters
s4 The database to add to.
trans The transaction to use.
key_a Key A.
val_a Value A.
key_b Key B.
val_b Value B.
src Source.
Returns
0 on error, non-zero on success.
Definition at line 195 of file transaction.c.
Referenced by CASE(), main(), and xmms_medialib_session_property_set().
s4_transaction_t* s4_begin (s4_t * s4, int flags)
Starts a new transaction.
Parameters
s4 The database to run the transaction on.
flags Flags specifying what kind of transaction this should be.
Returns
A new transaction that can be used when calling s4_add, s4_del and s4_query.
Definition at line 105 of file transaction.c.
Referenced by CASE(), and main().
int s4_commit (s4_transaction_t * trans)
Commits a transaction.
On success the operations in the transactions will be applied in one atomic step, on error none of the operations in the transaction will be applied.
Parameters
trans The transaction to commit.
Returns
0 on error (and sets s4_errno), non-zero on success.
Definition at line 126 of file transaction.c.
Referenced by CASE(), main(), and xmms_medialib_session_commit().
int s4_del (s4_transaction_t * trans, const char * key_a, const s4_val_t * val_a, const char * key_b, const s4_val_t * val_b, const char * src)
Deletes a relationship from the database.
It takes both a database handle and a transaction handle, but only one if used. If the transaction handle is NULL it will create a local transaction, otherwise it will use the transaction passed, and thus s4 is not needed.
Parameters
s4 The database to delete from.
trans The transaction to use.
key_a Key A.
val_a Value A.
key_b Key B.
val_b Value B.
src Source.
Returns
0 on error, non-zero on success.
Definition at line 246 of file transaction.c.
Referenced by CASE(), main(), xmms_medialib_session_property_set(), and xmms_medialib_session_property_unset().
s4_resultset_t* s4_query (s4_transaction_t * trans, s4_fetchspec_t * spec, s4_condition_t * cond)
Queries an S4 database.
Parameters
s4 The database to query. If s4 is NULL trans must be non-null.
trans The transaction to use. If trans is NULL s4 must be non-null.
spec The fetchspecification to use when querying.
cond The condition to use when querying.
Returns
A resultset containing the fetched data.
Definition at line 290 of file transaction.c.
Referenced by CASE(), xmms_medialib_session_property_set(), and xmms_medialib_session_query().