XMMS2: Result Set
Result Set
S4
A set of results.
Functions
void s4_resultset_add_row (s4_resultset_t *set, const s4_resultrow_t *row)
Adds a row to a resultset.
int s4_resultset_get_row (const s4_resultset_t *set, int row_no, const s4_resultrow_t **row)
Gets a row from a resultset.
const s4_result_t * s4_resultset_get_result (const s4_resultset_t *set, int row, int col)
Gets a result from a resultset.
int s4_resultset_get_colcount (const s4_resultset_t *set)
Gets the column count for a resultset.
int s4_resultset_get_rowcount (const s4_resultset_t *set)
Gets the row count for a resultset.
void s4_resultset_sort (s4_resultset_t *set, s4_order_t *order)
Sorts a resultset.
void s4_resultset_shuffle (s4_resultset_t *set)
Shuffles the resultset into a pseudo-random order.
void s4_resultset_free (s4_resultset_t *set)
Frees a resultset and all the results in it.
s4_resultset_t * s4_resultset_ref (s4_resultset_t *set)
void s4_resultset_unref (s4_resultset_t *set)
s4_resultrow_t * s4_resultrow_create (int col_count)
Creates a new row.
void s4_resultrow_set_col (s4_resultrow_t *row, int col_no, s4_result_t *col)
Sets a column in a resultrow.
int s4_resultrow_get_col (const s4_resultrow_t *row, int col_no, const s4_result_t **col)
Gets the value of a column in a resultrow.
s4_resultrow_t * s4_resultrow_ref (s4_resultrow_t *row)
References a resultrow.
void s4_resultrow_unref (s4_resultrow_t *row)
Unreferences a resultrow.
s4_order_t * s4_order_create (void)
s4_order_entry_t * s4_order_add_column (s4_order_t *order, s4_cmp_mode_t collation, s4_order_direction_t direction)
s4_order_entry_t * s4_order_add_random (s4_order_t *order, int seed)
void s4_order_entry_add_choice (s4_order_entry_t *entry, int column)
void s4_order_free (s4_order_t *order)
s4_resultset_t * s4_resultset_create (int col_count)
Creates a new resultset.
Detailed Description
A set of results.
Function Documentation
s4_order_entry_t* s4_order_add_column (s4_order_t * order, s4_cmp_mode_t collation, s4_order_direction_t direction)
Definition at line 365 of file resultset.c.
s4_order_entry_t* s4_order_add_random (s4_order_t * order, int seed)
Definition at line 375 of file resultset.c.
s4_order_t* s4_order_create (void)
Definition at line 357 of file resultset.c.
void s4_order_entry_add_choice (s4_order_entry_t * entry, int column)
Definition at line 384 of file resultset.c.
void s4_order_free (s4_order_t * order)
Definition at line 392 of file resultset.c.
s4_resultrow_t* s4_resultrow_create (int col_count)
Creates a new row.
Parameters
col_count The number of columns in the row
Returns
A new resultrow
Definition at line 259 of file resultset.c.
int s4_resultrow_get_col (const s4_resultrow_t * row, int col_no, const s4_result_t ** col)
Gets the value of a column in a resultrow.
Parameters
row The row to get the column from
col_no The index of the column to get
col A pointer to where the column will be saved
Returns
0 if col_no is out of bounds or the column is NULL, 1 otherwise
Definition at line 295 of file resultset.c.
s4_resultrow_t* s4_resultrow_ref (s4_resultrow_t * row)
References a resultrow.
Parameters
row The row to reference
Definition at line 308 of file resultset.c.
Referenced by s4_resultset_add_row().
void s4_resultrow_set_col (s4_resultrow_t * row, int col_no, s4_result_t * col)
Sets a column in a resultrow.
Parameters
row The row to set the column in
col_no The index of the column to set
col The new value of the column
Definition at line 280 of file resultset.c.
void s4_resultrow_unref (s4_resultrow_t * row)
Unreferences a resultrow.
If the refcount hits 0 the row will be freed
Parameters
row The row to unrefperence
Definition at line 319 of file resultset.c.
Referenced by s4_resultset_create().
void s4_resultset_add_row (s4_resultset_t * set, const s4_resultrow_t * row)
Adds a row to a resultset.
Parameters
set The resultset to add to
row The row to add
Definition at line 100 of file resultset.c.
Referenced by _s4_query().
s4_resultset_t* s4_resultset_create (int col_count)
Creates a new resultset.
Parameters
col_count The number of columns in every result
Returns
A new resultset with the column count set to col_count
Definition at line 78 of file resultset.c.
Referenced by _s4_query(), and s4_query().
void s4_resultset_free (s4_resultset_t * set)
Frees a resultset and all the results in it.
Parameters
set The set to free
Definition at line 230 of file resultset.c.
Referenced by CASE(), s4_resultset_unref(), xmms_medialib_entry_cleanup(), xmms_medialib_entry_not_resolved_get(), xmms_medialib_entry_remove(), xmms_medialib_num_not_resolved(), xmms_medialib_query(), xmms_medialib_query_to_xmmsv(), and xmms_medialib_session_property_set().
int s4_resultset_get_colcount (const s4_resultset_t * set)
Gets the column count for a resultset.
Parameters
set The set to find the column count of
Returns
The column count
Definition at line 146 of file resultset.c.
Referenced by CASE(), find_column(), and print_result().
const s4_result_t* s4_resultset_get_result (const s4_resultset_t * set, int row, int col)
Gets a result from a resultset.
Parameters
set The set to get the result from
row The row
col The column
Returns
The result at (row,col), or NULL if it does not exist
Definition at line 130 of file resultset.c.
Referenced by CASE(), print_result(), xmms_medialib_entry_cleanup(), xmms_medialib_entry_not_resolved_get(), xmms_medialib_entry_remove(), and xmms_medialib_session_property_set().
int s4_resultset_get_row (const s4_resultset_t * set, int row_no, const s4_resultrow_t ** row)
Gets a row from a resultset.
Parameters
set The resultset to get the row from
row_no The index of the row to fetch
row A pointer to where the row will be saved
Returns
0 if row_no was out of bounds, 1 otherwise
Definition at line 114 of file resultset.c.
int s4_resultset_get_rowcount (const s4_resultset_t * set)
Gets the row count for a resultset.
Parameters
set The set to find the row count of
Returns
The row count
Definition at line 156 of file resultset.c.
Referenced by CASE(), print_result(), xmms_medialib_entry_cleanup(), xmms_medialib_entry_remove(), xmms_medialib_num_not_resolved(), and xmms_medialib_query_to_xmmsv().
s4_resultset_t* s4_resultset_ref (s4_resultset_t * set)
Definition at line 236 of file resultset.c.
void s4_resultset_shuffle (s4_resultset_t * set)
Shuffles the resultset into a pseudo-random order.
Parameters
set The resultset to shuffle
Definition at line 221 of file resultset.c.
void s4_resultset_sort (s4_resultset_t * set, s4_order_t * order)
Sorts a resultset.
Parameters
set The set to sort
order The columns to order the result by
Definition at line 210 of file resultset.c.
void s4_resultset_unref (s4_resultset_t * set)
Definition at line 243 of file resultset.c.