XMMS2: Condition
Condition
S4
Functions to create and use S4 search conditions.
Functions
s4_condition_t * s4_cond_new_combiner (s4_combine_type_t type)
Creates a new combiner.
s4_condition_t * s4_cond_new_custom_combiner (combine_function_t func)
Creates a new combiner with a user specified combiner function.
void s4_cond_add_operand (s4_condition_t *cond, s4_condition_t *operand)
Adds and references an operand to a combiner condition.
s4_condition_t * s4_cond_get_operand (s4_condition_t *cond, int operand)
Gets an operand from a combiner condition.
s4_condition_t * s4_cond_new_filter (s4_filter_type_t type, const char *key, const s4_val_t *value, s4_sourcepref_t *sourcepref, s4_cmp_mode_t cmp_mode, int flags)
Creates a new filter condition.
s4_condition_t * s4_cond_new_custom_filter (filter_function_t func, void *userdata, free_func_t free, const char *key, s4_sourcepref_t *sourcepref, s4_cmp_mode_t cmp_mode, int monotonic, int flags)
Creates a new filter condition with a user specified filter function.
int s4_cond_is_filter (s4_condition_t *cond)
Checks if this condition is a filter condition.
int s4_cond_is_combiner (s4_condition_t *cond)
Checks if this condition is a combiner condition.
s4_filter_type_t s4_cond_get_filter_type (s4_condition_t *cond)
s4_combine_type_t s4_cond_get_combiner_type (s4_condition_t *cond)
int s4_cond_get_flags (s4_condition_t *cond)
Gets the flags for a condition.
const char * s4_cond_get_key (s4_condition_t *cond)
Gets the key for a condition.
s4_sourcepref_t * s4_cond_get_sourcepref (s4_condition_t *cond)
Gets the source preference that should be used.
void * s4_cond_get_funcdata (s4_condition_t *cond)
Returns the data that should be fed to the filter function.
void s4_cond_free (s4_condition_t *cond)
Frees a condition and operands recursively.
s4_condition_t * s4_cond_ref (s4_condition_t *cond)
Increments the reference count of a condition.
void s4_cond_unref (s4_condition_t *cond)
Decrements the reference count of a condition.
filter_function_t s4_cond_get_filter_function (s4_condition_t *cond)
Gets the filter function for the condition.
combine_function_t s4_cond_get_combine_function (s4_condition_t *cond)
Gets the combine function for the condition.
int s4_cond_is_monotonic (s4_condition_t *cond)
Checks if the condition is a monotonic filter.
int s4_cond_get_cmp_mode (s4_condition_t *cond)
Gets the comparison mode used by the filter condition.
void s4_cond_update_key (s4_condition_t *cond, s4_t *s4)
Change the key with a constant key for faster checking.
Detailed Description
Functions to create and use S4 search conditions.
Function Documentation
void s4_cond_add_operand (s4_condition_t * cond, s4_condition_t * operand)
Adds and references an operand to a combiner condition.
Parameters
cond The condition to add to
operand The operand to add
Definition at line 383 of file cond.c.
Referenced by CASE().
void s4_cond_free (s4_condition_t * cond)
Frees a condition and operands recursively.
Parameters
cond The condition to free
Definition at line 573 of file cond.c.
Referenced by CASE(), s4_cond_unref(), xmms_medialib_query_recurs(), and xmms_medialib_session_property_set().
int s4_cond_get_cmp_mode (s4_condition_t * cond)
Gets the comparison mode used by the filter condition.
Parameters
cond The condition to check
Returns
The comparison mode used
Definition at line 663 of file cond.c.
combine_function_t s4_cond_get_combine_function (s4_condition_t * cond)
Gets the combine function for the condition.
This function does not check if the condition is actually a combine condition, if it's called on a condition that is not a combiner it will return bogus data
Parameters
cond The condition to get the combine function of
Returns
The combine function
Definition at line 639 of file cond.c.
s4_combine_type_t s4_cond_get_combiner_type (s4_condition_t * cond)
Definition at line 519 of file cond.c.
Referenced by print_cond().
filter_function_t s4_cond_get_filter_function (s4_condition_t * cond)
Gets the filter function for the condition.
This function does not check if the condition is actually a filter condition, if it is called on a condition that is not a filter it will return bogus data
Parameters
cond The condition to get the filter function of
Returns
The filter function
Definition at line 626 of file cond.c.
Referenced by _s4_query(), and CASE().
s4_filter_type_t s4_cond_get_filter_type (s4_condition_t * cond)
Definition at line 514 of file cond.c.
Referenced by print_cond().
int s4_cond_get_flags (s4_condition_t * cond)
Gets the flags for a condition.
Parameters
cond The condition to get the flags of
Returns
The flags
Definition at line 530 of file cond.c.
Referenced by _s4_query().
void* s4_cond_get_funcdata (s4_condition_t * cond)
Returns the data that should be fed to the filter function.
Parameters
cond The condition to get the function data of
Returns
The function data
Definition at line 563 of file cond.c.
Referenced by print_cond().
const char* s4_cond_get_key (s4_condition_t * cond)
Gets the key for a condition.
Parameters
cond The condition to get the key of
Returns
The key
Definition at line 541 of file cond.c.
Referenced by _s4_query(), and print_cond().
s4_condition_t* s4_cond_get_operand (s4_condition_t * cond, int operand)
Gets an operand from a combiner condition.
Parameters
cond The condition to get the operand from
operand The index of the operand to get
Returns
The operand, or NULL if the index is out of bounds or cond is not a combiner condition. The reference is still held by cond, so you must not call s4_cond_unref on the returned condition.
Definition at line 400 of file cond.c.
Referenced by print_cond().
s4_sourcepref_t* s4_cond_get_sourcepref (s4_condition_t * cond)
Gets the source preference that should be used.
Parameters
cond The condition to get the source preference of
Returns
The source preference
Definition at line 552 of file cond.c.
int s4_cond_is_combiner (s4_condition_t * cond)
Checks if this condition is a combiner condition.
Parameters
cond The condition to check
Returns
non-zero if the condition is a combiner, 0 otherwise
Definition at line 509 of file cond.c.
int s4_cond_is_filter (s4_condition_t * cond)
Checks if this condition is a filter condition.
Parameters
cond The condition to check
Returns
non-zero if the condition is a filter, 0 otherwise
Definition at line 498 of file cond.c.
Referenced by _s4_query(), and print_cond().
int s4_cond_is_monotonic (s4_condition_t * cond)
Checks if the condition is a monotonic filter.
A monotonic filter is a filter that preserves the order, and it can thus be used to search in an index.
Parameters
cond The condition to check
Returns
non-zero if the condition is monotonic, 0 otherwise
Definition at line 652 of file cond.c.
Referenced by _s4_query().
s4_condition_t* s4_cond_new_combiner (s4_combine_type_t type)
Creates a new combiner.
Parameters
type The combiner type
Returns
A new combiner
Definition at line 345 of file cond.c.
s4_condition_t* s4_cond_new_custom_combiner (combine_function_t func)
Creates a new combiner with a user specified combiner function.
Parameters
func The combiner function to use
Returns
A new custom combiner
Definition at line 364 of file cond.c.
Referenced by CASE().
s4_condition_t* s4_cond_new_custom_filter (filter_function_t func, void * userdata, free_func_t free, const char * key, s4_sourcepref_t * sourcepref, s4_cmp_mode_t cmp_mode, int monotonic, int flags)
Creates a new filter condition with a user specified filter function.
The filter function should return 0 if the value meets the condition, non-zero otherwise.
Parameters
func The filter function to use
userdata The data that will be passed to the function along with the value to check
free The function that should be called to free userdata
key The key the condition should check
sourcepref The source preference
cmp_mode The comparison mode to use
flags Condition flags, or 0
Returns
A new custom filter condition
Definition at line 465 of file cond.c.
Referenced by CASE().
s4_condition_t* s4_cond_new_filter (s4_filter_type_t type, const char * key, const s4_val_t * value, s4_sourcepref_t * sourcepref, s4_cmp_mode_t cmp_mode, int flags)
Creates a new filter condition.
Parameters
type The type of the filter
key The key the condition should check
value The value to check against
sourcepref The source preference
cmp_mode The comparison mode to use
flags Condition flags, or 0
Returns
A new filter condition
Definition at line 424 of file cond.c.
Referenced by CASE(), and xmms_medialib_session_property_set().
s4_condition_t* s4_cond_ref (s4_condition_t * cond)
Increments the reference count of a condition.
Parameters
cond The condition to reference
Returns
The condition given
Definition at line 594 of file cond.c.
Referenced by s4_cond_add_operand().
void s4_cond_unref (s4_condition_t * cond)
Decrements the reference count of a condition.
If the reference count is 0 after this, the condition is freed.
Parameters
cond The condition to decrement the count of
Definition at line 606 of file cond.c.
Referenced by CASE(), s4_cond_new_combiner(), and s4_cond_new_custom_combiner().
void s4_cond_update_key (s4_condition_t * cond, s4_t * s4)
Change the key with a constant key for faster checking.
Parameters
s4 The database to optimize for
cond The condition to update
Definition at line 674 of file cond.c.
Referenced by _s4_query().