XMMS2: Log
Log
S4
Logs every action so we can redo changes if something crashes.
Macros
#define LOG_SIZE (2*1024*1024)
Enumerations
enum log_type_t {
LOG_ENTRY_ADD = 0xaddadd, LOG_ENTRY_DEL = 0xde1e7e, LOG_ENTRY_WRAP = 0x123123, LOG_ENTRY_INIT = 0x87654321,
LOG_ENTRY_BEGIN = 0x1, LOG_ENTRY_END = 0x2, LOG_ENTRY_WRITING = 0x3, LOG_ENTRY_CHECKPOINT = 0x4
}
Functions
s4_log_data_t * _log_create_data ()
void _log_free_data (s4_log_data_t *data)
void _log_checkpoint (s4_t *s4)
Writes a checkpoint entry to the log, marking that the database has finished being written to disk.
int _log_write (oplist_t *list)
Writes all the operations in an oplist to disk.
int _log_open (s4_t *s4)
Opens a log file.
int _log_close (s4_t *s4)
Closes the log file.
void _log_lock_file (s4_t *s4)
Locks the log file.
void _log_unlock_file (s4_t *s4)
Unlocks the log file.
void _log_lock_db (s4_t *s4)
Locks the database file.
void _log_unlock_db (s4_t *s4)
Unlocks the database file.
log_number_t _log_last_synced (s4_t *s4)
void _log_init (s4_t *s4, log_number_t last_checkpoint)
Detailed Description
Logs every action so we can redo changes if something crashes.
Macro Definition Documentation
#define LOG_SIZE (2*1024*1024)
Definition at line 47 of file log.c.
Enumeration Type Documentation
enum log_type_t
Enumerator
LOG_ENTRY_ADD
LOG_ENTRY_DEL
LOG_ENTRY_WRAP
LOG_ENTRY_INIT
LOG_ENTRY_BEGIN
LOG_ENTRY_END
LOG_ENTRY_WRITING
LOG_ENTRY_CHECKPOINT
Definition at line 36 of file log.c.
Function Documentation
void _log_checkpoint (s4_t * s4)
Writes a checkpoint entry to the log, marking that the database has finished being written to disk.
Parameters
s4 The database to write the log entry to.
Definition at line 320 of file log.c.
int _log_close (s4_t * s4)
Closes the log file.
Parameters
s4 The database to close the logfile of.
Returns
0 on error, non-zero on success.
Definition at line 688 of file log.c.
Referenced by s4_close().
s4_log_data_t* _log_create_data (void)
Definition at line 73 of file log.c.
void _log_free_data (s4_log_data_t * data)
Definition at line 82 of file log.c.
void _log_init (s4_t * s4, log_number_t last_checkpoint)
Definition at line 764 of file log.c.
log_number_t _log_last_synced (s4_t * s4)
Definition at line 759 of file log.c.
void _log_lock_db (s4_t * s4)
Locks the database file.
This is actually a lock set on the log file.
Parameters
s4 The database to log.
Definition at line 744 of file log.c.
void _log_lock_file (s4_t * s4)
Locks the log file.
It will redo everything new in the log.
Parameters
s4 The database to lock the log of.
Definition at line 701 of file log.c.
Referenced by s4_begin().
int _log_open (s4_t * s4)
Opens a log file.
Parameters
s4 The database to open the logfile for
Returns
0 on error, non-zero otherwise
Definition at line 663 of file log.c.
Referenced by s4_open().
void _log_unlock_db (s4_t * s4)
Unlocks the database file.
Parameters
s4 The database to unlock.
Definition at line 754 of file log.c.
void _log_unlock_file (s4_t * s4)
Unlocks the log file.
Parameters
s4 The database to unlock the log of.
Definition at line 720 of file log.c.
Referenced by s4_commit().
int _log_write (oplist_t * list)
Writes all the operations in an oplist to disk.
Parameters
list The oplist to write.
Returns
0 on error, non-zero on success.
Definition at line 350 of file log.c.
Referenced by s4_commit().