XMMS2: Dictionaries
Dictionaries
The type xmmsv_t
Modules
Iteration
Macros
#define xmmsv_dict_entry_get_int xmmsv_dict_entry_get_int32
#define xmmsv_dict_iter_pair_int xmmsv_dict_iter_pair_int32
Functions
xmmsv_t * xmmsv_new_dict (void)
Allocates a new dict xmmsv_t.
int xmmsv_dict_get (xmmsv_t *dictv, const char *key, xmmsv_t **val)
Get the element corresponding to the given key in the dict xmmsv_t (if it exists).
int xmmsv_dict_set (xmmsv_t *dictv, const char *key, xmmsv_t *val)
Insert an element under the given key in the dict xmmsv_t.
int xmmsv_dict_remove (xmmsv_t *dictv, const char *key)
Remove the element corresponding to a given key in the dict xmmsv_t (if it exists).
int xmmsv_dict_clear (xmmsv_t *dictv)
Empty the dict of all its elements.
int xmmsv_dict_get_size (xmmsv_t *dictv)
Return the size of the dict.
int xmmsv_dict_has_key (xmmsv_t *dictv, const char *key)
int xmmsv_dict_entry_get_string (xmmsv_t *val, const char *key, const char **r)
int xmmsv_dict_entry_get_int32 (xmmsv_t *val, const char *key, int32_t *r)
int xmmsv_dict_entry_get_int64 (xmmsv_t *val, const char *key, int64_t *r)
int xmmsv_dict_entry_get_float (xmmsv_t *val, const char *key, float *r)
int xmmsv_dict_entry_get_coll (xmmsv_t *val, const char *key, xmmsv_t **coll)
int xmmsv_dict_set_string (xmmsv_t *val, const char *key, const char *el)
int xmmsv_dict_set_int (xmmsv_t *val, const char *key, int64_t el)
int xmmsv_dict_set_float (xmmsv_t *val, const char *key, float el)
int xmmsv_dict_set_coll (xmmsv_t *val, const char *key, xmmsv_t *el)
xmmsv_type_t xmmsv_dict_entry_get_type (xmmsv_t *val, const char *key)
Gets the type of a dict entry.
Detailed Description
Macro Definition Documentation
#define xmmsv_dict_entry_get_int xmmsv_dict_entry_get_int32
Definition at line 91 of file xmmsv_dict.h.
Referenced by xmmsv_coll_attribute_get_int32(), and xmmsv_coll_attribute_get_int64().
#define xmmsv_dict_iter_pair_int xmmsv_dict_iter_pair_int32
Definition at line 92 of file xmmsv_dict.h.
Function Documentation
int xmmsv_dict_clear (xmmsv_t * dictv)
Empty the dict of all its elements.
Parameters
dictv A xmmsv_t containing a dict.
Returns
1 upon success otherwise 0
Definition at line 416 of file xmmsv_dict.c.
int xmmsv_dict_entry_get_coll (xmmsv_t * val, const char * key, xmmsv_t ** coll)
Definition at line 723 of file xmmsv_dict.c.
int xmmsv_dict_entry_get_float (xmmsv_t * val, const char * key, float * r)
Definition at line 720 of file xmmsv_dict.c.
int xmmsv_dict_entry_get_int32 (xmmsv_t * val, const char * key, int32_t * r)
Definition at line 718 of file xmmsv_dict.c.
int xmmsv_dict_entry_get_int64 (xmmsv_t * val, const char * key, int64_t * r)
Definition at line 719 of file xmmsv_dict.c.
int xmmsv_dict_entry_get_string (xmmsv_t * val, const char * key, const char ** r)
Definition at line 717 of file xmmsv_dict.c.
Referenced by xmms_fetch_spec_new(), and xmmsv_coll_attribute_get_string().
xmmsv_type_t xmmsv_dict_entry_get_type (xmmsv_t * val, const char * key)
Gets the type of a dict entry.
Parameters
val A xmmsv_t containing a dict.
key The key in the dict.
Returns
The type of the entry or XMMSV_TYPE_NONE if something goes wrong.
Definition at line 288 of file xmmsv_dict.c.
Referenced by xmms_fetch_spec_new().
int xmmsv_dict_get (xmmsv_t * dictv, const char * key, xmmsv_t ** val)
Get the element corresponding to the given key in the dict xmmsv_t (if it exists).
This function does not increase the refcount of the element, the reference is still owned by the dict.
Parameters
dictv A xmmsv_t containing a dict.
key The key in the dict.
val Pointer set to a borrowed reference to the element corresponding to the given key in the dict.
Returns
1 upon success otherwise 0
Definition at line 311 of file xmmsv_dict.c.
Referenced by xmms_collection_restore(), xmmsv_coll_attribute_get_value(), xmmsv_dict_entry_get_coll(), xmmsv_dict_entry_get_type(), and xmmsv_dict_has_key().
int xmmsv_dict_get_size (xmmsv_t * dictv)
Return the size of the dict.
Parameters
dictv The xmmsv_t containing the dict.
Returns
The size of the dict, or -1 if dict is invalid.
Definition at line 477 of file xmmsv_dict.c.
int xmmsv_dict_has_key (xmmsv_t * dictv, const char * key)
Definition at line 275 of file xmmsv_dict.c.
int xmmsv_dict_remove (xmmsv_t * dictv, const char * key)
Remove the element corresponding to a given key in the dict xmmsv_t (if it exists).
Parameters
dictv A xmmsv_t containing a dict.
key The key in the dict.
Returns
1 upon success otherwise 0
Definition at line 387 of file xmmsv_dict.c.
Referenced by xmmsv_coll_attribute_remove().
int xmmsv_dict_set (xmmsv_t * dictv, const char * key, xmmsv_t * val)
Insert an element under the given key in the dict xmmsv_t.
If the key already referenced an element, that element is unref'd and replaced by the new one.
Parameters
dictv A xmmsv_t containing a dict.
key The key in the dict.
val The new element to insert in the dict.
Returns
1 upon success otherwise 0
Definition at line 354 of file xmmsv_dict.c.
Referenced by xmms_collection_snapshot(), xmms_medialib_query_to_xmmsv(), xmms_xform_browse_add_entry_property(), xmmsv_build_cluster_dict(), xmmsv_build_cluster_list(), xmmsv_build_dict_va(), xmmsv_build_metadata(), xmmsv_build_organize(), xmmsv_coll_attribute_set_value(), xmmsv_dict_set_coll(), xmmsv_propdict_to_dict(), and xmmsv_sc_argument_new().
int xmmsv_dict_set_coll (xmmsv_t * val, const char * key, xmmsv_t * el)
Definition at line 748 of file xmmsv_dict.c.
int xmmsv_dict_set_float (xmmsv_t * val, const char * key, float el)
Definition at line 745 of file xmmsv_dict.c.
int xmmsv_dict_set_int (xmmsv_t * val, const char * key, int64_t el)
Definition at line 744 of file xmmsv_dict.c.
Referenced by xmms_playlist_add_entry_unlocked(), xmms_playlist_insert_entry(), xmmsv_coll_attribute_set_int(), and xmmsv_sc_argument_new().
int xmmsv_dict_set_string (xmmsv_t * val, const char * key, const char * el)
Definition at line 743 of file xmmsv_dict.c.
Referenced by xmms_collection_snapshot(), xmms_fetch_spec_new(), xmmsv_build_cluster_dict(), xmmsv_build_cluster_list(), xmmsv_build_count(), xmmsv_build_metadata(), xmmsv_build_organize(), xmmsv_coll_attribute_set_string(), and xmmsv_sc_argument_new().
xmmsv_t* xmmsv_new_dict (void)
Allocates a new dict xmmsv_t.
Returns
The new xmmsv_t. Must be unreferenced with xmmsv_unref.
Definition at line 263 of file xmmsv_dict.c.
Referenced by xmms_collection_snapshot(), xmms_medialib_query_to_xmmsv(), xmms_xform_browse_add_entry(), xmmsv_build_cluster_dict(), xmmsv_build_cluster_list(), xmmsv_build_count(), xmmsv_build_dict_va(), xmmsv_build_metadata(), xmmsv_build_organize(), xmmsv_propdict_to_dict(), and xmmsv_sc_argument_new().