XMMS2: Entry
Entry
S4
The in-memory database.
Functions
int _s4_add (s4_transaction_t *trans, const char *key_a, const s4_val_t *val_a, const char *key_b, const s4_val_t *val_b, const char *src)
Adds a new relation to a database.
int _s4_add_internal (s4_t *s4, const char *key_a, const s4_val_t *value_a, const char *key_b, const s4_val_t *value_b, const char *src)
int _s4_del (s4_transaction_t *trans, const char *key_a, const s4_val_t *val_a, const char *key_b, const s4_val_t *val_b, const char *src)
Deletes a relation from a database.
s4_resultset_t * _s4_query (s4_transaction_t *trans, s4_fetchspec_t *fs, s4_condition_t *cond)
Queries a database for all entries matching a condition, then fetches data from them.
s4_entry_data_t * _entry_create_data ()
void _entry_free_data (s4_entry_data_t *data)
void _free_relations (s4_t *s4)
Frees all relations in a database.
Detailed Description
The in-memory database.
Function Documentation
s4_entry_data_t* _entry_create_data (void)
Definition at line 55 of file relation.c.
Referenced by _reread_file().
void _entry_free_data (s4_entry_data_t * data)
Definition at line 62 of file relation.c.
Referenced by _reread_file().
void _free_relations (s4_t * s4)
Frees all relations in a database.
Parameters
s4 The database to free in
Definition at line 366 of file relation.c.
Referenced by _reread_file().
int _s4_add (s4_transaction_t * trans, const char * key_a, const s4_val_t * val_a, const char * key_b, const s4_val_t * val_b, const char * src)
Adds a new relation to a database.
Parameters
s4 The database to add to
key_a The key of the first entry
val_a The value of the first entry
key_b The key of the second entry
val_b The value of the second entry
src The source that made the relation
Returns
non-zero if everything went alrite, 0 otherwise
Definition at line 204 of file relation.c.
Referenced by _oplist_execute(), _oplist_rollback(), and s4_add().
int _s4_add_internal (s4_t * s4, const char * key_a, const s4_val_t * value_a, const char * key_b, const s4_val_t * value_b, const char * src)
Definition at line 251 of file relation.c.
int _s4_del (s4_transaction_t * trans, const char * key_a, const s4_val_t * val_a, const char * key_b, const s4_val_t * val_b, const char * src)
Deletes a relation from a database.
Parameters
s4 The database to delete from
key_a The key of the first entry
val_a The value of the first entry
key_b The key of the second entry
val_b The value of the second entry
src The source that made the relation
Returns
non-zero if everything went alrite, 0 otherwise
Definition at line 303 of file relation.c.
Referenced by _oplist_execute(), _oplist_rollback(), and s4_del().
s4_resultset_t* _s4_query (s4_transaction_t * trans, s4_fetchspec_t * fs, s4_condition_t * cond)
Queries a database for all entries matching a condition, then fetches data from them.
Parameters
trans The transaction this query belongs to.
fs The fetchspec to use when fetching data
cond The condition to check entries against
Returns
A resultset with a row for every entry that matched
Definition at line 520 of file relation.c.
Referenced by s4_query().