XMMS2: Lock
Lock
S4
Locks entries so only one transaction can use tham at a time.
Functions
s4_lock_t * _lock_alloc ()
void _lock_free (s4_lock_t *lock)
int _lock_exclusive (s4_lock_t *lock, s4_transaction_t *trans)
int _lock_shared (s4_lock_t *lock, s4_transaction_t *trans)
void _lock_unlock_all (s4_transaction_t *trans)
Detailed Description
Locks entries so only one transaction can use tham at a time.
Locks can be locked in three ways, read-only, upgradable and exclusive.
Read-only is for read-only transactions that know they will not want an exclusive version of the lock later one
Upgradable is for transactions that might want to upgrade it to an exclusive lock later on.
Exclusive locks can only be held by one transaction.
Function Documentation
s4_lock_t* _lock_alloc (void)
Definition at line 44 of file lock.c.
Referenced by _index_create().
int _lock_exclusive (s4_lock_t * lock, s4_transaction_t * trans)
Definition at line 147 of file lock.c.
Referenced by _index_lock_exclusive().
void _lock_free (s4_lock_t * lock)
Definition at line 56 of file lock.c.
Referenced by _free_relations(), and _index_free().
int _lock_shared (s4_lock_t * lock, s4_transaction_t * trans)
Definition at line 190 of file lock.c.
Referenced by _index_lock_shared().
void _lock_unlock_all (s4_transaction_t * trans)
Definition at line 258 of file lock.c.
Referenced by _transaction_dummy_free().