XMMS2: IPC
IPC
XMMSServer
IPC functions for XMMS2 Daemon.
Typedefs
typedef struct
xmms_ipc_object_pool_t xmms_ipc_object_pool_t
The IPC object list.
typedef struct xmms_ipc_client_St xmms_ipc_client_t
A IPC client representation.
Functions
void on_config_ipcsocket_change (xmms_object_t *object, xmmsv_t *_data, gpointer udata)
Gets called when the config property "core.ipcsocket" has changed.
void xmms_ipc_send_broadcast (guint broadcastid, gint32 clientid, xmmsv_t *arg, xmms_error_t *err)
Format and send a broadcast to a single client.
void xmms_ipc_send_message (gint32 clientid, xmms_ipc_msg_t *msg, xmms_error_t *err)
Send an ipc message to a client.
gboolean xmms_ipc_has_pending (guint signalid)
Checks if someone is waiting for signalid.
xmms_ipc_manager_t * xmms_ipc_manager_get ()
Get the ipc_manager object.
void xmms_ipc_broadcast_register (xmms_object_t *object, xmms_ipc_signal_t signalid)
Register a broadcast signal.
void xmms_ipc_broadcast_unregister (xmms_ipc_signal_t signalid)
Unregister a broadcast signal.
void xmms_ipc_signal_register (xmms_object_t *object, xmms_ipc_signal_t signalid)
Register a signal.
void xmms_ipc_signal_unregister (xmms_ipc_signal_t signalid)
Unregister a signal.
void xmms_ipc_object_register (xmms_ipc_object_t objectid, xmms_object_t *object)
Register a object to the IPC core.
void xmms_ipc_object_unregister (xmms_ipc_object_t objectid)
Remove a object from the IPC core.
xmms_ipc_t * xmms_ipc_init (void)
Initialize IPC.
void xmms_ipc_shutdown (void)
Disable IPC.
gboolean xmms_ipc_setup_server (const gchar *path)
Start the server.
Detailed Description
IPC functions for XMMS2 Daemon.
Typedef Documentation
typedef struct xmms_ipc_client_St xmms_ipc_client_t
A IPC client representation.
typedef struct xmms_ipc_object_pool_t xmms_ipc_object_pool_t
The IPC object list.
Function Documentation
void on_config_ipcsocket_change (xmms_object_t * object, xmmsv_t * _data, gpointer udata)
Gets called when the config property "core.ipcsocket" has changed.
Definition at line 464 of file ipc.c.
Referenced by main().
void xmms_ipc_broadcast_register (xmms_object_t * object, xmms_ipc_signal_t signalid)
Register a broadcast signal.
Definition at line 783 of file ipc.c.
void xmms_ipc_broadcast_unregister (xmms_ipc_signal_t signalid)
Unregister a broadcast signal.
Definition at line 798 of file ipc.c.
gboolean xmms_ipc_has_pending (guint signalid)
Checks if someone is waiting for signalid.
Definition at line 679 of file ipc.c.
xmms_ipc_t* xmms_ipc_init (void)
Initialize IPC.
Definition at line 869 of file ipc.c.
Referenced by main().
xmms_ipc_manager_t* xmms_ipc_manager_get (void)
Get the ipc_manager object.
Definition at line 774 of file ipc.c.
Referenced by xmms_courier_init().
void xmms_ipc_object_register (xmms_ipc_object_t objectid, xmms_object_t * object)
Register a object to the IPC core.
This needs to be done if you want to send commands to that object from the client.
Definition at line 847 of file ipc.c.
void xmms_ipc_object_unregister (xmms_ipc_object_t objectid)
Remove a object from the IPC core.
Definition at line 858 of file ipc.c.
void xmms_ipc_send_broadcast (guint broadcastid, gint32 clientid, xmmsv_t * arg, xmms_error_t * err)
Format and send a broadcast to a single client.
Definition at line 479 of file ipc.c.
void xmms_ipc_send_message (gint32 clientid, xmms_ipc_msg_t * msg, xmms_error_t * err)
Send an ipc message to a client.
Definition at line 506 of file ipc.c.
gboolean xmms_ipc_setup_server (const gchar * path)
Start the server.
Definition at line 949 of file ipc.c.
Referenced by main(), and on_config_ipcsocket_change().
void xmms_ipc_shutdown (void)
Disable IPC.
Definition at line 914 of file ipc.c.
Referenced by main().
void xmms_ipc_signal_register (xmms_object_t * object, xmms_ipc_signal_t signalid)
Register a signal.
Definition at line 815 of file ipc.c.
void xmms_ipc_signal_unregister (xmms_ipc_signal_t signalid)
Unregister a signal.
Definition at line 829 of file ipc.c.