XMMS2: Easier building of lists and dictionaries
Easier building of lists and dictionaries
The type xmmsv_t
Macros
#define XMMSV_DICT_ENTRY(k, v) __xmmsv_identity_const_charp (k), __xmmsv_identity_xmmsv (v)
#define XMMSV_DICT_ENTRY_STR(k, v) XMMSV_DICT_ENTRY (k, __xmmsv_null_to_none (xmmsv_new_string (v)))
#define XMMSV_DICT_ENTRY_INT(k, v) XMMSV_DICT_ENTRY (k, xmmsv_new_int (v))
#define XMMSV_DICT_ENTRY_FLOAT(k, v) XMMSV_DICT_ENTRY (k, xmmsv_new_float (v))
#define XMMSV_DICT_END NULL
#define XMMSV_LIST_ENTRY(v) __xmmsv_identity_xmmsv (v)
#define XMMSV_LIST_ENTRY_STR(v) XMMSV_LIST_ENTRY (__xmmsv_null_to_none (xmmsv_new_string (v)))
#define XMMSV_LIST_ENTRY_INT(v) XMMSV_LIST_ENTRY (xmmsv_new_int (v))
#define XMMSV_LIST_ENTRY_FLOAT(v) XMMSV_LIST_ENTRY (xmmsv_new_float (v))
#define XMMSV_LIST_ENTRY_COLL(v) XMMSV_LIST_ENTRY (__xmmsv_null_to_none (xmmsv_new_coll (v)))
#define XMMSV_LIST_END NULL
Functions
xmmsv_t * xmmsv_make_stringlist (char *array[], int num)
Helper function to build a list xmmsv_t containing the strings from the input array.
xmmsv_t * xmmsv_build_dict (const char *firstkey,...)
xmmsv_t * xmmsv_build_dict_va (const char *firstkey, va_list ap)
xmmsv_t * xmmsv_build_list (xmmsv_t *first_entry,...)
xmmsv_t * xmmsv_build_list_va (xmmsv_t *first_entry, va_list ap)
xmmsv_t * xmmsv_build_empty_organize (void)
xmmsv_t * xmmsv_build_organize (xmmsv_t *data)
Creates an organize fetch specification that may be passed to xmmsc_coll_query.
xmmsv_t * xmmsv_build_metadata (xmmsv_t *keys, xmmsv_t *get, const char *aggregate, xmmsv_t *sourcepref)
Creates a metadata fetch specification.
xmmsv_t * xmmsv_build_cluster_list (xmmsv_t *cluster_by, xmmsv_t *cluster_field, xmmsv_t *cluster_data)
Creates a cluster-list fetch specification.
xmmsv_t * xmmsv_build_cluster_dict (xmmsv_t *cluster_by, xmmsv_t *cluster_field, xmmsv_t *cluster_data)
Creates a cluster-dict fetch specification.
xmmsv_t * xmmsv_build_count (void)
Creates a count fetch specification.
Detailed Description
Macro Definition Documentation
#define XMMSV_DICT_END NULL
Definition at line 44 of file xmmsv_build.h.
Referenced by xmms_collection_changed_msg_new(), xmms_collection_query_ids(), xmms_config_property_set_data(), xmms_medialib_query_random_id(), and xmmsv_c2c_message_format().
#define XMMSV_DICT_ENTRY (k, v) __xmmsv_identity_const_charp (k), __xmmsv_identity_xmmsv (v)
Definition at line 40 of file xmmsv_build.h.
Referenced by xmms_collection_query_ids(), xmms_medialib_query_random_id(), and xmmsv_c2c_message_format().
#define XMMSV_DICT_ENTRY_FLOAT (k, v) XMMSV_DICT_ENTRY (k, xmmsv_new_float (v))
Definition at line 43 of file xmmsv_build.h.
#define XMMSV_DICT_ENTRY_INT (k, v) XMMSV_DICT_ENTRY (k, xmmsv_new_int (v))
Definition at line 42 of file xmmsv_build.h.
Referenced by xmms_collection_changed_msg_new(), and xmmsv_c2c_message_format().
#define XMMSV_DICT_ENTRY_STR (k, v) XMMSV_DICT_ENTRY (k, __xmmsv_null_to_none (xmmsv_new_string (v)))
Definition at line 41 of file xmmsv_build.h.
Referenced by xmms_collection_changed_msg_new(), xmms_collection_query_ids(), xmms_config_property_set_data(), and xmms_medialib_query_random_id().
#define XMMSV_LIST_END NULL
Definition at line 53 of file xmmsv_build.h.
Referenced by xmms_collection_query_ids(), and xmms_medialib_query_random_id().
#define XMMSV_LIST_ENTRY (v) __xmmsv_identity_xmmsv (v)
Definition at line 48 of file xmmsv_build.h.
#define XMMSV_LIST_ENTRY_COLL (v) XMMSV_LIST_ENTRY (__xmmsv_null_to_none (xmmsv_new_coll (v)))
Definition at line 52 of file xmmsv_build.h.
#define XMMSV_LIST_ENTRY_FLOAT (v) XMMSV_LIST_ENTRY (xmmsv_new_float (v))
Definition at line 51 of file xmmsv_build.h.
#define XMMSV_LIST_ENTRY_INT (v) XMMSV_LIST_ENTRY (xmmsv_new_int (v))
Definition at line 50 of file xmmsv_build.h.
#define XMMSV_LIST_ENTRY_STR (v) XMMSV_LIST_ENTRY (__xmmsv_null_to_none (xmmsv_new_string (v)))
Definition at line 49 of file xmmsv_build.h.
Referenced by xmms_collection_query_ids(), and xmms_medialib_query_random_id().
Function Documentation
xmmsv_t* xmmsv_build_cluster_dict (xmmsv_t * cluster_by, xmmsv_t * cluster_field, xmmsv_t * cluster_data)
Creates a cluster-dict fetch specification.
Parameters
cluster_by A list of attributes to cluster by
cluster_data The fetch specifcation to use when filling the list
Returns
A cluster-list fetch specification
Definition at line 241 of file xmmsv_build.c.
xmmsv_t* xmmsv_build_cluster_list (xmmsv_t * cluster_by, xmmsv_t * cluster_field, xmmsv_t * cluster_data)
Creates a cluster-list fetch specification.
Parameters
cluster_by A list of attributes to cluster by
cluster_data The fetch specifcation to use when filling the list
Returns
A cluster-list fetch specification
Definition at line 208 of file xmmsv_build.c.
xmmsv_t* xmmsv_build_count (void)
Creates a count fetch specification.
Returns
A new count fetch specification
Definition at line 273 of file xmmsv_build.c.
xmmsv_t* xmmsv_build_dict (const char * firstkey, ...)
Definition at line 79 of file xmmsv_build.c.
Referenced by xmms_collection_changed_msg_new(), xmms_collection_query_ids(), xmms_config_property_set_data(), xmms_medialib_query_random_id(), and xmmsv_c2c_message_format().
xmmsv_t* xmmsv_build_dict_va (const char * firstkey, va_list ap)
Definition at line 53 of file xmmsv_build.c.
Referenced by xmmsv_build_dict().
xmmsv_t* xmmsv_build_empty_organize (void)
xmmsv_t* xmmsv_build_list (xmmsv_t * first_entry, ...)
Definition at line 118 of file xmmsv_build.c.
Referenced by xmms_collection_query_ids(), and xmms_medialib_query_random_id().
xmmsv_t* xmmsv_build_list_va (xmmsv_t * first_entry, va_list ap)
Definition at line 92 of file xmmsv_build.c.
Referenced by xmmsv_build_list().
xmmsv_t* xmmsv_build_metadata (xmmsv_t * fields, xmmsv_t * get, const char * aggregate, xmmsv_t * sourcepref)
Creates a metadata fetch specification.
Parameters
fields A list of fields to fetch, or NULL to fetch everything
get A list of what to get ("id", "key", "value", "source")
aggregate The aggregation function to use
sourcepref A list of sources, first one has the highest priority
Returns
A metadata fetch specification
Definition at line 162 of file xmmsv_build.c.
xmmsv_t* xmmsv_build_organize (xmmsv_t * data)
Creates an organize fetch specification that may be passed to xmmsc_coll_query.
It takes a dict with key-value pairs where the values are fetch specifications.
Returns
An organize fetch specification
Definition at line 137 of file xmmsv_build.c.
xmmsv_t* xmmsv_make_stringlist (char * array[], int num)
Helper function to build a list xmmsv_t containing the strings from the input array.
Parameters
array An array of C strings. Must be NULL-terminated if num is -1.
num The optional number of elements to read from the array. Set to -1 if the array is NULL-terminated.
Returns
An xmmsv_t containing the list of strings. Must be unreffed manually when done.
Definition at line 35 of file xmmsv_build.c.