XMMS2: Source Preferences
Source Preferences
S4
Handles source preferences.
Functions
s4_sourcepref_t * s4_sourcepref_create (const char **srcprefs)
Creates a new source preferences that can be used when querying.
void s4_sourcepref_unref (s4_sourcepref_t *sp)
Decreases the reference of a sourcepref.
s4_sourcepref_t * s4_sourcepref_ref (s4_sourcepref_t *sp)
Increases the refcount of a sourcepref.
int s4_sourcepref_get_priority (s4_sourcepref_t *sp, const char *src)
Gets the priority of a source.
Detailed Description
Handles source preferences.
Function Documentation
s4_sourcepref_t* s4_sourcepref_create (const char ** srcprefs)
Creates a new source preferences that can be used when querying.
Parameters
srcprefs An NULL terminated array of sources, where the first one has the highest priority. The sources may use glob- like patterns, for example "plugin*".
Returns
A new sourcepref
Definition at line 56 of file sourcepref.c.
Referenced by CASE(), xmms_medialib_init(), and xmms_medialib_session_property_set().
int s4_sourcepref_get_priority (s4_sourcepref_t * sp, const char * src)
Gets the priority of a source.
Parameters
sp The sourcepref to check against
src The source to check
Returns
The priority of the source
Definition at line 114 of file sourcepref.c.
Referenced by CASE().
s4_sourcepref_t* s4_sourcepref_ref (s4_sourcepref_t * sp)
Increases the refcount of a sourcepref.
Parameters
sp The sourcepref to reference
Definition at line 101 of file sourcepref.c.
Referenced by s4_cond_new_custom_filter(), s4_cond_new_filter(), s4_fetchspec_add(), and xmms_medialib_get_source_preferences().
void s4_sourcepref_unref (s4_sourcepref_t * sp)
Decreases the reference of a sourcepref.
If the reference count is less than or equal to zero it will be freed.
Parameters
sp The sourcepref to free
Definition at line 81 of file sourcepref.c.
Referenced by CASE(), s4_cond_free(), s4_fetchspec_free(), xmms_medialib_query(), and xmms_medialib_session_property_set().