XMMS2: Medialib
Medialib
XMMSServer
Medialib caches metadata.
Macros
#define XMMS_MEDIALIB_SOURCE_SERVER "server"
Functions
xmms_medialib_t * xmms_medialib_init (void)
Initialize the medialib and open the database file.
s4_sourcepref_t * xmms_medialib_get_source_preferences (xmms_medialib_t *medialib)
s4_t * xmms_medialib_get_database_backend (xmms_medialib_t *medialib)
char * xmms_medialib_uuid (xmms_medialib_t *medialib)
xmmsv_t * xmms_medialib_entry_property_get_value (xmms_medialib_session_t *session, xmms_medialib_entry_t id_num, const gchar *property)
Retrieve a property from an entry.
gchar * xmms_medialib_entry_property_get_str (xmms_medialib_session_t *session, xmms_medialib_entry_t entry, const gchar *property)
Retrieve a property from an entry.
gint xmms_medialib_entry_property_get_int (xmms_medialib_session_t *session, xmms_medialib_entry_t id_num, const gchar *property)
Retrieve a property as a int from a entry.
gboolean xmms_medialib_entry_property_set_int (xmms_medialib_session_t *session, xmms_medialib_entry_t entry, const gchar *property, gint value)
Set a entry property to a new value, overwriting the old value.
gboolean xmms_medialib_entry_property_set_int_source (xmms_medialib_session_t *session, xmms_medialib_entry_t id_num, const gchar *property, gint value, const gchar *source)
gboolean xmms_medialib_entry_property_set_str (xmms_medialib_session_t *session, xmms_medialib_entry_t entry, const gchar *property, const gchar *value)
Set a entry property to a new value, overwriting the old value.
gboolean xmms_medialib_entry_property_set_str_source (xmms_medialib_session_t *session, xmms_medialib_entry_t id_num, const gchar *property, const gchar *value, const gchar *source)
void xmms_medialib_entry_remove (xmms_medialib_session_t *session, xmms_medialib_entry_t entry)
Remove a medialib entry from the database.
void xmms_medialib_entry_cleanup (xmms_medialib_session_t *session, xmms_medialib_entry_t entry)
xmmsv_t * xmms_medialib_add_recursive (xmms_medialib_t *medialib, const gchar *path, xmms_error_t *error)
Recursively add files under a path to the media library.
xmms_medialib_entry_t xmms_medialib_entry_new_encoded (xmms_medialib_session_t *session, const gchar *url, xmms_error_t *error)
xmms_medialib_entry_t xmms_medialib_entry_new (xmms_medialib_session_t *session, const char *url, xmms_error_t *error)
Welcome to a function that should be called something else.
Detailed Description
Medialib caches metadata.
Controls metadata storage.
Macro Definition Documentation
#define XMMS_MEDIALIB_SOURCE_SERVER "server"
Definition at line 98 of file medialib.c.
Function Documentation
xmmsv_t* xmms_medialib_add_recursive (xmms_medialib_t * medialib, const gchar * path, xmms_error_t * error)
Recursively add files under a path to the media library.
Parameters
medialib the medialib object
path the directory to scan for files
error If an error occurs, it will be stored in there.
Returns
an IDLIST collection with the added entries
Definition at line 777 of file medialib.c.
void xmms_medialib_entry_cleanup (xmms_medialib_session_t * session, xmms_medialib_entry_t entry)
Definition at line 639 of file medialib.c.
xmms_medialib_entry_t xmms_medialib_entry_new (xmms_medialib_session_t * session, const char * url, xmms_error_t * error)
Welcome to a function that should be called something else.
Returns a entry for a URL, if the URL is already in the medialib the current entry will be returned otherwise a new one will be created and returned.
Todo:
rename to something better?
Parameters
url URL to add/retrieve from the medialib
error If an error occurs, it will be stored in there.
Returns
Entry mapped to the URL
Definition at line 880 of file medialib.c.
xmms_medialib_entry_t xmms_medialib_entry_new_encoded (xmms_medialib_session_t * session, const gchar * url, xmms_error_t * error)
Definition at line 845 of file medialib.c.
Referenced by xmms_medialib_entry_new().
gint xmms_medialib_entry_property_get_int (xmms_medialib_session_t * session, xmms_medialib_entry_t id_num, const gchar * property)
Retrieve a property as a int from a entry.
Parameters
id_num Entry to query.
property The property to extract. Strings passed should be defined in medialib.h
Returns
Property as integer, or -1 if it doesn't exist.
Definition at line 398 of file medialib.c.
gchar* xmms_medialib_entry_property_get_str (xmms_medialib_session_t * session, xmms_medialib_entry_t entry, const gchar * property)
Retrieve a property from an entry.
Parameters
entry Entry to query.
property The property to extract. Strings passed should be defined in medialib.h
Returns
Newly allocated gchar that needs to be freed with g_free
Definition at line 371 of file medialib.c.
xmmsv_t* xmms_medialib_entry_property_get_value (xmms_medialib_session_t * session, xmms_medialib_entry_t id_num, const gchar * property)
Retrieve a property from an entry.
See Also
xmms_medialib_entry_property_get_str
Definition at line 336 of file medialib.c.
Referenced by xmms_medialib_check_id().
gboolean xmms_medialib_entry_property_set_int (xmms_medialib_session_t * session, xmms_medialib_entry_t entry, const gchar * property, gint value)
Set a entry property to a new value, overwriting the old value.
Parameters
entry Entry to alter.
property The property to extract. Strings passed should be defined in medialib.h
value gint with the new value, will be copied in to the medialib
Returns
TRUE on success and FALSE on failure.
Definition at line 430 of file medialib.c.
Referenced by xmms_sample_converter_to_medialib().
gboolean xmms_medialib_entry_property_set_int_source (xmms_medialib_session_t * session, xmms_medialib_entry_t id_num, const gchar * property, gint value, const gchar * source)
Definition at line 442 of file medialib.c.
Referenced by xmms_medialib_entry_property_set_int().
gboolean xmms_medialib_entry_property_set_str (xmms_medialib_session_t * session, xmms_medialib_entry_t entry, const gchar * property, const gchar * value)
Set a entry property to a new value, overwriting the old value.
Parameters
entry Entry to alter.
property The property to extract. Strings passed should be defined in medialib.h
value gchar with the new value, will be copied in to the medialib
Returns
TRUE on success and FALSE on failure.
Definition at line 470 of file medialib.c.
Referenced by xmms_sample_converter_to_medialib().
gboolean xmms_medialib_entry_property_set_str_source (xmms_medialib_session_t * session, xmms_medialib_entry_t id_num, const gchar * property, const gchar * value, const gchar * source)
Definition at line 482 of file medialib.c.
Referenced by xmms_medialib_entry_property_set_str().
void xmms_medialib_entry_remove (xmms_medialib_session_t * session, xmms_medialib_entry_t entry)
Remove a medialib entry from the database.
Parameters
id_num Entry to remove
Definition at line 575 of file medialib.c.
s4_t* xmms_medialib_get_database_backend (xmms_medialib_t * medialib)
Definition at line 148 of file medialib.c.
s4_sourcepref_t* xmms_medialib_get_source_preferences (xmms_medialib_t * medialib)
Definition at line 142 of file medialib.c.
Referenced by xmms_medialib_session_get_source_preferences().
xmms_medialib_t* xmms_medialib_init (void)
Initialize the medialib and open the database file.
Returns
TRUE if successful and FALSE if there was a problem
Definition at line 107 of file medialib.c.
Referenced by main().
char* xmms_medialib_uuid (xmms_medialib_t * medialib)
Definition at line 262 of file medialib.c.
Referenced by main().