XMMS2: S4
S4
A database backend for XMMS2.
Modules
Condition
Functions to create and use S4 search conditions.
Fetch Specifications
Specifies what to fetch in a query.
Lock
Locks entries so only one transaction can use tham at a time.
Log
Logs every action so we can redo changes if something crashes.
Pattern
Functions to create and match glob-like patterns.
Entry
The in-memory database.
Result
Handles results returned from S4.
Result Set
A set of results.
Source Preferences
Handles source preferences.
Transactions
Functions dealing with transactions.
UUID
Functions dealing with UUID.
Value
The way values are represented in S4.
Macros
#define S4_MAGIC ("s4db")
#define S4_MAGIC_LEN (4)
#define S4_VERSION 1
Functions
s4_t * s4_open (const char *filename, const char **indices, int open_flags)
Opens an S4 database.
int s4_close (s4_t *s4)
Closes an open S4 database.
void s4_sync (s4_t *s4)
Writes all changes to disk.
s4_errno_t s4_errno ()
Returns the last error number set.
void s4_set_errno (s4_errno_t err)
Sets errno to the given error number.
int _reread_file (s4_t *s4)
void _start_sync (s4_t *s4)
void _sync (s4_t *s4)
Detailed Description
A database backend for XMMS2.
Macro Definition Documentation
#define S4_MAGIC ("s4db")
Definition at line 33 of file s4.c.
#define S4_MAGIC_LEN (4)
Definition at line 34 of file s4.c.
#define S4_VERSION 1
Definition at line 35 of file s4.c.
Function Documentation
int _reread_file (s4_t * s4)
Definition at line 195 of file s4.c.
void _start_sync (s4_t * s4)
Definition at line 413 of file s4.c.
Referenced by _log_write().
void _sync (s4_t * s4)
Definition at line 421 of file s4.c.
Referenced by s4_commit().
int s4_close (s4_t * s4)
Closes an open S4 database.
Parameters
s4 The database to close
Definition at line 545 of file s4.c.
Referenced by CASE(), and main().
s4_errno_t s4_errno (void)
Returns the last error number set.
This function is thread safe, error numbers set in one thread will NOT be seen in another thread.
Returns
The last error number set, or S4E_NOERROR if none has been set
Definition at line 583 of file s4.c.
Referenced by CASE().
s4_t* s4_open (const char * filename, const char ** indices, int open_flags)
Opens an S4 database.
The different flags you can pass:
S4_NEW
It will create a new file if one does not already exists. If one exists it will fail and return NULL.
S4_EXISTS
If the file does not exists it will fail and return NULL. s4_errno may be used to get more information about what went wrong.
S4_MEMORY Creates a memory-only database. It will not read any files on startup or write files on shutdown. Use this if you want a temporary database.
Parameters
filename The name of the file containing the database
indices An array of keys to have indices on
open_flags Zero or more of the flags bitwise-or'd.
Returns
A pointer to an s4_t, or NULL if something went wrong.
Definition at line 499 of file s4.c.
Referenced by CASE(), and main().
void s4_set_errno (s4_errno_t err)
Sets errno to the given error number.
Parameters
err The error number to set
Definition at line 597 of file s4.c.
Referenced by _lock_exclusive(), _lock_shared(), _log_open(), _oplist_execute(), and s4_commit().
void s4_sync (s4_t * s4)
Writes all changes to disk.
Parameters
s4 The database to sync
Definition at line 569 of file s4.c.
Referenced by s4_open().