XMMS2: src/lib/s4/src/lib/index.c File Reference
index.c File Reference
#include "s4_priv.h"
#include <stdlib.h>
#include <string.h>
Functions
s4_index_data_t * _index_create_data ()
void _index_free_data (s4_index_data_t *data)
s4_index_t * _index_get_a (s4_t *s4, const char *key, int create)
Gets the a-index associated with key.
s4_index_t * _index_get_b (s4_t *s4, const char *key)
Gets the b-index associated with key.
GList * _index_get_all_a (s4_t *s4)
Gets all a-indexes.
GList * _index_get_all_b (s4_t *s4)
Gets all b-indexes.
s4_index_t * _index_create ()
Creates a new index.
int _index_add (s4_t *s4, const char *key, s4_index_t *index)
Adds an index to a database.
int _index_insert (s4_index_t *index, const s4_val_t *val, void *new_data)
Inserts a new value-data pair into the index.
int _index_delete (s4_index_t *index, const s4_val_t *val, void *data)
Removes a value-data pair from the index.
GList * _index_search (s4_index_t *index, index_function_t func, void *func_data)
Searches an index.
GList * _index_lsearch (s4_index_t *index, index_function_t func, void *func_data)
Searches an index using a linear search.
void _index_free (s4_index_t *index)
Frees an index.
int _index_lock_shared (s4_index_t *index, s4_transaction_t *trans)
int _index_lock_exclusive (s4_index_t *index, s4_transaction_t *trans)
Function Documentation
int _index_add (s4_t * s4, const char * key, s4_index_t * index)
Adds an index to a database.
Parameters
s4 The database to add the index to
key The key to associate the index with
index The index to insert
Returns
0 if the key already has an index, non-zero otherwise
Definition at line 188 of file index.c.
Referenced by s4_open().
s4_index_t* _index_create (void)
Creates a new index.
Returns
A new index
Definition at line 169 of file index.c.
Referenced by _index_get_a(), and s4_open().
s4_index_data_t* _index_create_data (void)
Definition at line 51 of file index.c.
Referenced by _reread_file().
int _index_delete (s4_index_t * index, const s4_val_t * val, void * data)
Removes a value-data pair from the index.
Parameters
index The index to remove from
val The value to remove
data The data to remove
Returns
0 if the value-data pair is not found, 1 otherwise
Definition at line 302 of file index.c.
Referenced by _s4_del().
void _index_free (s4_index_t * index)
Frees an index.
The values and data is NOT freed
Parameters
index The index to free
Definition at line 414 of file index.c.
Referenced by _index_create_data().
void _index_free_data (s4_index_data_t * data)
Definition at line 65 of file index.c.
Referenced by _reread_file().
s4_index_t* _index_get_a (s4_t * s4, const char * key, int create)
Gets the a-index associated with key.
A a-index is used to lookup entries by the a-value. If an index has not yet been created for this key and create is non-zero, one will be created and returned.
Parameters
s4 The database to look for the index in
key The key the index should be indexing
create Creates the index if it does not exist
Returns
The index, or NULL if it does not exist and create is 0.
Definition at line 85 of file index.c.
Referenced by _s4_add(), _s4_add_internal(), _s4_del(), and _s4_query().
GList* _index_get_all_a (s4_t * s4)
Gets all a-indexes.
Parameters
s4 The database to get the index of.
Returns
A list of indexes.
Definition at line 134 of file index.c.
Referenced by _free_relations(), and _s4_query().
GList* _index_get_all_b (s4_t * s4)
Gets all b-indexes.
Parameters
s4 The database to get the index of.
Returns
A list of indexes.
Definition at line 152 of file index.c.
s4_index_t* _index_get_b (s4_t * s4, const char * key)
Gets the b-index associated with key.
A b-index is used to lookup entries by the b-value.
Parameters
s4 The database to look for the index in
key The key the index should be indexing
Returns
The index, or NULL if it is not found
Definition at line 108 of file index.c.
Referenced by _s4_add(), _s4_add_internal(), _s4_del(), and _s4_query().
int _index_insert (s4_index_t * index, const s4_val_t * val, void * new_data)
Inserts a new value-data pair into the index.
Parameters
index The index to insert into
val The value to associate the data with
new_data The data
Returns
1
Definition at line 254 of file index.c.
Referenced by _s4_add(), and _s4_add_internal().
int _index_lock_exclusive (s4_index_t * index, s4_transaction_t * trans)
Definition at line 432 of file index.c.
Referenced by _s4_add(), and _s4_del().
int _index_lock_shared (s4_index_t * index, s4_transaction_t * trans)
Definition at line 427 of file index.c.
Referenced by _s4_add(), _s4_del(), and _s4_query().
GList* _index_lsearch (s4_index_t * index, index_function_t func, void * func_data)
Searches an index using a linear search.
Parameters
index The index to search
func The function to use when searching. It should return 0 if the value matches, -1 if the value is too small and 1 if the value is too big,
func_data Data passed as the second argument to func
Returns
A GList where list->data is the data found matching
Definition at line 385 of file index.c.
Referenced by _s4_query().
GList* _index_search (s4_index_t * index, index_function_t func, void * func_data)
Searches an index.
Parameters
index The index to search
func The function to use when searching. It must be monotonic, It should return 0 if the value matches, -1 if the value is too small and 1 if the value is too big,
func_data Data passed as the second argument to func
Returns
A GList where list->data is the data found matching
Definition at line 341 of file index.c.
Referenced by _free_relations(), _s4_add(), _s4_add_internal(), _s4_del(), and _s4_query().