XMMS2: src/lib/s4/src/tools/s4/config.c File Reference
config.c File Reference
#include "cli.h"
#include <glib.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <ctype.h>
Macros
#define CONFIG_FILENAME "s4-cli.conf"
#define HEX_TO_CHAR(h) ((h)<10?(h) + '0':(h) + 'a' - 9)
#define CHAR_TO_HEX(c) (((c) & 0xf) + (((c) & 0x40) >> 6) * 9)
Functions
void config_init (void)
void config_cleanup (void)
void set_var (const char *key, char *val)
const char * get_var (const char *key)
void print_set_var (const char *key)
Variables
config_var user_vars []
char * config_file
Macro Definition Documentation
#define CHAR_TO_HEX (c) (((c) & 0xf) + (((c) & 0x40) >> 6) * 9)
Definition at line 70 of file config.c.
#define CONFIG_FILENAME "s4-cli.conf"
Definition at line 23 of file config.c.
Referenced by config_init().
#define HEX_TO_CHAR (h) ((h)<10?(h) + '0':(h) + 'a' - 9)
Definition at line 69 of file config.c.
Function Documentation
void config_cleanup (void)
Definition at line 125 of file config.c.
void config_init (void)
Definition at line 100 of file config.c.
const char* get_var (const char * key)
Definition at line 182 of file config.c.
Referenced by print_fetch(), print_list(), and print_result().
void print_set_var (const char * key)
Definition at line 198 of file config.c.
void set_var (const char * key, char * val)
Definition at line 150 of file config.c.
Referenced by config_init().
Variable Documentation
char* config_file
Definition at line 38 of file config.c.
Referenced by config_cleanup(), and config_init().
config_var user_vars[]
Initial value:
= {
    {.key = "default_source", .default_value = "s4", .possible_values = {NULL}},
    {.key = "print_mode", .default_value = "verbose", .possible_values = {"verbose", "pretty", "compact", NULL}},
    {.key = NULL}
}
Definition at line 32 of file config.c.
Referenced by config_cleanup(), config_init(), get_var(), print_set_var(), and set_var().