XMMS2: src/xmms/medialib_session.c File Reference
medialib_session.c File Reference
#include <xmmspriv/xmms_medialib.h>
#include <xmms/xmms_object.h>
#include <string.h>
Functions
xmms_medialib_session_t * xmms_medialib_session_begin (xmms_medialib_t *medialib)
xmms_medialib_session_t * xmms_medialib_session_begin_ro (xmms_medialib_t *medialib)
void xmms_medialib_session_abort (xmms_medialib_session_t *session)
gboolean xmms_medialib_session_commit (xmms_medialib_session_t *session)
s4_sourcepref_t * xmms_medialib_session_get_source_preferences (xmms_medialib_session_t *session)
s4_resultset_t * xmms_medialib_session_query (xmms_medialib_session_t *session, s4_fetchspec_t *specification, s4_condition_t *condition)
gint xmms_medialib_session_property_set (xmms_medialib_session_t *session, xmms_medialib_entry_t entry, const gchar *key, const s4_val_t *value, const gchar *source)
gint xmms_medialib_session_property_unset (xmms_medialib_session_t *session, xmms_medialib_entry_t entry, const gchar *key, const s4_val_t *value, const gchar *source)
void xmms_medialib_session_track_garbage (xmms_medialib_session_t *session, xmmsv_t *data)
Function Documentation
void xmms_medialib_session_abort (xmms_medialib_session_t * session)
Definition at line 67 of file medialib_session.c.
xmms_medialib_session_t* xmms_medialib_session_begin (xmms_medialib_t * medialib)
Definition at line 55 of file medialib_session.c.
Referenced by xmms_xform_chain_setup(), and xmms_xform_chain_setup_url().
xmms_medialib_session_t* xmms_medialib_session_begin_ro (xmms_medialib_t * medialib)
Definition at line 61 of file medialib_session.c.
Referenced by xmms_collection_get_random_media(), and xmms_playlist_insert_entry().
gboolean xmms_medialib_session_commit (xmms_medialib_session_t * session)
Definition at line 74 of file medialib_session.c.
Referenced by xmms_collection_get_random_media(), xmms_playlist_insert_entry(), xmms_xform_chain_setup(), and xmms_xform_chain_setup_url().
s4_sourcepref_t* xmms_medialib_session_get_source_preferences (xmms_medialib_session_t * session)
Definition at line 122 of file medialib_session.c.
Referenced by xmms_medialib_query().
gint xmms_medialib_session_property_set (xmms_medialib_session_t * session, xmms_medialib_entry_t entry, const gchar * key, const s4_val_t * value, const gchar * source)
Definition at line 136 of file medialib_session.c.
Referenced by xmms_medialib_entry_property_set_int_source(), and xmms_medialib_entry_property_set_str_source().
gint xmms_medialib_session_property_unset (xmms_medialib_session_t * session, xmms_medialib_entry_t entry, const gchar * key, const s4_val_t * value, const gchar * source)
Definition at line 195 of file medialib_session.c.
Referenced by xmms_medialib_entry_cleanup(), and xmms_medialib_entry_remove().
s4_resultset_t * xmms_medialib_session_query (xmms_medialib_session_t * session, s4_fetchspec_t * specification, s4_condition_t * condition)
Definition at line 128 of file medialib_session.c.
Referenced by xmms_medialib_query_recurs().
void xmms_medialib_session_track_garbage (xmms_medialib_session_t * session, xmmsv_t * data)
Definition at line 224 of file medialib_session.c.
Referenced by xmms_medialib_query().