XMMS2: src/xmms/metadata.c File Reference
metadata.c File Reference
#include <ctype.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include <glib.h>
#include <xmmspriv/xmms_metadata_mapper.h>
#include <xmmspriv/xmms_utils.h>
#include <xmms/xmms_log.h>
#include <xmms/xmms_xformplugin.h>
Functions
gboolean xmms_xform_metadata_parse_number (xmms_xform_t *xform, const gchar *key, const gchar *value, gsize length)
Set numeric metadata for the media by parsing a string value.
gboolean xmms_xform_metadata_parse_replay_gain (xmms_xform_t *xform, const gchar *key, const gchar *value, gsize length)
Set string metadata represesting replay gain for the media by parsing a string value.
gboolean xmms_xform_metadata_parse_compilation (xmms_xform_t *xform, const gchar *key, const gchar *value, gsize length)
Set compliation status by performing a number of probes on a value.
GHashTable * xmms_metadata_mapper_init (const xmms_xform_metadata_basic_mapping_t *basic_mappings, gint basic_count, const xmms_xform_metadata_mapping_t *mappings, gint count)
gboolean xmms_metadata_mapper_match (GHashTable *table, xmms_xform_t *xform, const gchar *key, const gchar *value, gsize length)
Function Documentation
GHashTable* xmms_metadata_mapper_init (const xmms_xform_metadata_basic_mapping_t * basic_mappings, gint basic_count, const xmms_xform_metadata_mapping_t * mappings, gint count)
Referenced by xmms_xform_plugin_metadata_basic_mapper_init(), and xmms_xform_plugin_metadata_mapper_init().
gboolean xmms_metadata_mapper_match (GHashTable * table, xmms_xform_t * xform, const gchar * key, const gchar * value, gsize length)
Referenced by xmms_xform_plugin_metadata_mapper_match().