XMMS2: src/xmms/object.c File Reference
object.c File Reference
#include <xmms/xmms_object.h>
#include <xmms/xmms_log.h>
#include <xmmsc/xmmsc_idnumbers.h>
#include <stdarg.h>
#include <string.h>
Functions
void xmms_object_cleanup (xmms_object_t *object)
Cleanup all the resources for the object.
void xmms_object_connect (xmms_object_t *object, guint32 signalid, xmms_object_handler_t handler, gpointer userdata)
Connect to a signal that is emitted by this object.
void xmms_object_disconnect (xmms_object_t *object, guint32 signalid, xmms_object_handler_t handler, gpointer userdata)
Disconnect from a signal.
void xmms_object_emit (xmms_object_t *object, guint32 signalid, xmmsv_t *data)
Emit a signal and thus call all the handlers that are connected.
void xmms_object_cmd_arg_init (xmms_object_cmd_arg_t *arg)
Initialize a command argument.
void xmms_object_cmd_add (xmms_object_t *object, guint cmdid, const xmms_object_cmd_func_t func)
Add a command that could be called from the client API to a object.
void xmms_object_cmd_call (xmms_object_t *object, guint cmdid, xmms_object_cmd_arg_t *arg)
Call a command with argument.
xmmsv_t * xmms_convert_and_kill_string (gchar *str)
int xmms_bin_to_gstring (xmmsv_t *value, GString **gs)
int dummy_identity (xmmsv_t *value, xmmsv_t **arg)
gpointer xmms_object_ref (gpointer obj)
void xmms_object_unref (gpointer obj)
xmms_object_t * __int_xmms_object_new (gint size, xmms_object_destroy_func_t destfunc)
Function Documentation
xmms_object_t* __int_xmms_object_new (gint size, xmms_object_destroy_func_t destfunc)
Definition at line 361 of file object.c.
gpointer xmms_object_ref (gpointer obj)
Definition at line 330 of file object.c.
Referenced by __int_xmms_object_new(), xmms_coll_sync_init(), xmms_collection_init(), xmms_courier_init(), xmms_mediainfo_reader_start(), xmms_output_new(), xmms_playlist_init(), xmms_playlist_updater_init(), xmms_visualization_new(), xmms_xform_new(), and xmms_xform_outdata_type_set().
void xmms_object_unref (gpointer obj)
Definition at line 343 of file object.c.
Referenced by xmms_config_shutdown(), xmms_ipc_shutdown(), xmms_output_plugin_switch(), xmms_plugin_load(), xmms_plugin_shutdown(), xmms_sample_converter_init(), xmms_stream_type_parse(), xmms_xform_browse(), xmms_xform_chain_setup(), xmms_xform_chain_setup_url(), xmms_xform_chain_setup_url_session(), and xmms_xform_new().