XMMS2: src/lib/s4/src/lib/oplist.c File Reference
oplist.c File Reference
#include "s4_priv.h"
#include <stdlib.h>
Enumerations
enum op_type_t { OP_ADD, OP_DEL, OP_WRITING }
Functions
oplist_t * _oplist_new (s4_transaction_t *trans)
s4_t * _oplist_get_db (oplist_t *list)
s4_transaction_t * _oplist_get_trans (oplist_t *list)
void _oplist_free (oplist_t *list)
void _oplist_insert_add (oplist_t *list, const char *key_a, const s4_val_t *val_a, const char *key_b, const s4_val_t *val_b, const char *src)
void _oplist_insert_del (oplist_t *list, const char *key_a, const s4_val_t *val_a, const char *key_b, const s4_val_t *val_b, const char *src)
void _oplist_insert_writing (oplist_t *list)
int _oplist_next (oplist_t *list)
void _oplist_first (oplist_t *list)
void _oplist_last (oplist_t *list)
int _oplist_get_add (oplist_t *list, const char **key_a, const s4_val_t **val_a, const char **key_b, const s4_val_t **val_b, const char **src)
int _oplist_get_del (oplist_t *list, const char **key_a, const s4_val_t **val_a, const char **key_b, const s4_val_t **val_b, const char **src)
int _oplist_get_writing (oplist_t *list)
int _oplist_rollback (oplist_t *list)
int _oplist_execute (oplist_t *list, int rollback_on_failure)
Enumeration Type Documentation
enum op_type_t
Enumerator
OP_ADD
OP_DEL
OP_WRITING
Definition at line 4 of file oplist.c.
Function Documentation
int _oplist_execute (oplist_t * list, int rollback_on_failure)
Definition at line 193 of file oplist.c.
void _oplist_first (oplist_t * list)
Definition at line 104 of file oplist.c.
Referenced by _log_write(), and _oplist_execute().
void _oplist_free (oplist_t * list)
Definition at line 42 of file oplist.c.
int _oplist_get_add (oplist_t * list, const char ** key_a, const s4_val_t ** val_a, const char ** key_b, const s4_val_t ** val_b, const char ** src)
Definition at line 114 of file oplist.c.
Referenced by _log_write(), _oplist_execute(), and _oplist_rollback().
s4_t* _oplist_get_db (oplist_t * list)
Definition at line 32 of file oplist.c.
Referenced by _log_write().
int _oplist_get_del (oplist_t * list, const char ** key_a, const s4_val_t ** val_a, const char ** key_b, const s4_val_t ** val_b, const char ** src)
Definition at line 138 of file oplist.c.
Referenced by _log_write(), _oplist_execute(), and _oplist_rollback().
s4_transaction_t* _oplist_get_trans (oplist_t * list)
Definition at line 37 of file oplist.c.
int _oplist_get_writing (oplist_t * list)
Definition at line 162 of file oplist.c.
Referenced by _log_write().
void _oplist_insert_add (oplist_t * list, const char * key_a, const s4_val_t * val_a, const char * key_b, const s4_val_t * val_b, const char * src)
Definition at line 49 of file oplist.c.
Referenced by s4_add().
void _oplist_insert_del (oplist_t * list, const char * key_a, const s4_val_t * val_a, const char * key_b, const s4_val_t * val_b, const char * src)
Definition at line 65 of file oplist.c.
Referenced by s4_del().
void _oplist_insert_writing (oplist_t * list)
Definition at line 81 of file oplist.c.
Referenced by _transaction_writing().
void _oplist_last (oplist_t * list)
Definition at line 109 of file oplist.c.
Referenced by s4_abort(), and s4_commit().
oplist_t* _oplist_new (s4_transaction_t * trans)
Definition at line 22 of file oplist.c.
Referenced by s4_begin().
int _oplist_next (oplist_t * list)
Definition at line 89 of file oplist.c.
Referenced by _log_write(), and _oplist_execute().
int _oplist_rollback (oplist_t * list)
Definition at line 177 of file oplist.c.
Referenced by _oplist_execute(), s4_abort(), and s4_commit().