XMMS2: src/xmms/outputplugin.c File Reference
outputplugin.c File Reference
#include <xmmspriv/xmms_outputplugin.h>
#include <xmmspriv/xmms_plugin.h>
#include <xmmspriv/xmms_thread_name.h>
#include <xmms/xmms_log.h>
Functions
xmms_plugin_t * xmms_output_plugin_new (void)
void xmms_output_plugin_methods_set (xmms_output_plugin_t *plugin, xmms_output_methods_t *methods)
Register the output plugin functions.
gboolean xmms_output_plugin_verify (xmms_plugin_t *_plugin)
xmms_config_property_t * xmms_output_plugin_config_property_register (xmms_output_plugin_t *plugin, const gchar *name, const gchar *default_value, xmms_object_handler_t cb, gpointer userdata)
Register a configuration directive in the plugin setup function.
gboolean xmms_output_plugin_method_new (xmms_output_plugin_t *plugin, xmms_output_t *output)
void xmms_output_plugin_method_destroy (xmms_output_plugin_t *plugin, xmms_output_t *output)
void xmms_output_plugin_method_flush (xmms_output_plugin_t *plugin, xmms_output_t *output)
gboolean xmms_output_plugin_format_set_always (xmms_output_plugin_t *plugin)
Check if an output plugin needs format updates on each track change.
gboolean xmms_output_plugin_method_format_set (xmms_output_plugin_t *plugin, xmms_output_t *output, xmms_stream_type_t *st)
gboolean xmms_output_plugin_method_status (xmms_output_plugin_t *plugin, xmms_output_t *output, gint st)
guint xmms_output_plugin_method_latency_get (xmms_output_plugin_t *plugin, xmms_output_t *output)
gboolean xmms_output_plugin_method_volume_set_available (xmms_output_plugin_t *plugin)
gboolean xmms_output_plugin_methods_volume_set (xmms_output_plugin_t *plugin, xmms_output_t *output, const gchar *chan, guint val)
gboolean xmms_output_plugin_method_volume_get_available (xmms_output_plugin_t *plugin)
gboolean xmms_output_plugin_method_volume_get (xmms_output_plugin_t *plugin, xmms_output_t *output, const gchar **n, guint *x, guint *y)
Function Documentation
void xmms_output_plugin_method_destroy (xmms_output_plugin_t * plugin, xmms_output_t * output)
Definition at line 184 of file outputplugin.c.
void xmms_output_plugin_method_flush (xmms_output_plugin_t * plugin, xmms_output_t * output)
Definition at line 210 of file outputplugin.c.
Referenced by xmms_output_flush().
gboolean xmms_output_plugin_method_format_set (xmms_output_plugin_t * plugin, xmms_output_t * output, xmms_stream_type_t * st)
Definition at line 237 of file outputplugin.c.
guint xmms_output_plugin_method_latency_get (xmms_output_plugin_t * plugin, xmms_output_t * output)
Definition at line 280 of file outputplugin.c.
Referenced by xmms_output_latency().
gboolean xmms_output_plugin_method_new (xmms_output_plugin_t * plugin, xmms_output_t * output)
Definition at line 160 of file outputplugin.c.
gboolean xmms_output_plugin_method_status (xmms_output_plugin_t * plugin, xmms_output_t * output, gint st)
Definition at line 261 of file outputplugin.c.
gboolean xmms_output_plugin_method_volume_get (xmms_output_plugin_t * plugin, xmms_output_t * output, const gchar ** n, guint * x, guint * y)
Definition at line 333 of file outputplugin.c.
gboolean xmms_output_plugin_method_volume_get_available (xmms_output_plugin_t * plugin)
Definition at line 324 of file outputplugin.c.
gboolean xmms_output_plugin_method_volume_set_available (xmms_output_plugin_t * plugin)
Definition at line 297 of file outputplugin.c.
gboolean xmms_output_plugin_methods_volume_set (xmms_output_plugin_t * plugin, xmms_output_t * output, const gchar * chan, guint val)
Definition at line 306 of file outputplugin.c.
xmms_plugin_t* xmms_output_plugin_new (void)
Definition at line 70 of file outputplugin.c.
Referenced by xmms_plugin_load().
gboolean xmms_output_plugin_verify (xmms_plugin_t * _plugin)
Definition at line 101 of file outputplugin.c.
Referenced by xmms_plugin_load().