XMMS2: src/lib/s4/src/tools/s4/print.c File Reference
print.c File Reference
#include "cli.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
const char * value_to_string (const s4_val_t *val)
void print_list (list_t *l)
int find_column (const char *key, const s4_resultset_t *set)
void print_result (const s4_resultset_t *set)
void print_cond (s4_condition_t *cond)
void print_fetch (s4_fetchspec_t *fetch)
void print_vars ()
void print_help (void)
Function Documentation
int find_column (const char * key, const s4_resultset_t * set)
void print_cond (s4_condition_t * cond)
Referenced by print_vars().
void print_fetch (s4_fetchspec_t * fetch)
Referenced by print_vars().
void print_help (void)
void print_list (list_t * l)
Referenced by print_vars().
void print_result (const s4_resultset_t * set)
Referenced by print_vars().
void print_vars (void)
const char* value_to_string (const s4_val_t * val)
Referenced by print_cond(), print_list(), and print_result().