XMMS2: src/includepriv/xmmspriv/xmms_plugin.h File Reference
xmms_plugin.h File Reference
#include <xmms/xmms_object.h>
#include <xmms/xmms_plugin.h>
#include <xmms/xmms_config.h>
#include <gmodule.h>
Data Structures
struct xmms_plugin_St
Macros
#define XMMS_BUILTIN_DEFINE(type, api_ver, shname, name, ver, desc, setupfunc)
Typedefs
typedef struct xmms_plugin_St xmms_plugin_t
typedef gboolean(* xmms_plugin_foreach_func_t)(xmms_plugin_t *, gpointer)
Functions
gboolean xmms_plugin_load (const xmms_plugin_desc_t *desc, GModule *module)
gboolean xmms_plugin_init (const gchar *path)
void xmms_plugin_shutdown (void)
void xmms_plugin_destroy (xmms_plugin_t *plugin)
void xmms_plugin_foreach (xmms_plugin_type_t type, xmms_plugin_foreach_func_t func, gpointer user_data)
xmms_plugin_t * xmms_plugin_find (xmms_plugin_type_t type, const gchar *name)
xmms_plugin_type_t xmms_plugin_type_get (const xmms_plugin_t *plugin)
const char * xmms_plugin_name_get (const xmms_plugin_t *plugin)
const gchar * xmms_plugin_shortname_get (const xmms_plugin_t *plugin)
const gchar * xmms_plugin_version_get (const xmms_plugin_t *plugin)
const char * xmms_plugin_description_get (const xmms_plugin_t *plugin)
xmms_config_property_t * xmms_plugin_config_lookup (xmms_plugin_t *plugin, const gchar *key)
xmms_config_property_t * xmms_plugin_config_property_register (xmms_plugin_t *plugin, const gchar *name, const gchar *default_value, xmms_object_handler_t cb, gpointer userdata)
Macro Definition Documentation
#define XMMS_BUILTIN_DEFINE (type, api_ver, shname, name, ver, desc, setupfunc)
Value:
const xmms_plugin_desc_t xmms_builtin_##shname = {          \
        type,                           \
        api_ver,                        \
        G_STRINGIFY(shname),                    \
        name,                         \
        ver,                            \
        desc,                           \
        setupfunc                       \
    };
Definition at line 63 of file xmms_plugin.h.
Typedef Documentation
typedef gboolean(* xmms_plugin_foreach_func_t)(xmms_plugin_t *, gpointer)
Definition at line 48 of file xmms_plugin.h.
typedef struct xmms_plugin_St xmms_plugin_t
Function Documentation
xmms_config_property_t* xmms_plugin_config_lookup (xmms_plugin_t * plugin, const gchar * key)
Definition at line 76 of file plugin.c.
Referenced by xmms_output_config_lookup(), xmms_xform_config_lookup(), xmms_xform_plugin_config_lookup(), and xmms_xform_plugin_supports().
xmms_config_property_t* xmms_plugin_config_property_register (xmms_plugin_t * plugin, const gchar * name, const gchar * default_value, xmms_object_handler_t cb, gpointer userdata)
Definition at line 104 of file plugin.c.
Referenced by xmms_output_config_property_register(), xmms_output_plugin_config_property_register(), and xmms_xform_plugin_config_property_register().
const char* xmms_plugin_description_get (const xmms_plugin_t * plugin)
Definition at line 184 of file plugin.c.
void xmms_plugin_destroy (xmms_plugin_t * plugin)
Definition at line 479 of file plugin.c.
xmms_plugin_t* xmms_plugin_find (xmms_plugin_type_t type, const gchar * name)
Definition at line 458 of file plugin.c.
Referenced by main(), and xmms_xform_chain_setup_url_session().
void xmms_plugin_foreach (xmms_plugin_type_t type, xmms_plugin_foreach_func_t func, gpointer user_data)
Definition at line 419 of file plugin.c.
Referenced by xmms_plugin_find(), and xmms_xform_find().
gboolean xmms_plugin_init (const gchar * path)
Definition at line 227 of file plugin.c.
Referenced by main().
gboolean xmms_plugin_load (const xmms_plugin_desc_t * desc, GModule * module)
Definition at line 282 of file plugin.c.
const char* xmms_plugin_name_get (const xmms_plugin_t * plugin)
Definition at line 145 of file plugin.c.
const gchar* xmms_plugin_shortname_get (const xmms_plugin_t * plugin)
Definition at line 158 of file plugin.c.
Referenced by xmms_output_plugin_methods_set(), xmms_output_set_error(), xmms_plugin_config_lookup(), xmms_plugin_config_property_register(), xmms_xform_plugin_methods_set(), and xmms_xform_shortname().
void xmms_plugin_shutdown (void)
Definition at line 243 of file plugin.c.
xmms_plugin_type_t xmms_plugin_type_get (const xmms_plugin_t * plugin)
Definition at line 132 of file plugin.c.
const gchar* xmms_plugin_version_get (const xmms_plugin_t * plugin)
Definition at line 171 of file plugin.c.