XMMS2: src/includepriv/xmmspriv/xmms_streamtype.h File Reference
xmms_streamtype.h File Reference
#include <stdarg.h>
#include <xmms/xmms_streamtype.h>
Functions
xmms_stream_type_t * xmms_stream_type_parse (va_list ap)
gboolean xmms_stream_type_match (const xmms_stream_type_t *in_type, const xmms_stream_type_t *out_type)
xmms_stream_type_t * xmms_stream_type_coerce (const xmms_stream_type_t *in, const GList *goal_types)
Find the best pair of formats.
xmms_stream_type_t * _xmms_stream_type_new (const gchar *begin,...)
Function Documentation
xmms_stream_type_t* _xmms_stream_type_new (const gchar * begin, ...)
Definition at line 362 of file streamtype.c.
Referenced by xmms_stream_type_coerce().
xmms_stream_type_t* xmms_stream_type_coerce (const xmms_stream_type_t * in, const GList * goal_types)
Find the best pair of formats.
Definition at line 240 of file streamtype.c.
gboolean xmms_stream_type_match (const xmms_stream_type_t * in_type, const xmms_stream_type_t * out_type)
Definition at line 210 of file streamtype.c.
Referenced by xmms_xform_plugin_supports().
xmms_stream_type_t* xmms_stream_type_parse (va_list ap)
Definition at line 71 of file streamtype.c.
Referenced by _xmms_stream_type_new(), xmms_output_stream_type_add(), xmms_xform_outdata_type_add(), xmms_xform_plugin_indata_add(), and xmms_xform_plugin_set_out_stream_type().