XMMS2: src/includepriv/xmmspriv/xmms_medialib.h File Reference
xmms_medialib.h File Reference
#include <xmms/xmms_medialib.h>
#include <xmmspriv/xmms_collection.h>
#include <xmmspriv/xmms_fetch_info.h>
#include <xmmspriv/xmms_fetch_spec.h>
#include <s4.h>
Macros
#define xmms_medialib_entry_status_set(s, e, st) xmms_medialib_entry_property_set_int_source(s, e, XMMS_MEDIALIB_ENTRY_PROPERTY_STATUS, st, "server") /** @todo: hardcoded server id might be bad? */
Typedefs
typedef struct xmms_medialib_St xmms_medialib_t
typedef struct
xmms_medialib_session_St xmms_medialib_session_t
Functions
xmms_medialib_t * xmms_medialib_init (void)
Initialize the medialib and open the database file.
s4_t * xmms_medialib_get_database_backend (xmms_medialib_t *medialib)
s4_sourcepref_t * xmms_medialib_get_source_preferences (xmms_medialib_t *medialib)
char * xmms_medialib_uuid (xmms_medialib_t *mlib)
s4_resultset_t * xmms_medialib_session_query (xmms_medialib_session_t *s, s4_fetchspec_t *spec, s4_condition_t *cond)
guint xmms_medialib_num_not_resolved (xmms_medialib_session_t *s)
xmms_medialib_entry_t xmms_medialib_entry_not_resolved_get (xmms_medialib_session_t *s)
xmms_medialib_entry_t xmms_medialib_entry_new (xmms_medialib_session_t *s, const char *url, xmms_error_t *error)
Welcome to a function that should be called something else.
xmms_medialib_entry_t xmms_medialib_entry_new_encoded (xmms_medialib_session_t *s, const char *url, xmms_error_t *error)
void xmms_medialib_entry_remove (xmms_medialib_session_t *s, xmms_medialib_entry_t entry)
Remove a medialib entry from the database.
void xmms_medialib_entry_cleanup (xmms_medialib_session_t *s, xmms_medialib_entry_t entry)
gint xmms_medialib_entry_property_get_int (xmms_medialib_session_t *s, xmms_medialib_entry_t entry, const gchar *property)
Retrieve a property as a int from a entry.
gchar * xmms_medialib_entry_property_get_str (xmms_medialib_session_t *s, xmms_medialib_entry_t entry, const gchar *property)
Retrieve a property from an entry.
xmmsv_t * xmms_medialib_entry_property_get_value (xmms_medialib_session_t *s, xmms_medialib_entry_t entry, const gchar *property)
Retrieve a property from an entry.
gboolean xmms_medialib_entry_property_set_int (xmms_medialib_session_t *s, xmms_medialib_entry_t entry, const gchar *property, gint value)
Set a entry property to a new value, overwriting the old value.
gboolean xmms_medialib_entry_property_set_str (xmms_medialib_session_t *s, xmms_medialib_entry_t entry, const gchar *property, const gchar *value)
Set a entry property to a new value, overwriting the old value.
gboolean xmms_medialib_entry_property_set_int_source (xmms_medialib_session_t *s, xmms_medialib_entry_t entry, const gchar *property, gint value, const gchar *source)
gboolean xmms_medialib_entry_property_set_str_source (xmms_medialib_session_t *s, xmms_medialib_entry_t entry, const gchar *property, const gchar *value, const gchar *source)
gchar * xmms_medialib_url_encode (const gchar *path)
gboolean xmms_medialib_decode_url (char *url)
gboolean xmms_medialib_check_id (xmms_medialib_session_t *s, xmms_medialib_entry_t entry)
xmmsv_t * xmms_medialib_add_recursive (xmms_medialib_t *medialib, const gchar *path, xmms_error_t *error)
Recursively add files under a path to the media library.
xmms_medialib_entry_t xmms_medialib_query_random_id (xmms_medialib_session_t *s, xmmsv_t *coll)
Returns a random entry from a collection.
xmmsv_t * xmms_medialib_query (xmms_medialib_session_t *s, xmmsv_t *coll, xmmsv_t *fetch, xmms_error_t *err)
Queries the medialib and returns an xmmsv_t with the info requested.
s4_resultset_t * xmms_medialib_query_recurs (xmms_medialib_session_t *session, xmmsv_t *coll, xmms_fetch_info_t *fetch)
Internal function that does the actual querying.
xmmsv_t * xmms_medialib_query_to_xmmsv (s4_resultset_t *set, xmms_fetch_spec_t *spec)
xmms_medialib_session_t * xmms_medialib_session_begin (xmms_medialib_t *mlib)
xmms_medialib_session_t * xmms_medialib_session_begin_ro (xmms_medialib_t *medialib)
void xmms_medialib_session_abort (xmms_medialib_session_t *session)
gboolean xmms_medialib_session_commit (xmms_medialib_session_t *session)
s4_sourcepref_t * xmms_medialib_session_get_source_preferences (xmms_medialib_session_t *session)
void xmms_medialib_session_track_garbage (xmms_medialib_session_t *session, xmmsv_t *data)
gint xmms_medialib_session_property_set (xmms_medialib_session_t *session, xmms_medialib_entry_t entry, const gchar *key, const s4_val_t *value, const gchar *source)
gint xmms_medialib_session_property_unset (xmms_medialib_session_t *session, xmms_medialib_entry_t entry, const gchar *key, const s4_val_t *value, const gchar *source)
Macro Definition Documentation
#define xmms_medialib_entry_status_set (s, e, st) xmms_medialib_entry_property_set_int_source(s, e, XMMS_MEDIALIB_ENTRY_PROPERTY_STATUS, st, "server") /** @todo: hardcoded server id might be bad? */
Definition at line 81 of file xmms_medialib.h.
Typedef Documentation
typedef struct xmms_medialib_session_St xmms_medialib_session_t
Definition at line 26 of file xmms_medialib.h.
typedef struct xmms_medialib_St xmms_medialib_t
Definition at line 25 of file xmms_medialib.h.
Function Documentation
gboolean xmms_medialib_check_id (xmms_medialib_session_t * s, xmms_medialib_entry_t entry)
Definition at line 1170 of file medialib.c.
Referenced by xmms_playlist_insert_entry().
gboolean xmms_medialib_decode_url (char * url)
xmms_medialib_entry_t xmms_medialib_entry_new_encoded (xmms_medialib_session_t * s, const char * url, xmms_error_t * error)
xmms_medialib_entry_t xmms_medialib_entry_not_resolved_get (xmms_medialib_session_t * s)
Definition at line 1265 of file medialib.c.
guint xmms_medialib_num_not_resolved (xmms_medialib_session_t * s)
Definition at line 1284 of file medialib.c.
xmmsv_t* xmms_medialib_query (xmms_medialib_session_t * session, xmmsv_t * coll, xmmsv_t * fetch, xmms_error_t * err)
Queries the medialib and returns an xmmsv_t with the info requested.
Parameters
coll The collection to find
fetch Specifies what to fetch
Returns
An xmmsv_t with the structure requested in fetch
Definition at line 1384 of file medialib.c.
Referenced by xmms_medialib_query_random_id().
xmms_medialib_entry_t xmms_medialib_query_random_id (xmms_medialib_session_t * session, xmmsv_t * coll)
Returns a random entry from a collection.
Parameters
coll The collection to find a random entry in
Returns
A random entry from the collection, 0 if the collection is empty
Definition at line 1193 of file medialib.c.
Referenced by xmms_collection_get_random_media().
s4_resultset_t* xmms_medialib_query_recurs (xmms_medialib_session_t * session, xmmsv_t * coll, xmms_fetch_info_t * fetch)
Internal function that does the actual querying.
Parameters
coll The collection to use when querying
fetch Information on what is being fetched
Returns
An S4 resultset correspoding to the entires in the medialib matching the collection. Must be free with s4_resultset_free
Definition at line 969 of file medialib_query.c.
Referenced by xmms_medialib_query().
xmmsv_t* xmms_medialib_query_to_xmmsv (s4_resultset_t * set, xmms_fetch_spec_t * spec)
Definition at line 582 of file medialib_query_result.c.
Referenced by xmms_medialib_query(), and xmms_medialib_query_to_xmmsv().
void xmms_medialib_session_abort (xmms_medialib_session_t * session)
Definition at line 67 of file medialib_session.c.
xmms_medialib_session_t* xmms_medialib_session_begin (xmms_medialib_t * mlib)
Definition at line 55 of file medialib_session.c.
Referenced by xmms_xform_chain_setup(), and xmms_xform_chain_setup_url().
xmms_medialib_session_t* xmms_medialib_session_begin_ro (xmms_medialib_t * medialib)
Definition at line 61 of file medialib_session.c.
Referenced by xmms_collection_get_random_media(), and xmms_playlist_insert_entry().
gboolean xmms_medialib_session_commit (xmms_medialib_session_t * session)
Definition at line 74 of file medialib_session.c.
Referenced by xmms_collection_get_random_media(), xmms_playlist_insert_entry(), xmms_xform_chain_setup(), and xmms_xform_chain_setup_url().
s4_sourcepref_t* xmms_medialib_session_get_source_preferences (xmms_medialib_session_t * session)
Definition at line 122 of file medialib_session.c.
Referenced by xmms_medialib_query().
gint xmms_medialib_session_property_set (xmms_medialib_session_t * session, xmms_medialib_entry_t entry, const gchar * key, const s4_val_t * value, const gchar * source)
Definition at line 136 of file medialib_session.c.
Referenced by xmms_medialib_entry_property_set_int_source(), and xmms_medialib_entry_property_set_str_source().
gint xmms_medialib_session_property_unset (xmms_medialib_session_t * session, xmms_medialib_entry_t entry, const gchar * key, const s4_val_t * value, const gchar * source)
Definition at line 195 of file medialib_session.c.
Referenced by xmms_medialib_entry_cleanup(), and xmms_medialib_entry_remove().
s4_resultset_t* xmms_medialib_session_query (xmms_medialib_session_t * s, s4_fetchspec_t * spec, s4_condition_t * cond)
Definition at line 128 of file medialib_session.c.
Referenced by xmms_medialib_query_recurs().
void xmms_medialib_session_track_garbage (xmms_medialib_session_t * session, xmmsv_t * data)
Definition at line 224 of file medialib_session.c.
Referenced by xmms_medialib_query().
gchar* xmms_medialib_url_encode (const gchar * path)
Definition at line 1346 of file medialib.c.
Referenced by xmms_medialib_entry_new(), xmms_xform_browse_add_entry(), and xmms_xform_browse_add_symlink_args().