XMMS2: src/includepriv/xmmspriv/xmms_outputplugin.h File Reference
xmms_outputplugin.h File Reference
#include <xmms/xmms_outputplugin.h>
#include <xmmspriv/xmms_plugin.h>
Functions
xmms_plugin_t * xmms_output_plugin_new (void)
gboolean xmms_output_plugin_verify (xmms_plugin_t *_plugin)
gboolean xmms_output_plugin_method_new (xmms_output_plugin_t *plugin, xmms_output_t *output)
void xmms_output_plugin_method_destroy (xmms_output_plugin_t *plugin, xmms_output_t *output)
void xmms_output_plugin_method_flush (xmms_output_plugin_t *plugin, xmms_output_t *output)
gboolean xmms_output_plugin_method_format_set (xmms_output_plugin_t *plugin, xmms_output_t *output, xmms_stream_type_t *st)
gboolean xmms_output_plugin_method_status (xmms_output_plugin_t *plugin, xmms_output_t *output, int st)
guint xmms_output_plugin_method_latency_get (xmms_output_plugin_t *plugin, xmms_output_t *output)
gboolean xmms_output_plugin_method_volume_set_available (xmms_output_plugin_t *plugin)
gboolean xmms_output_plugin_methods_volume_set (xmms_output_plugin_t *plugin, xmms_output_t *output, const gchar *chan, guint val)
gboolean xmms_output_plugin_method_volume_get_available (xmms_output_plugin_t *plugin)
gboolean xmms_output_plugin_method_volume_get (xmms_output_plugin_t *plugin, xmms_output_t *output, const gchar **n, guint *x, guint *y)
Function Documentation
void xmms_output_plugin_method_destroy (xmms_output_plugin_t * plugin, xmms_output_t * output)
void xmms_output_plugin_method_flush (xmms_output_plugin_t * plugin, xmms_output_t * output)
Referenced by xmms_output_flush().
gboolean xmms_output_plugin_method_format_set (xmms_output_plugin_t * plugin, xmms_output_t * output, xmms_stream_type_t * st)
guint xmms_output_plugin_method_latency_get (xmms_output_plugin_t * plugin, xmms_output_t * output)
Referenced by xmms_output_latency().
gboolean xmms_output_plugin_method_new (xmms_output_plugin_t * plugin, xmms_output_t * output)
gboolean xmms_output_plugin_method_status (xmms_output_plugin_t * plugin, xmms_output_t * output, int st)
gboolean xmms_output_plugin_method_volume_get (xmms_output_plugin_t * plugin, xmms_output_t * output, const gchar ** n, guint * x, guint * y)
gboolean xmms_output_plugin_method_volume_get_available (xmms_output_plugin_t * plugin)
gboolean xmms_output_plugin_method_volume_set_available (xmms_output_plugin_t * plugin)
gboolean xmms_output_plugin_methods_volume_set (xmms_output_plugin_t * plugin, xmms_output_t * output, const gchar * chan, guint val)
xmms_plugin_t* xmms_output_plugin_new (void)
Referenced by xmms_plugin_load().
gboolean xmms_output_plugin_verify (xmms_plugin_t * _plugin)
Referenced by xmms_plugin_load().