XMMS2: src/xmms/sample.c File Reference
sample.c File Reference
#include <glib.h>
#include <xmms/xmms_sample.h>
Functions
gint xmms_sample_frame_size_get (const xmms_stream_type_t *st)
Get number of bytes used for one sample length worth of music.
gint64 xmms_sample_ms_to_samples (const xmms_stream_type_t *st, gint64 milliseconds)
convert from milliseconds to samples for this format.
gint64 xmms_sample_samples_to_ms (const xmms_stream_type_t *st, gint64 samples)
Convert from samples to milliseconds for this format.
gint64 xmms_sample_samples_to_bytes (const xmms_stream_type_t *st, gint64 samples)
Convert from samples to bytes for this format.
gint64 xmms_sample_bytes_to_samples (const xmms_stream_type_t *st, gint64 bytes, xmms_error_t *error)
Convert from bytes to samples for this format.
gint64 xmms_sample_bytes_to_samples_inexact (const xmms_stream_type_t *st, gint64 bytes)
Convert from bytes to samples for this format.
gint64 xmms_sample_bytes_to_ms (const xmms_stream_type_t *st, gint64 bytes)
Convert from bytes to milliseconds for this format.
gint64 xmms_sample_ms_to_bytes (const xmms_stream_type_t *st, gint64 ms)
Convert from milliseconds to bytes for this format.
Function Documentation
gint64 xmms_sample_bytes_to_ms (const xmms_stream_type_t * st, gint64 bytes)
Convert from bytes to milliseconds for this format.
This is not exact.
Definition at line 95 of file sample.c.
Referenced by xmms_output_latency().
gint64 xmms_sample_bytes_to_samples (const xmms_stream_type_t * st, gint64 bytes, xmms_error_t * error)
Convert from bytes to samples for this format.
This is exact. On error 0 is returned and error is set.
Definition at line 69 of file sample.c.
gint64 xmms_sample_bytes_to_samples_inexact (const xmms_stream_type_t * st, gint64 bytes)
Convert from bytes to samples for this format.
This is not exact.
Definition at line 85 of file sample.c.
Referenced by xmms_sample_bytes_to_ms().
gint xmms_sample_frame_size_get (const xmms_stream_type_t * st)
Get number of bytes used for one sample length worth of music.
That is, (size of one sample) * channels.
Definition at line 27 of file sample.c.
Referenced by xmms_output_read(), xmms_sample_bytes_to_samples(), xmms_sample_bytes_to_samples_inexact(), xmms_sample_convert(), xmms_sample_convert_reset(), and xmms_sample_samples_to_bytes().
gint64 xmms_sample_ms_to_bytes (const xmms_stream_type_t * st, gint64 ms)
Convert from milliseconds to bytes for this format.
This is not exact.
Definition at line 104 of file sample.c.
gint64 xmms_sample_ms_to_samples (const xmms_stream_type_t * st, gint64 milliseconds)
convert from milliseconds to samples for this format.
Definition at line 39 of file sample.c.
Referenced by xmms_sample_ms_to_bytes().
gint64 xmms_sample_samples_to_bytes (const xmms_stream_type_t * st, gint64 samples)
Convert from samples to bytes for this format.
This is exact.
Definition at line 59 of file sample.c.
Referenced by xmms_sample_ms_to_bytes().
gint64 xmms_sample_samples_to_ms (const xmms_stream_type_t * st, gint64 samples)
Convert from samples to milliseconds for this format.
Definition at line 49 of file sample.c.
Referenced by xmms_sample_bytes_to_ms().