XMMS2: src/lib/xmmssocket/socket_common.c File Reference
socket_common.c File Reference
#include <xmmsc/xmmsc_sockets.h>
#include <xmmsc/xmmsc_stdbool.h>
Functions
bool xmms_socket_error_recoverable ()
int xmms_getaddrinfo (const char *node, const char *service, const struct addrinfo *hints, struct addrinfo **res)
void xmms_freeaddrinfo (struct addrinfo *res)
Function Documentation
void xmms_freeaddrinfo (struct addrinfo * res)
Definition at line 26 of file socket_common.c.
Referenced by xmms_ipc_tcp_client_init(), and xmms_ipc_tcp_server_init().
int xmms_getaddrinfo (const char * node, const char * service, const struct addrinfo * hints, struct addrinfo ** res)
Definition at line 19 of file socket_common.c.
Referenced by xmms_ipc_tcp_client_init(), and xmms_ipc_tcp_server_init().
bool xmms_socket_error_recoverable (void)
Definition at line 9 of file socket_common.c.
Referenced by xmms_ipc_msg_read_transport(), and xmms_ipc_msg_write_transport().