XMMS2: src/lib/xmmssocket/socket_win32.c File Reference
socket_win32.c File Reference
#include <xmmsc/xmmsc_sockets.h>
Functions
int xmms_sockets_initialize ()
int xmms_socket_set_nonblock (xmms_socket_t socket)
Tries to set socket to non-blocking mode.
int xmms_socket_valid (xmms_socket_t socket)
void xmms_socket_invalidate (xmms_socket_t *socket)
void xmms_socket_close (xmms_socket_t socket)
int xmms_socket_errno ()
Function Documentation
void xmms_socket_close (xmms_socket_t socket)
int xmms_socket_errno (void)
Referenced by xmms_socket_error_recoverable().
void xmms_socket_invalidate (xmms_socket_t * socket)
Referenced by xmms_visualization_new().
int xmms_socket_set_nonblock (xmms_socket_t socket)
Tries to set socket to non-blocking mode.
Parameters
socket Socket to make non-blocking. On success, returns 1. On failure, closes socket and returns 0.
Referenced by xmms_ipc_tcp_client_init(), and xmms_ipc_tcp_server_init().
int xmms_socket_valid (xmms_socket_t socket)
Referenced by init_udp(), xmms_ipc_tcp_client_init(), and xmms_ipc_tcp_server_init().
int xmms_sockets_initialize (void)
Referenced by xmms_ipc_tcp_client_init(), and xmms_ipc_tcp_server_init().