XMMS2: src/xmms/streamtype.c File Reference
streamtype.c File Reference
xforms
#include <glib.h>
#include <xmmspriv/xmms_xform.h>
#include <xmms/xmms_log.h>
#include <xmms/xmms_object.h>
Typedefs
typedef enum
xmms_stream_type_val_type_E xmms_stream_type_val_type_t
typedef struct
xmms_stream_type_val_St xmms_stream_type_val_t
Enumerations
enum xmms_stream_type_val_type_E { STRING, INT }
Functions
xmms_stream_type_t * xmms_stream_type_parse (va_list ap)
const char * xmms_stream_type_get_str (const xmms_stream_type_t *st, xmms_stream_type_key_t key)
gint xmms_stream_type_get_int (const xmms_stream_type_t *st, xmms_stream_type_key_t key)
gboolean xmms_stream_type_match (const xmms_stream_type_t *in_type, const xmms_stream_type_t *out_type)
xmms_stream_type_t * xmms_stream_type_coerce (const xmms_stream_type_t *in, const GList *goal_types)
Find the best pair of formats.
xmms_stream_type_t * _xmms_stream_type_new (const gchar *begin,...)
Detailed Description
xforms
Definition in file streamtype.c.
Typedef Documentation
typedef struct xmms_stream_type_val_St xmms_stream_type_val_t
typedef enum xmms_stream_type_val_type_E xmms_stream_type_val_type_t
Enumeration Type Documentation
enum xmms_stream_type_val_type_E
Enumerator
STRING
INT
Definition at line 36 of file streamtype.c.
Function Documentation
xmms_stream_type_t* _xmms_stream_type_new (const gchar * begin, ...)
Definition at line 362 of file streamtype.c.
Referenced by xmms_stream_type_coerce().
xmms_stream_type_t* xmms_stream_type_coerce (const xmms_stream_type_t * in, const GList * goal_types)
Find the best pair of formats.
Definition at line 240 of file streamtype.c.
gint xmms_stream_type_get_int (const xmms_stream_type_t * st, xmms_stream_type_key_t key)
Definition at line 171 of file streamtype.c.
Referenced by xmms_sample_converter_init(), xmms_sample_frame_size_get(), xmms_sample_ms_to_samples(), xmms_sample_samples_to_ms(), xmms_stream_type_coerce(), xmms_xform_outtype_get_int(), and xmms_xform_plugin_indata_add().
const char* xmms_stream_type_get_str (const xmms_stream_type_t * st, xmms_stream_type_key_t key)
Definition at line 148 of file streamtype.c.
Referenced by xmms_stream_type_coerce(), xmms_stream_type_parse(), xmms_xform_outtype_get_str(), xmms_xform_plugin_indata_add(), and xmms_xform_plugin_supports().
gboolean xmms_stream_type_match (const xmms_stream_type_t * in_type, const xmms_stream_type_t * out_type)
Definition at line 210 of file streamtype.c.
Referenced by xmms_xform_plugin_supports().
xmms_stream_type_t* xmms_stream_type_parse (va_list ap)
Definition at line 71 of file streamtype.c.
Referenced by _xmms_stream_type_new(), xmms_output_stream_type_add(), xmms_xform_outdata_type_add(), xmms_xform_plugin_indata_add(), and xmms_xform_plugin_set_out_stream_type().