XMMS2: src/lib/xmmsipc/transport.c File Reference
transport.c File Reference
#include <stdlib.h>
#include <string.h>
#include <xmmsc/xmmsc_ipc_transport.h>
#include <xmmscpriv/xmmsc_util.h>
#include "socket_unix.h"
#include "socket_tcp.h"
#include "url.h"
Functions
void xmms_ipc_transport_destroy (xmms_ipc_transport_t *ipct)
int xmms_ipc_transport_read (xmms_ipc_transport_t *ipct, char *buffer, int len)
int xmms_ipc_transport_write (xmms_ipc_transport_t *ipct, char *buffer, int len)
xmms_socket_t xmms_ipc_transport_fd_get (xmms_ipc_transport_t *ipct)
xmms_ipc_transport_t * xmms_ipc_server_accept (xmms_ipc_transport_t *ipct)
char * xmms_ipc_hostname (const char *path)
Function Documentation
char* xmms_ipc_hostname (const char * path)
Definition at line 69 of file transport.c.
xmms_ipc_transport_t* xmms_ipc_server_accept (xmms_ipc_transport_t * ipct)
Definition at line 58 of file transport.c.
Referenced by main().
void xmms_ipc_transport_destroy (xmms_ipc_transport_t * ipct)
Definition at line 29 of file transport.c.
xmms_socket_t xmms_ipc_transport_fd_get (xmms_ipc_transport_t * ipct)
Definition at line 51 of file transport.c.
Referenced by main().
int xmms_ipc_transport_read (xmms_ipc_transport_t * ipct, char * buffer, int len)
Definition at line 39 of file transport.c.
Referenced by main(), and xmms_ipc_msg_read_transport().
int xmms_ipc_transport_write (xmms_ipc_transport_t * ipct, char * buffer, int len)
Definition at line 45 of file transport.c.
Referenced by main(), and xmms_ipc_msg_write_transport().