XMMS2: src/lib/xmmsipc/url.h File Reference
url.h File Reference
Data Structures
struct xmms_url_St
Typedefs
typedef struct xmms_url_St xmms_url_t
Functions
xmms_url_t * parse_url (const char *)
Split a URL into its respective parts.
void free_url (xmms_url_t *)
Typedef Documentation
typedef struct xmms_url_St xmms_url_t
Definition at line 14 of file url.h.
Function Documentation
void free_url (xmms_url_t *)
Definition at line 94 of file url.c.
Referenced by xmms_ipc_client_init(), xmms_ipc_hostname(), and xmms_ipc_server_init().
xmms_url_t* parse_url (const char * url)
Split a URL into its respective parts.
Parameters
url The URL to split
Definition at line 17 of file url.c.
Referenced by xmms_ipc_client_init(), xmms_ipc_hostname(), and xmms_ipc_server_init().