XMMS2: src/lib/xmmsipc/url.c File Reference
url.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "url.h"
Functions
xmms_url_t * parse_url (const char *url)
Split a URL into its respective parts.
void free_url (xmms_url_t *url)
Function Documentation
void free_url (xmms_url_t * url)
Referenced by xmms_ipc_client_init(), xmms_ipc_hostname(), and xmms_ipc_server_init().
xmms_url_t* parse_url (const char * url)
Split a URL into its respective parts.
Parameters
url The URL to split
Referenced by xmms_ipc_client_init(), xmms_ipc_hostname(), and xmms_ipc_server_init().