XMMS2: src/xmms/xform_plugin.c File Reference
xform_plugin.c File Reference
#include <xmmspriv/xmms_xform.h>
#include <xmmspriv/xmms_xform_plugin.h>
#include <xmmspriv/xmms_metadata_mapper.h>
#include <xmms/xmms_log.h>
Functions
xmms_plugin_t * xmms_xform_plugin_new (void)
void xmms_xform_plugin_methods_set (xmms_xform_plugin_t *plugin, xmms_xform_methods_t *methods)
Should be called once from the plugin's setupfunc.
gboolean xmms_xform_plugin_verify (xmms_plugin_t *_plugin)
void xmms_xform_plugin_indata_add (xmms_xform_plugin_t *plugin,...)
Add a valid input type to the plugin.
void xmms_xform_plugin_set_out_stream_type (xmms_xform_plugin_t *plugin,...)
Set a static output type to the plugin.
xmms_stream_type_t * xmms_xform_plugin_get_out_stream_type (xmms_xform_plugin_t *plugin)
gboolean xmms_xform_plugin_supports (const xmms_xform_plugin_t *plugin, const xmms_stream_type_t *st, gint *priority)
void xmms_xform_plugin_metadata_basic_mapper_init (xmms_xform_plugin_t *xform_plugin, const xmms_xform_metadata_basic_mapping_t *mappings, gint count)
Configure automatic metadata mapping.
void xmms_xform_plugin_metadata_mapper_init (xmms_xform_plugin_t *xform_plugin, const xmms_xform_metadata_basic_mapping_t *basic_mappings, gint basic_count, const xmms_xform_metadata_mapping_t *mappings, gint count)
Configure automatic metadata mapping.
gboolean xmms_xform_plugin_metadata_mapper_match (const xmms_xform_plugin_t *xform_plugin, xmms_xform_t *xform, const gchar *key, const gchar *value, gsize length)
xmms_config_property_t * xmms_xform_plugin_config_property_register (xmms_xform_plugin_t *xform_plugin, const gchar *name, const gchar *default_value, xmms_object_handler_t cb, gpointer userdata)
xmms_config_property_t * xmms_xform_plugin_config_lookup (xmms_xform_plugin_t *xform_plugin, const gchar *path)
gboolean xmms_xform_plugin_can_init (const xmms_xform_plugin_t *plugin)
gboolean xmms_xform_plugin_can_read (const xmms_xform_plugin_t *plugin)
gboolean xmms_xform_plugin_can_seek (const xmms_xform_plugin_t *plugin)
gboolean xmms_xform_plugin_can_browse (const xmms_xform_plugin_t *plugin)
gboolean xmms_xform_plugin_can_destroy (const xmms_xform_plugin_t *plugin)
gboolean xmms_xform_plugin_init (const xmms_xform_plugin_t *plugin, xmms_xform_t *xform)
gint xmms_xform_plugin_read (const xmms_xform_plugin_t *plugin, xmms_xform_t *xform, xmms_sample_t *buf, gint length, xmms_error_t *error)
gint64 xmms_xform_plugin_seek (const xmms_xform_plugin_t *plugin, xmms_xform_t *xform, gint64 offset, xmms_xform_seek_mode_t whence, xmms_error_t *err)
gboolean xmms_xform_plugin_browse (const xmms_xform_plugin_t *plugin, xmms_xform_t *xform, const gchar *url, xmms_error_t *error)
void xmms_xform_plugin_destroy (const xmms_xform_plugin_t *plugin, xmms_xform_t *xform)
Function Documentation
gboolean xmms_xform_plugin_browse (const xmms_xform_plugin_t * plugin, xmms_xform_t * xform, const gchar * url, xmms_error_t * error)
Definition at line 271 of file xform_plugin.c.
Referenced by xmms_xform_browse_method().
gboolean xmms_xform_plugin_can_browse (const xmms_xform_plugin_t * plugin)
Definition at line 235 of file xform_plugin.c.
Referenced by xmms_xform_browse_method().
gboolean xmms_xform_plugin_can_destroy (const xmms_xform_plugin_t * plugin)
Definition at line 241 of file xform_plugin.c.
gboolean xmms_xform_plugin_can_init (const xmms_xform_plugin_t * plugin)
Definition at line 217 of file xform_plugin.c.
gboolean xmms_xform_plugin_can_read (const xmms_xform_plugin_t * plugin)
Definition at line 223 of file xform_plugin.c.
gboolean xmms_xform_plugin_can_seek (const xmms_xform_plugin_t * plugin)
Definition at line 229 of file xform_plugin.c.
Referenced by xmms_xform_this_seek().
void xmms_xform_plugin_destroy (const xmms_xform_plugin_t * plugin, xmms_xform_t * xform)
Definition at line 278 of file xform_plugin.c.
xmms_stream_type_t* xmms_xform_plugin_get_out_stream_type (xmms_xform_plugin_t * plugin)
Definition at line 117 of file xform_plugin.c.
gboolean xmms_xform_plugin_init (const xmms_xform_plugin_t * plugin, xmms_xform_t * xform)
Definition at line 247 of file xform_plugin.c.
Referenced by xmms_xform_new().
gboolean xmms_xform_plugin_metadata_mapper_match (const xmms_xform_plugin_t * xform_plugin, xmms_xform_t * xform, const gchar * key, const gchar * value, gsize length)
Definition at line 185 of file xform_plugin.c.
Referenced by xmms_xform_metadata_mapper_match().
xmms_plugin_t* xmms_xform_plugin_new (void)
Definition at line 46 of file xform_plugin.c.
Referenced by xmms_plugin_load().
gint xmms_xform_plugin_read (const xmms_xform_plugin_t * plugin, xmms_xform_t * xform, xmms_sample_t * buf, gint length, xmms_error_t * error)
Definition at line 255 of file xform_plugin.c.
Referenced by xmms_xform_this_read().
gint64 xmms_xform_plugin_seek (const xmms_xform_plugin_t * plugin, xmms_xform_t * xform, gint64 offset, xmms_xform_seek_mode_t whence, xmms_error_t * err)
Definition at line 262 of file xform_plugin.c.
Referenced by xmms_xform_this_seek().
gboolean xmms_xform_plugin_supports (const xmms_xform_plugin_t * plugin, const xmms_stream_type_t * st, gint * priority)
Definition at line 123 of file xform_plugin.c.
Referenced by xmms_xform_chain_setup_url_session().
gboolean xmms_xform_plugin_verify (xmms_plugin_t * _plugin)
Definition at line 69 of file xform_plugin.c.
Referenced by xmms_plugin_load().