XMMS2: src/xmms/xform.c File Reference
xform.c File Reference
xforms
#include <string.h>
#include <xmmspriv/xmms_plugin.h>
#include <xmmspriv/xmms_xform.h>
#include <xmmspriv/xmms_streamtype.h>
#include <xmmspriv/xmms_medialib.h>
#include <xmmspriv/xmms_utils.h>
#include <xmmspriv/xmms_xform_plugin.h>
#include <xmms/xmms_ipc.h>
#include <xmms/xmms_log.h>
#include <xmms/xmms_object.h>
Macros
#define READ_CHUNK 4096
#define GEN_AUXDATA_EXTRACTOR_FUNC(typename, xmmsvtypename, type)
Typedefs
typedef struct
xmms_xform_hotspot_St xmms_xform_hotspot_t
typedef struct match_state_St match_state_t
Functions
xmms_xform_t * xmms_xform_find (xmms_xform_t *prev, xmms_medialib_entry_t entry, GList *goal_hints)
const char * xmms_xform_shortname (xmms_xform_t *xform)
void xmms_xform_browse_add_entry_property_str (xmms_xform_t *xform, const gchar *key, const gchar *value)
void xmms_xform_browse_add_entry_property_int (xmms_xform_t *xform, const gchar *key, gint value)
void xmms_xform_browse_add_symlink_args (xmms_xform_t *xform, const gchar *basename, const gchar *url, gint nargs, gchar **args)
void xmms_xform_browse_add_symlink (xmms_xform_t *xform, const gchar *basename, const gchar *url)
void xmms_xform_browse_add_entry_property (xmms_xform_t *xform, const gchar *key, xmmsv_t *val)
void xmms_xform_browse_add_entry (xmms_xform_t *xform, const gchar *filename, guint32 flags)
xmmsv_t * xmms_xform_browse_method (xmms_xform_t *xform, const gchar *url, xmms_error_t *error)
xmmsv_t * xmms_xform_browse (const gchar *url, xmms_error_t *error)
xmms_xform_t * xmms_xform_new (xmms_xform_plugin_t *plugin, xmms_xform_t *prev, xmms_medialib_t *medialib, xmms_medialib_entry_t entry, GList *goal_hints)
xmms_medialib_entry_t xmms_xform_entry_get (xmms_xform_t *xform)
Get the medialib entry played by this xform.
gpointer xmms_xform_private_data_get (xmms_xform_t *xform)
Get private data for this xform.
void xmms_xform_private_data_set (xmms_xform_t *xform, gpointer data)
Set private data for this xform.
void xmms_xform_outdata_type_add (xmms_xform_t *xform,...)
void xmms_xform_outdata_type_set (xmms_xform_t *xform, xmms_stream_type_t *type)
void xmms_xform_outdata_type_copy (xmms_xform_t *xform)
const char * xmms_xform_indata_find_str (xmms_xform_t *xform, xmms_stream_type_key_t key)
const char * xmms_xform_indata_get_str (xmms_xform_t *xform, xmms_stream_type_key_t key)
gint xmms_xform_indata_get_int (xmms_xform_t *xform, xmms_stream_type_key_t key)
xmms_stream_type_t * xmms_xform_outtype_get (xmms_xform_t *xform)
xmms_stream_type_t * xmms_xform_intype_get (xmms_xform_t *xform)
const char * xmms_xform_outtype_get_str (xmms_xform_t *xform, xmms_stream_type_key_t key)
gint xmms_xform_outtype_get_int (xmms_xform_t *xform, xmms_stream_type_key_t key)
gboolean xmms_xform_metadata_mapper_match (xmms_xform_t *xform, const gchar *key, const gchar *value, gsize length)
Attempt to automatically set a metadata property.
gboolean xmms_xform_metadata_set_int (xmms_xform_t *xform, const char *key, int val)
gboolean xmms_xform_metadata_set_str (xmms_xform_t *xform, const char *key, const char *val)
gboolean xmms_xform_metadata_has_val (xmms_xform_t *xform, const gchar *key)
gboolean xmms_xform_metadata_get_int (xmms_xform_t *xform, const char *key, gint32 *val)
gboolean xmms_xform_metadata_get_str (xmms_xform_t *xform, const char *key, const gchar **val)
void xmms_xform_auxdata_barrier (xmms_xform_t *xform)
void xmms_xform_auxdata_set_int (xmms_xform_t *xform, const char *key, gint64 intval)
void xmms_xform_auxdata_set_str (xmms_xform_t *xform, const gchar *key, const gchar *strval)
void xmms_xform_auxdata_set_bin (xmms_xform_t *xform, const gchar *key, gpointer data, gssize len)
gboolean xmms_xform_auxdata_has_val (xmms_xform_t *xform, const gchar *key)
gboolean xmms_xform_auxdata_get_int32 (xmms_xform_t *xform, const gchar *key, gint32 *val)
gboolean xmms_xform_auxdata_get_int64 (xmms_xform_t *xform, const gchar *key, gint64 *val)
gboolean xmms_xform_auxdata_get_str (xmms_xform_t *xform, const gchar *key, const gchar **val)
gboolean xmms_xform_auxdata_get_bin (xmms_xform_t *xform, const gchar *key, const guchar **data, gsize *datalen)
gint xmms_xform_this_read (xmms_xform_t *xform, gpointer buf, gint siz, xmms_error_t *err)
gint64 xmms_xform_this_seek (xmms_xform_t *xform, gint64 offset, xmms_xform_seek_mode_t whence, xmms_error_t *err)
gint xmms_xform_peek (xmms_xform_t *xform, gpointer buf, gint siz, xmms_error_t *err)
Preview data from previous xform.
gchar * xmms_xform_read_line (xmms_xform_t *xform, gchar *line, xmms_error_t *err)
Read one line from previous xform.
gint xmms_xform_read (xmms_xform_t *xform, gpointer buf, gint siz, xmms_error_t *err)
Read data from previous xform.
gint64 xmms_xform_seek (xmms_xform_t *xform, gint64 offset, xmms_xform_seek_mode_t whence, xmms_error_t *err)
Change offset in stream.
const gchar * xmms_xform_get_url (xmms_xform_t *xform)
gboolean xmms_xform_iseos (xmms_xform_t *xform)
const GList * xmms_xform_goal_hints_get (xmms_xform_t *xform)
xmms_xform_t * xmms_xform_chain_setup (xmms_medialib_t *medialib, xmms_medialib_entry_t entry, GList *goal_formats, gboolean rehash)
xmms_xform_t * xmms_xform_chain_setup_session (xmms_medialib_t *medialib, xmms_medialib_session_t *session, xmms_medialib_entry_t entry, GList *goal_formats, gboolean rehash)
xmms_xform_t * xmms_xform_chain_setup_url_session (xmms_medialib_t *medialib, xmms_medialib_session_t *session, xmms_medialib_entry_t entry, const gchar *url, GList *goal_formats, gboolean rehash)
xmms_xform_t * xmms_xform_chain_setup_url (xmms_medialib_t *medialib, xmms_medialib_entry_t entry, const gchar *url, GList *goal_formats, gboolean rehash)
xmms_config_property_t * xmms_xform_config_lookup (xmms_xform_t *xform, const gchar *path)
Detailed Description
xforms
Definition in file xform.c.
Macro Definition Documentation
#define GEN_AUXDATA_EXTRACTOR_FUNC (typename, xmmsvtypename, type)
Value:
gboolean \
    xmms_xform_auxdata_get_##typename (xmms_xform_t *xform, const gchar *key, \
                                       type *val) \
    { \
        const xmmsv_t *obj; \
        obj = xmms_xform_auxdata_get_val (xform, key); \
        return obj && xmmsv_get_##xmmsvtypename (obj, val); \
    }
Definition at line 802 of file xform.c.
#define READ_CHUNK 4096
Definition at line 83 of file xform.c.
Referenced by xmms_xform_new().
Typedef Documentation
typedef struct match_state_St match_state_t
typedef struct xmms_xform_hotspot_St xmms_xform_hotspot_t
Function Documentation
void xmms_xform_auxdata_set_int (xmms_xform_t * xform, const char * key, gint64 intval)
Definition at line 736 of file xform.c.
xmmsv_t* xmms_xform_browse (const gchar * url, xmms_error_t * error)
Definition at line 271 of file xform.c.
void xmms_xform_browse_add_symlink_args (xmms_xform_t * xform, const gchar * basename, const gchar * url, gint nargs, gchar ** args)
Definition at line 121 of file xform.c.
Referenced by xmms_xform_browse_add_symlink().
xmmsv_t* xmms_xform_browse_method (xmms_xform_t * xform, const gchar * url, xmms_error_t * error)
Definition at line 250 of file xform.c.
Referenced by xmms_xform_browse().
xmms_xform_t* xmms_xform_chain_setup (xmms_medialib_t * medialib, xmms_medialib_entry_t entry, GList * goal_formats, gboolean rehash)
Definition at line 1355 of file xform.c.
xmms_xform_t* xmms_xform_chain_setup_session (xmms_medialib_t * medialib, xmms_medialib_session_t * session, xmms_medialib_entry_t entry, GList * goal_formats, gboolean rehash)
Definition at line 1372 of file xform.c.
Referenced by xmms_xform_chain_setup().
xmms_xform_t* xmms_xform_chain_setup_url (xmms_medialib_t * medialib, xmms_medialib_entry_t entry, const gchar * url, GList * goal_formats, gboolean rehash)
Definition at line 1442 of file xform.c.
xmms_xform_t* xmms_xform_chain_setup_url_session (xmms_medialib_t * medialib, xmms_medialib_session_t * session, xmms_medialib_entry_t entry, const gchar * url, GList * goal_formats, gboolean rehash)
Definition at line 1392 of file xform.c.
Referenced by xmms_xform_chain_setup_session(), and xmms_xform_chain_setup_url().
xmms_xform_t * xmms_xform_find (xmms_xform_t * prev, xmms_medialib_entry_t entry, GList * goal_hints)
Definition at line 1150 of file xform.c.
Referenced by xmms_xform_browse().
const GList* xmms_xform_goal_hints_get (xmms_xform_t * xform)
Definition at line 1192 of file xform.c.
const char* xmms_xform_indata_find_str (xmms_xform_t * xform, xmms_stream_type_key_t key)
Definition at line 432 of file xform.c.
Referenced by xmms_xform_indata_find_str().
xmms_stream_type_t* xmms_xform_intype_get (xmms_xform_t * xform)
Definition at line 462 of file xform.c.
gboolean xmms_xform_metadata_get_int (xmms_xform_t * xform, const char * key, gint32 * val)
Definition at line 543 of file xform.c.
gboolean xmms_xform_metadata_get_str (xmms_xform_t * xform, const char * key, const gchar ** val)
Definition at line 559 of file xform.c.
Referenced by xmms_xform_metadata_set_str().
gboolean xmms_xform_metadata_set_int (xmms_xform_t * xform, const char * key, int val)
Definition at line 488 of file xform.c.
Referenced by xmms_xform_metadata_parse_compilation(), and xmms_xform_metadata_parse_number().
gboolean xmms_xform_metadata_set_str (xmms_xform_t * xform, const char * key, const char * val)
Definition at line 497 of file xform.c.
Referenced by xmms_xform_metadata_parse_replay_gain().
xmms_xform_t* xmms_xform_new (xmms_xform_plugin_t * plugin, xmms_xform_t * prev, xmms_medialib_t * medialib, xmms_medialib_entry_t entry, GList * goal_hints)
Definition at line 347 of file xform.c.
Referenced by xmms_xform_browse(), and xmms_xform_find().
void xmms_xform_outdata_type_set (xmms_xform_t * xform, xmms_stream_type_t * type)
Definition at line 418 of file xform.c.
Referenced by xmms_xform_outdata_type_copy().
xmms_stream_type_t* xmms_xform_outtype_get (xmms_xform_t * xform)
Definition at line 456 of file xform.c.
Referenced by xmms_xform_intype_get().
gint xmms_xform_outtype_get_int (xmms_xform_t * xform, xmms_stream_type_key_t key)
Definition at line 475 of file xform.c.
Referenced by xmms_xform_indata_get_int().
const char* xmms_xform_outtype_get_str (xmms_xform_t * xform, xmms_stream_type_key_t key)
Definition at line 468 of file xform.c.
Referenced by xmms_xform_indata_get_str().
const char * xmms_xform_shortname (xmms_xform_t * xform)
Definition at line 832 of file xform.c.
Referenced by xmms_xform_browse(), xmms_xform_metadata_set_str(), xmms_xform_this_read(), and xmms_xform_this_seek().
gint xmms_xform_this_read (xmms_xform_t * xform, gpointer buf, gint siz, xmms_error_t * err)
Definition at line 910 of file xform.c.
Referenced by xmms_xform_read().
gint64 xmms_xform_this_seek (xmms_xform_t * xform, gint64 offset, xmms_xform_seek_mode_t whence, xmms_error_t * err)
Definition at line 988 of file xform.c.
Referenced by xmms_xform_seek().