XMMS2: src/includepriv/xmmspriv/xmms_xform_plugin.h File Reference
xmms_xform_plugin.h File Reference
Functions
gboolean xmms_xform_plugin_can_init (const xmms_xform_plugin_t *plugin)
gboolean xmms_xform_plugin_can_read (const xmms_xform_plugin_t *plugin)
gboolean xmms_xform_plugin_can_seek (const xmms_xform_plugin_t *plugin)
gboolean xmms_xform_plugin_can_browse (const xmms_xform_plugin_t *plugin)
gboolean xmms_xform_plugin_can_destroy (const xmms_xform_plugin_t *plugin)
gboolean xmms_xform_plugin_init (const xmms_xform_plugin_t *plugin, xmms_xform_t *xform)
gboolean xmms_xform_plugin_metadata_mapper_match (const xmms_xform_plugin_t *xform_plugin, xmms_xform_t *xform, const gchar *key, const gchar *value, gsize length)
gint xmms_xform_plugin_read (const xmms_xform_plugin_t *plugin, xmms_xform_t *xform, xmms_sample_t *buf, gint length, xmms_error_t *error)
gint64 xmms_xform_plugin_seek (const xmms_xform_plugin_t *plugin, xmms_xform_t *xform, gint64 offset, xmms_xform_seek_mode_t whence, xmms_error_t *err)
gboolean xmms_xform_plugin_browse (const xmms_xform_plugin_t *plugin, xmms_xform_t *xform, const gchar *url, xmms_error_t *error)
void xmms_xform_plugin_destroy (const xmms_xform_plugin_t *plugin, xmms_xform_t *xform)
gboolean xmms_xform_plugin_supports (const xmms_xform_plugin_t *plugin, const xmms_stream_type_t *st, gint *priority)
xmms_stream_type_t * xmms_xform_plugin_get_out_stream_type (xmms_xform_plugin_t *plugin)
Function Documentation
gboolean xmms_xform_plugin_browse (const xmms_xform_plugin_t * plugin, xmms_xform_t * xform, const gchar * url, xmms_error_t * error)
Definition at line 271 of file xform_plugin.c.
Referenced by xmms_xform_browse_method().
gboolean xmms_xform_plugin_can_browse (const xmms_xform_plugin_t * plugin)
Definition at line 235 of file xform_plugin.c.
Referenced by xmms_xform_browse_method().
gboolean xmms_xform_plugin_can_destroy (const xmms_xform_plugin_t * plugin)
Definition at line 241 of file xform_plugin.c.
gboolean xmms_xform_plugin_can_init (const xmms_xform_plugin_t * plugin)
Definition at line 217 of file xform_plugin.c.
gboolean xmms_xform_plugin_can_read (const xmms_xform_plugin_t * plugin)
Definition at line 223 of file xform_plugin.c.
gboolean xmms_xform_plugin_can_seek (const xmms_xform_plugin_t * plugin)
Definition at line 229 of file xform_plugin.c.
Referenced by xmms_xform_this_seek().
void xmms_xform_plugin_destroy (const xmms_xform_plugin_t * plugin, xmms_xform_t * xform)
Definition at line 278 of file xform_plugin.c.
xmms_stream_type_t* xmms_xform_plugin_get_out_stream_type (xmms_xform_plugin_t * plugin)
Definition at line 117 of file xform_plugin.c.
gboolean xmms_xform_plugin_init (const xmms_xform_plugin_t * plugin, xmms_xform_t * xform)
Definition at line 247 of file xform_plugin.c.
Referenced by xmms_xform_new().
gboolean xmms_xform_plugin_metadata_mapper_match (const xmms_xform_plugin_t * xform_plugin, xmms_xform_t * xform, const gchar * key, const gchar * value, gsize length)
Definition at line 185 of file xform_plugin.c.
Referenced by xmms_xform_metadata_mapper_match().
gint xmms_xform_plugin_read (const xmms_xform_plugin_t * plugin, xmms_xform_t * xform, xmms_sample_t * buf, gint length, xmms_error_t * error)
Definition at line 255 of file xform_plugin.c.
Referenced by xmms_xform_this_read().
gint64 xmms_xform_plugin_seek (const xmms_xform_plugin_t * plugin, xmms_xform_t * xform, gint64 offset, xmms_xform_seek_mode_t whence, xmms_error_t * err)
Definition at line 262 of file xform_plugin.c.
Referenced by xmms_xform_this_seek().
gboolean xmms_xform_plugin_supports (const xmms_xform_plugin_t * plugin, const xmms_stream_type_t * st, gint * priority)
Definition at line 123 of file xform_plugin.c.
Referenced by xmms_xform_chain_setup_url_session().