XMMS2: src/lib/xmmstypes/xmmsv_general.c File Reference
xmmsv_general.c File Reference
#include <stdlib.h>
#include <string.h>
#include <xmmscpriv/xmmsv.h>
#include <xmmscpriv/xmmsc_util.h>
#include <xmmsc/xmmsv.h>
#include <xmmsc/xmmsc_util.h>
Functions
xmmsv_t * _xmmsv_new (xmmsv_type_t type)
Allocates new xmmsv_t and references it.
xmmsv_t * xmmsv_new_none (void)
Allocates a new empty xmmsv_t.
xmmsv_t * xmmsv_new_error (const char *errstr)
Allocates a new error xmmsv_t.
xmmsv_t * xmmsv_new_int (int64_t i)
Allocates a new integer xmmsv_t.
xmmsv_t * xmmsv_new_float (float i)
Allocates a new float xmmsv_t.
xmmsv_t * xmmsv_new_string (const char *s)
Allocates a new string xmmsv_t.
xmmsv_t * xmmsv_new_bin (const unsigned char *data, unsigned int len)
Allocates a new binary data xmmsv_t.
xmmsv_t * xmmsv_ref (xmmsv_t *val)
References the xmmsv_t.
void xmmsv_unref (xmmsv_t *val)
Decreases the references for the xmmsv_t When the number of references reaches 0 it will be freed.
xmmsv_type_t xmmsv_get_type (const xmmsv_t *val)
Get the type of the value.
int xmmsv_is_type (const xmmsv_t *val, xmmsv_type_t t)
Check if value is of specified type.
int xmmsv_is_error (const xmmsv_t *val)
Check if the value stores an error.
int xmmsv_get_error (const xmmsv_t *val, const char **r)
Retrieves an error string describing the server error from the value.
int xmmsv_get_int32 (const xmmsv_t *val, int32_t *r)
Retrieves a signed integer from the value.
int xmmsv_get_int64 (const xmmsv_t *val, int64_t *r)
Retrieves a signed integer from the value.
int xmmsv_get_float (const xmmsv_t *val, float *r)
Retrieves a float from the value.
int xmmsv_get_string (const xmmsv_t *val, const char **r)
Retrieves a string from the value.
int xmmsv_get_coll (const xmmsv_t *val, xmmsv_t **c)
Retrieves a collection from the value.
int xmmsv_get_bin (const xmmsv_t *val, const unsigned char **r, unsigned int *rlen)
Retrieves binary data from the value.
Variables
const char * xmmsv_default_source_pref []
Function Documentation
xmmsv_t* _xmmsv_new (xmmsv_type_t type)
Allocates new xmmsv_t and references it.
Definition at line 47 of file xmmsv_general.c.
Referenced by xmmsv_new_bin(), xmmsv_new_bitbuffer(), xmmsv_new_bitbuffer_ro(), xmmsv_new_coll(), xmmsv_new_dict(), xmmsv_new_error(), xmmsv_new_float(), xmmsv_new_int(), xmmsv_new_list(), xmmsv_new_none(), and xmmsv_new_string().
Variable Documentation
const char* xmmsv_default_source_pref[]
Initial value:
= {
    "server",
    "client/*",
    "plugin/playlist",
    "plugin/segment",
    "plugin/nibbler",
    "plugin/id3v2",
    "plugin/*",
    "*",
    NULL
}
Definition at line 29 of file xmmsv_general.c.
Referenced by xmms_medialib_init(), and xmmsv_propdict_to_dict().