XMMS2: src/includepriv/xmmspriv/xmms_fetch_spec.h File Reference
xmms_fetch_spec.h File Reference
#include <glib.h>
#include <xmmspriv/xmms_fetch_info.h>
#include <xmmsc/xmmsv_coll.h>
#include <xmmsc/xmmsv.h>
#include <xmms/xmms_error.h>
Data Structures
struct xmms_fetch_spec_St
Typedefs
typedef struct xmms_fetch_spec_St xmms_fetch_spec_t
Enumerations
enum aggregate_function_t {
AGGREGATE_FIRST, AGGREGATE_SUM, AGGREGATE_MAX, AGGREGATE_MIN,
AGGREGATE_SET, AGGREGATE_LIST, AGGREGATE_RANDOM, AGGREGATE_AVG,
AGGREGATE_END
}
Functions
xmms_fetch_spec_t * xmms_fetch_spec_new (xmmsv_t *fetch, xmms_fetch_info_t *info, s4_sourcepref_t *prefs, xmms_error_t *err)
Converts a fetch specification in xmmsv_t form into a fetch_spec_t structure.
void xmms_fetch_spec_free (xmms_fetch_spec_t *spec)
Typedef Documentation
typedef struct xmms_fetch_spec_St xmms_fetch_spec_t
Definition at line 38 of file xmms_fetch_spec.h.
Enumeration Type Documentation
enum aggregate_function_t
Enumerator
AGGREGATE_FIRST
AGGREGATE_SUM
AGGREGATE_MAX
AGGREGATE_MIN
AGGREGATE_SET
AGGREGATE_LIST
AGGREGATE_RANDOM
AGGREGATE_AVG
AGGREGATE_END
Definition at line 26 of file xmms_fetch_spec.h.
Function Documentation
void xmms_fetch_spec_free (xmms_fetch_spec_t * spec)
Definition at line 575 of file fetchspec.c.
Referenced by xmms_fetch_spec_free(), and xmms_medialib_query().
xmms_fetch_spec_t* xmms_fetch_spec_new (xmmsv_t * fetch, xmms_fetch_info_t * info, s4_sourcepref_t * prefs, xmms_error_t * err)
Converts a fetch specification in xmmsv_t form into a fetch_spec_t structure.
Definition at line 537 of file fetchspec.c.
Referenced by xmms_medialib_query().