XMMS2: src/xmms/fetchspec.c File Reference
fetchspec.c File Reference
#include <xmmspriv/xmms_fetch_spec.h>
#include <xmmspriv/xmms_fetch_info.h>
#include <xmms/xmms_log.h>
#include <string.h>
#include <stdlib.h>
Functions
xmms_fetch_spec_t * xmms_fetch_spec_new (xmmsv_t *fetch, xmms_fetch_info_t *info, s4_sourcepref_t *prefs, xmms_error_t *err)
Converts a fetch specification in xmmsv_t form into a fetch_spec_t structure.
void xmms_fetch_spec_free (xmms_fetch_spec_t *spec)
Function Documentation
void xmms_fetch_spec_free (xmms_fetch_spec_t * spec)
Referenced by xmms_fetch_spec_free(), and xmms_medialib_query().
xmms_fetch_spec_t* xmms_fetch_spec_new (xmmsv_t * fetch, xmms_fetch_info_t * info, s4_sourcepref_t * prefs, xmms_error_t * err)
Converts a fetch specification in xmmsv_t form into a fetch_spec_t structure.
Referenced by xmms_medialib_query().