XMMS2: src/includepriv/xmmspriv/xmms_metadata_mapper.h File Reference
xmms_metadata_mapper.h File Reference
#include <glib.h>
#include <xmms/xmms_xformplugin.h>
Functions
gboolean xmms_metadata_mapper_match (GHashTable *table, xmms_xform_t *xform, const gchar *key, const gchar *value, gsize value_length)
GHashTable * xmms_metadata_mapper_init (const xmms_xform_metadata_basic_mapping_t *basic_mapping, gint basic_count, const xmms_xform_metadata_mapping_t *mapping, gint count)
Function Documentation
GHashTable* xmms_metadata_mapper_init (const xmms_xform_metadata_basic_mapping_t * basic_mapping, gint basic_count, const xmms_xform_metadata_mapping_t * mapping, gint count)
Definition at line 240 of file metadata.c.
Referenced by xmms_xform_plugin_metadata_basic_mapper_init(), and xmms_xform_plugin_metadata_mapper_init().
gboolean xmms_metadata_mapper_match (GHashTable * table, xmms_xform_t * xform, const gchar * key, const gchar * value, gsize value_length)
Definition at line 273 of file metadata.c.
Referenced by xmms_xform_plugin_metadata_mapper_match().