XMMS2: src/xmms/utils.c File Reference
utils.c File Reference
Miscellaneous internal utility functions specific to the daemon.
#include <stdlib.h>
#include <glib.h>
#include <stdarg.h>
#include <string.h>
#include <ctype.h>
#include <xmmsc/xmmsc_util.h>
#include <xmms/xmms_util.h>
#include <xmmspriv/xmms_utils.h>
#include <xmmsc/xmmsc_strlist.h>
Functions
char * xmms_build_path (const char *first,...)
Build path to file in xmms2 configuration directory.
gchar * xmms_build_playlist_url (const gchar *plspath, const gchar *file)
gint xmms_natcmp_len (const gchar *str1, gint len1, const gchar *str2, gint len2)
gint xmms_natcmp (const gchar *str1, const gchar *str2)
gboolean xmms_strcase_equal (gconstpointer v1, gconstpointer v2)
Case insensitive version of g_str_equal.
guint xmms_strcase_hash (gconstpointer v)
Case insensitive version of g_str_hash.
Detailed Description
Miscellaneous internal utility functions specific to the daemon.
Definition in file utils.c.
Function Documentation
char* xmms_build_path (const char * first, ...)
Build path to file in xmms2 configuration directory.
Parameters
first The first file or directory name in the path.
... Additional file/directory names.
Returns
Absolute path to a file or directory.
Definition at line 39 of file utils.c.
gchar* xmms_build_playlist_url (const gchar * plspath, const gchar * file)
Definition at line 103 of file utils.c.
gint xmms_natcmp (const gchar * str1, const gchar * str2)
Definition at line 151 of file utils.c.
gint xmms_natcmp_len (const gchar * str1, gint len1, const gchar * str2, gint len2)
Definition at line 128 of file utils.c.
Referenced by xmms_natcmp().
gboolean xmms_strcase_equal (gconstpointer v1, gconstpointer v2)
Case insensitive version of g_str_equal.
Parameters
v1 first string
v2 second string
Returns
TRUE if first string equals the seconds tring, otherwise FALSE
Definition at line 163 of file utils.c.
Referenced by xmms_metadata_mapper_init().
guint xmms_strcase_hash (gconstpointer v)
Case insensitive version of g_str_hash.
Parameters
v a string
Returns
the case insensitive hash code of the string
Definition at line 177 of file utils.c.
Referenced by xmms_metadata_mapper_init().