XMMS2: src/include/xmms/xmms_object.h File Reference
xmms_object.h File Reference
#include <glib.h>
#include <xmms/xmms_error.h>
#include <xmmsc/xmmsc_idnumbers.h>
#include <xmmsc/xmmsv.h>
#include <xmmsc/xmmsv_coll.h>
Data Structures
struct xmms_object_St
struct xmms_object_cmd_arg_t
Macros
#define XMMS_OBJECT_MID 0x00455574
#define XMMS_OBJECT_CMD_MAX_ARGS 6
#define XMMS_OBJECT(p) ((xmms_object_t *)p)
#define XMMS_IS_OBJECT(p) (XMMS_OBJECT (p)->id == XMMS_OBJECT_MID)
#define xmms_object_new(objtype, destroyfunc) (objtype *) __int_xmms_object_new (sizeof (objtype), destroyfunc)
Typedefs
typedef struct xmms_object_St xmms_object_t
typedef void(* xmms_object_destroy_func_t)(xmms_object_t *object)
typedef void(* xmms_object_handler_t)(xmms_object_t *object, xmmsv_t *data, gpointer userdata)
typedef void(* xmms_object_cmd_func_t)(xmms_object_t *object, xmms_object_cmd_arg_t *arg)
Functions
xmmsv_t * xmms_convert_and_kill_list (GList *list)
xmmsv_t * xmms_convert_and_kill_string (gchar *str)
xmmsv_t * xmms_convert_and_kill_bin (GString *gs)
int xmms_bin_to_gstring (xmmsv_t *value, GString **gs)
int dummy_identity (xmmsv_t *value, xmmsv_t **arg)
void xmms_object_cleanup (xmms_object_t *object)
Cleanup all the resources for the object.
void xmms_object_connect (xmms_object_t *object, guint32 signalid, xmms_object_handler_t handler, gpointer userdata)
Connect to a signal that is emitted by this object.
void xmms_object_disconnect (xmms_object_t *object, guint32 signalid, xmms_object_handler_t handler, gpointer userdata)
Disconnect from a signal.
void xmms_object_emit (xmms_object_t *object, guint32 signalid, xmmsv_t *data)
Emit a signal and thus call all the handlers that are connected.
void xmms_object_cmd_arg_init (xmms_object_cmd_arg_t *arg)
Initialize a command argument.
void xmms_object_cmd_add (xmms_object_t *object, guint cmdid, const xmms_object_cmd_func_t desc)
Add a command that could be called from the client API to a object.
void xmms_object_cmd_call (xmms_object_t *object, guint cmdid, xmms_object_cmd_arg_t *arg)
Call a command with argument.
gpointer xmms_object_ref (gpointer obj)
void xmms_object_unref (gpointer obj)
xmms_object_t * __int_xmms_object_new (gint size, xmms_object_destroy_func_t destfunc)
Macro Definition Documentation
#define XMMS_IS_OBJECT (p) (XMMS_OBJECT (p)->id == XMMS_OBJECT_MID)
Referenced by xmms_object_cleanup(), xmms_object_connect(), xmms_object_disconnect(), xmms_object_emit(), xmms_object_ref(), and xmms_object_unref().
#define XMMS_OBJECT (p) ((xmms_object_t *)p)
Referenced by main(), xmms_bindata_init(), xmms_coll_sync_init(), xmms_collection_changed_msg_send(), xmms_collection_init(), xmms_config_init(), xmms_config_property_callback_remove(), xmms_config_property_callback_set(), xmms_config_property_set_data(), xmms_courier_init(), xmms_ipc_init(), xmms_mediainfo_reader_start(), xmms_medialib_init(), xmms_object_ref(), xmms_object_unref(), xmms_output_new(), xmms_playlist_init(), xmms_playlist_updater_init(), xmms_visualization_new(), and xmms_xform_object_init().
#define XMMS_OBJECT_CMD_MAX_ARGS 6
#define XMMS_OBJECT_MID 0x00455574
Referenced by __int_xmms_object_new().
#define xmms_object_new (objtype, destroyfunc) (objtype *) __int_xmms_object_new (sizeof (objtype), destroyfunc)
Referenced by main(), xmms_bindata_init(), xmms_coll_sync_init(), xmms_collection_init(), xmms_config_init(), xmms_courier_init(), xmms_ipc_init(), xmms_mediainfo_reader_start(), xmms_medialib_init(), xmms_output_new(), xmms_output_plugin_new(), xmms_playlist_init(), xmms_playlist_updater_init(), xmms_sample_converter_init(), xmms_stream_type_parse(), xmms_visualization_new(), xmms_xform_new(), xmms_xform_object_init(), and xmms_xform_plugin_new().
Typedef Documentation
typedef void(* xmms_object_cmd_func_t)(xmms_object_t *object, xmms_object_cmd_arg_t *arg)
typedef void(* xmms_object_destroy_func_t)(xmms_object_t *object)
typedef void(* xmms_object_handler_t)(xmms_object_t *object, xmmsv_t *data, gpointer userdata)
typedef struct xmms_object_St xmms_object_t
Function Documentation
xmms_object_t* __int_xmms_object_new (gint size, xmms_object_destroy_func_t destfunc)
gpointer xmms_object_ref (gpointer obj)
Referenced by __int_xmms_object_new(), xmms_coll_sync_init(), xmms_collection_init(), xmms_courier_init(), xmms_mediainfo_reader_start(), xmms_output_new(), xmms_playlist_init(), xmms_playlist_updater_init(), xmms_visualization_new(), xmms_xform_new(), and xmms_xform_outdata_type_set().
void xmms_object_unref (gpointer obj)
Referenced by xmms_config_shutdown(), xmms_ipc_shutdown(), xmms_output_plugin_switch(), xmms_plugin_load(), xmms_plugin_shutdown(), xmms_sample_converter_init(), xmms_stream_type_parse(), xmms_xform_browse(), xmms_xform_chain_setup(), xmms_xform_chain_setup_url(), xmms_xform_chain_setup_url_session(), and xmms_xform_new().