XMMS2: src/includepriv/xmmspriv/xmms_xform.h File Reference
xmms_xform.h File Reference
#include <xmms/xmms_xformplugin.h>
#include <xmmspriv/xmms_medialib.h>
#include <xmmspriv/xmms_streamtype.h>
#include <xmmspriv/xmms_plugin.h>
Macros
#define xmms_xform_find_plugin(name) (xmms_xform_plugin_t *) xmms_plugin_find (XMMS_PLUGIN_TYPE_XFORM, name)
#define XMMS_XFORM_BUILTIN_DEFINE(shname, name, ver, desc, setupfunc) XMMS_BUILTIN_DEFINE(XMMS_PLUGIN_TYPE_XFORM, XMMS_XFORM_API_VERSION, shname, name, ver, desc, (gboolean (*)(gpointer))setupfunc)
Functions
xmms_xform_t * xmms_xform_new (xmms_xform_plugin_t *plugin, xmms_xform_t *prev, xmms_medialib_t *medialib, xmms_medialib_entry_t entry, GList *goal_hints)
const gchar * xmms_xform_outtype_get_str (xmms_xform_t *xform, xmms_stream_type_key_t key)
gint xmms_xform_outtype_get_int (xmms_xform_t *xform, xmms_stream_type_key_t key)
xmms_stream_type_t * xmms_xform_outtype_get (xmms_xform_t *xform)
xmms_plugin_t * xmms_xform_plugin_new (void)
gboolean xmms_xform_plugin_verify (xmms_plugin_t *plugin)
xmms_xform_t * xmms_xform_chain_setup (xmms_medialib_t *medialib, xmms_medialib_entry_t entry, GList *goal_formats, gboolean rehash)
xmms_xform_t * xmms_xform_chain_setup_session (xmms_medialib_t *medialib, xmms_medialib_session_t *session, xmms_medialib_entry_t entry, GList *goal_fmts, gboolean rehash)
xmms_xform_t * xmms_xform_chain_setup_url_session (xmms_medialib_t *medialib, xmms_medialib_session_t *session, xmms_medialib_entry_t entry, const gchar *url, GList *goal_fmts, gboolean rehash)
xmms_xform_t * xmms_xform_chain_setup_url (xmms_medialib_t *medialib, xmms_medialib_entry_t entry, const gchar *url, GList *goal_formats, gboolean rehash)
gint64 xmms_xform_this_seek (xmms_xform_t *xform, gint64 offset, xmms_xform_seek_mode_t whence, xmms_error_t *err)
int xmms_xform_this_read (xmms_xform_t *xform, gpointer buf, int siz, xmms_error_t *err)
gboolean xmms_xform_iseos (xmms_xform_t *xform)
const GList * xmms_xform_goal_hints_get (xmms_xform_t *xform)
xmms_stream_type_t * xmms_xform_intype_get (xmms_xform_t *xform)
void xmms_xform_outdata_type_set (xmms_xform_t *xform, xmms_stream_type_t *type)
xmmsv_t * xmms_xform_browse (const gchar *url, xmms_error_t *error)
xmmsv_t * xmms_xform_browse_method (xmms_xform_t *xform, const gchar *url, xmms_error_t *error)
const char * xmms_xform_indata_find_str (xmms_xform_t *xform, xmms_stream_type_key_t key)
Macro Definition Documentation
#define XMMS_XFORM_BUILTIN_DEFINE (shname, name, ver, desc, setupfunc) XMMS_BUILTIN_DEFINE(XMMS_PLUGIN_TYPE_XFORM, XMMS_XFORM_API_VERSION, shname, name, ver, desc, (gboolean (*)(gpointer))setupfunc)
#define xmms_xform_find_plugin (name) (xmms_xform_plugin_t *) xmms_plugin_find (XMMS_PLUGIN_TYPE_XFORM, name)
Function Documentation
xmmsv_t* xmms_xform_browse (const gchar * url, xmms_error_t * error)
xmmsv_t* xmms_xform_browse_method (xmms_xform_t * xform, const gchar * url, xmms_error_t * error)
Referenced by xmms_xform_browse().
xmms_xform_t* xmms_xform_chain_setup (xmms_medialib_t * medialib, xmms_medialib_entry_t entry, GList * goal_formats, gboolean rehash)
xmms_xform_t* xmms_xform_chain_setup_session (xmms_medialib_t * medialib, xmms_medialib_session_t * session, xmms_medialib_entry_t entry, GList * goal_fmts, gboolean rehash)
Referenced by xmms_xform_chain_setup().
xmms_xform_t* xmms_xform_chain_setup_url (xmms_medialib_t * medialib, xmms_medialib_entry_t entry, const gchar * url, GList * goal_formats, gboolean rehash)
xmms_xform_t* xmms_xform_chain_setup_url_session (xmms_medialib_t * medialib, xmms_medialib_session_t * session, xmms_medialib_entry_t entry, const gchar * url, GList * goal_fmts, gboolean rehash)
Referenced by xmms_xform_chain_setup_session(), and xmms_xform_chain_setup_url().
const GList* xmms_xform_goal_hints_get (xmms_xform_t * xform)
const char* xmms_xform_indata_find_str (xmms_xform_t * xform, xmms_stream_type_key_t key)
Referenced by xmms_xform_indata_find_str().
xmms_stream_type_t* xmms_xform_intype_get (xmms_xform_t * xform)
xmms_xform_t* xmms_xform_new (xmms_xform_plugin_t * plugin, xmms_xform_t * prev, xmms_medialib_t * medialib, xmms_medialib_entry_t entry, GList * goal_hints)
Referenced by xmms_xform_browse(), and xmms_xform_find().
void xmms_xform_outdata_type_set (xmms_xform_t * xform, xmms_stream_type_t * type)
Referenced by xmms_xform_outdata_type_copy().
xmms_stream_type_t* xmms_xform_outtype_get (xmms_xform_t * xform)
Referenced by xmms_xform_intype_get().
gint xmms_xform_outtype_get_int (xmms_xform_t * xform, xmms_stream_type_key_t key)
Referenced by xmms_xform_indata_get_int().
const gchar* xmms_xform_outtype_get_str (xmms_xform_t * xform, xmms_stream_type_key_t key)
Referenced by xmms_xform_indata_get_str().
xmms_plugin_t* xmms_xform_plugin_new (void)
Referenced by xmms_plugin_load().
gboolean xmms_xform_plugin_verify (xmms_plugin_t * plugin)
Referenced by xmms_plugin_load().
int xmms_xform_this_read (xmms_xform_t * xform, gpointer buf, int siz, xmms_error_t * err)
gint64 xmms_xform_this_seek (xmms_xform_t * xform, gint64 offset, xmms_xform_seek_mode_t whence, xmms_error_t * err)
Referenced by xmms_xform_seek().