XMMS2: src/includepriv/xmmspriv/xmms_collection.h File Reference
xmms_collection.h File Reference
#include <glib.h>
#include <xmms/xmms_error.h>
#include <xmmsc/xmmsv_coll.h>
#include <xmmspriv/xmms_playlist.h>
#include <xmmspriv/xmms_medialib.h>
Macros
#define XMMS_COLLECTION_NUM_NAMESPACES 2
#define XMMS_COLLECTION_PLAYLIST_CHANGED_MSG(dag, name) xmms_collection_changed_msg_send (dag, xmms_collection_changed_msg_new (XMMS_COLLECTION_CHANGED_UPDATE, name, XMMS_COLLECTION_NS_PLAYLISTS))
Typedefs
typedef struct xmms_coll_dag_St xmms_coll_dag_t
typedef void(* FuncApplyToColl)(xmms_coll_dag_t *dag, xmmsv_t *coll, xmmsv_t *parent, void *udata)
Enumerations
enum xmms_collection_namespace_id_t { XMMS_COLLECTION_NSID_COLLECTIONS, XMMS_COLLECTION_NSID_PLAYLISTS, XMMS_COLLECTION_NSID_ALL, XMMS_COLLECTION_NSID_INVALID }
Functions
xmms_coll_dag_t * xmms_collection_init (xmms_medialib_t *medialib)
Initializes a new xmms_coll_dag_t.
xmmsv_t * xmms_collection_query_ids (xmms_coll_dag_t *dag, xmmsv_t *coll, xmms_error_t *err)
Find the ids of the media matched by a collection.
void xmms_collection_foreach_in_namespace (xmms_coll_dag_t *dag, xmms_collection_namespace_id_t nsid, GHFunc f, void *udata)
Apply a function to all the collections in a given namespace.
void xmms_collection_apply_to_all_collections (xmms_coll_dag_t *dag, FuncApplyToColl f, void *udata)
Apply a function of type FuncApplyToColl to all the collections in all namespaces.
void xmms_collection_apply_to_collection (xmms_coll_dag_t *dag, xmmsv_t *coll, FuncApplyToColl f, void *udata)
Apply a function of type FuncApplyToColl to the given collection.
xmmsv_t * xmms_collection_get_pointer (xmms_coll_dag_t *dag, const gchar *collname, guint namespace)
void xmms_collection_update_pointer (xmms_coll_dag_t *dag, const gchar *name, xmms_collection_namespace_id_t nsid, xmmsv_t *newtarget)
Update a reference to point to a new collection.
gchar * xmms_collection_find_alias (xmms_coll_dag_t *dag, xmms_collection_namespace_id_t nsid, xmmsv_t *value, const gchar *key)
Reverse-search the list of collections in the given namespace to find the first pair whose value matches the argument.
xmms_medialib_entry_t xmms_collection_get_random_media (xmms_coll_dag_t *dag, xmmsv_t *source)
Get a random media entry from the given collection.
xmms_collection_namespace_id_t xmms_collection_get_namespace_id (const gchar *namespace)
Find the namespace id corresponding to a namespace string.
const gchar * xmms_collection_get_namespace_string (xmms_collection_namespace_id_t nsid)
Find the namespace name (string) corresponding to a namespace id.
gboolean xmms_collection_get_int_attr (xmmsv_t *coll, const gchar *attrname, gint *val)
Extract an attribute from a collection as an integer.
gboolean xmms_collection_set_int_attr (xmmsv_t *coll, const gchar *attrname, gint newval)
Set the attribute of a collection as an integer.
xmmsv_t * xmms_collection_changed_msg_new (xmms_collection_changed_action_t type, const gchar *plname, const gchar *namespace)
void xmms_collection_changed_msg_send (xmms_coll_dag_t *colldag, xmmsv_t *dict)
xmmsv_t * xmms_collection_snapshot (xmms_coll_dag_t *dag)
void xmms_collection_restore (xmms_coll_dag_t *dag, xmmsv_t *snapshot)
Macro Definition Documentation
#define XMMS_COLLECTION_NUM_NAMESPACES 2
Referenced by xmms_collection_apply_to_all_collections(), xmms_collection_foreach_in_namespace(), xmms_collection_get_pointer(), and xmms_collection_init().
#define XMMS_COLLECTION_PLAYLIST_CHANGED_MSG (dag, name) xmms_collection_changed_msg_send (dag, xmms_collection_changed_msg_new (XMMS_COLLECTION_CHANGED_UPDATE, name, XMMS_COLLECTION_NS_PLAYLISTS))
Typedef Documentation
typedef void(* FuncApplyToColl)(xmms_coll_dag_t *dag, xmmsv_t *coll, xmmsv_t *parent, void *udata)
typedef struct xmms_coll_dag_St xmms_coll_dag_t
Enumeration Type Documentation
enum xmms_collection_namespace_id_t
Enumerator
XMMS_COLLECTION_NSID_COLLECTIONS
XMMS_COLLECTION_NSID_PLAYLISTS
XMMS_COLLECTION_NSID_ALL
XMMS_COLLECTION_NSID_INVALID
Function Documentation
void xmms_collection_apply_to_all_collections (xmms_coll_dag_t * dag, FuncApplyToColl f, void * udata)
Apply a function of type FuncApplyToColl to all the collections in all namespaces.
Parameters
dag The collection DAG.
f The function to apply to all the collections.
udata Additional user data parameter passed to the function.
Referenced by xmms_collection_restore(), and xmms_collection_snapshot().
void xmms_collection_apply_to_collection (xmms_coll_dag_t * dag, xmmsv_t * coll, FuncApplyToColl f, void * udata)
Apply a function of type FuncApplyToColl to the given collection.
Parameters
dag The collection DAG.
coll The collection on which to apply the function.
f The function to apply to all the collections.
udata Additional user data parameter passed to the function.
Referenced by xmms_collection_get_random_media().
xmmsv_t* xmms_collection_changed_msg_new (xmms_collection_changed_action_t type, const gchar * plname, const gchar * namespace)
void xmms_collection_changed_msg_send (xmms_coll_dag_t * colldag, xmmsv_t * dict)
void xmms_collection_foreach_in_namespace (xmms_coll_dag_t * dag, xmms_collection_namespace_id_t nsid, GHFunc f, void * udata)
Apply a function to all the collections in a given namespace.
Parameters
dag The collection DAG.
nsid The namespace id.
f The function to apply to all the collections.
udata Additional user data parameter passed to the function.
xmms_collection_namespace_id_t xmms_collection_get_namespace_id (const gchar * namespace)
Find the namespace id corresponding to a namespace string.
Parameters
namespace The namespace string.
Returns
The namespace id.
const gchar* xmms_collection_get_namespace_string (xmms_collection_namespace_id_t nsid)
Find the namespace name (string) corresponding to a namespace id.
Parameters
nsid The namespace id.
Returns
The namespace name (string).
xmmsv_t* xmms_collection_get_pointer (xmms_coll_dag_t * dag, const gchar * collname, guint namespace)
void xmms_collection_restore (xmms_coll_dag_t * dag, xmmsv_t * snapshot)
xmmsv_t* xmms_collection_snapshot (xmms_coll_dag_t * dag)