XMMS2: src/include/xmms/xmms_streamtype.h File Reference
xmms_streamtype.h File Reference
#include <xmmsc/xmmsc_compiler.h>
#include <glib.h>
#include <string.h>
Macros
#define XMMS_STREAM_TYPE_BEGIN "placeholder"
#define XMMS_STREAM_TYPE_PRIORITY_FALLBACK 40
#define XMMS_STREAM_TYPE_PRIORITY_DEFAULT 50
Typedefs
typedef enum xmms_stream_type_key_E xmms_stream_type_key_t
typedef struct xmms_stream_type_St xmms_stream_type_t
Enumerations
enum xmms_stream_type_key_E {
XMMS_STREAM_TYPE_END, XMMS_STREAM_TYPE_MIMETYPE, XMMS_STREAM_TYPE_URL, XMMS_STREAM_TYPE_FMT_FORMAT,
XMMS_STREAM_TYPE_FMT_CHANNELS, XMMS_STREAM_TYPE_FMT_SAMPLERATE, XMMS_STREAM_TYPE_PRIORITY, XMMS_STREAM_TYPE_NAME
}
Functions
const char * xmms_stream_type_get_str (const xmms_stream_type_t *st, xmms_stream_type_key_t key)
gint xmms_stream_type_get_int (const xmms_stream_type_t *st, xmms_stream_type_key_t key)
Macro Definition Documentation
#define XMMS_STREAM_TYPE_BEGIN "placeholder"
Definition at line 30 of file xmms_streamtype.h.
Referenced by xmms_stream_type_coerce().
#define XMMS_STREAM_TYPE_PRIORITY_DEFAULT 50
Definition at line 47 of file xmms_streamtype.h.
Referenced by xmms_stream_type_parse(), and xmms_xform_plugin_supports().
#define XMMS_STREAM_TYPE_PRIORITY_FALLBACK 40
Definition at line 46 of file xmms_streamtype.h.
Typedef Documentation
typedef enum xmms_stream_type_key_E xmms_stream_type_key_t
typedef struct xmms_stream_type_St xmms_stream_type_t
Definition at line 44 of file xmms_streamtype.h.
Enumeration Type Documentation
enum xmms_stream_type_key_E
Enumerator
XMMS_STREAM_TYPE_END
XMMS_STREAM_TYPE_MIMETYPE
XMMS_STREAM_TYPE_URL
XMMS_STREAM_TYPE_FMT_FORMAT
XMMS_STREAM_TYPE_FMT_CHANNELS
XMMS_STREAM_TYPE_FMT_SAMPLERATE
XMMS_STREAM_TYPE_PRIORITY
XMMS_STREAM_TYPE_NAME
Definition at line 32 of file xmms_streamtype.h.
Function Documentation
gint xmms_stream_type_get_int (const xmms_stream_type_t * st, xmms_stream_type_key_t key)
Definition at line 171 of file streamtype.c.
Referenced by xmms_sample_converter_init(), xmms_sample_frame_size_get(), xmms_sample_ms_to_samples(), xmms_sample_samples_to_ms(), xmms_stream_type_coerce(), xmms_xform_outtype_get_int(), and xmms_xform_plugin_indata_add().
const char* xmms_stream_type_get_str (const xmms_stream_type_t * st, xmms_stream_type_key_t key)
Definition at line 148 of file streamtype.c.
Referenced by xmms_stream_type_coerce(), xmms_stream_type_parse(), xmms_xform_outtype_get_str(), xmms_xform_plugin_indata_add(), and xmms_xform_plugin_supports().